### ISSUE TITLE
Optional Remember Me Expiration Parameter

### ISSUE THREAD

**Issue by psgibbs** [maxcountryman/flask-login#105]
Would there be any interest in adding an optional 'duration' argument to login_user method, which would override the remember_me cookie expiration for that specific sign-on event.

If so, I'm more than happy to submit a pull request. This is definitely a use case I've got, and I don't think it would be a significant increase in LoC or complexity, but I completely understand if you want to keep flask-login as minimal as possible.

**Comment by SirCmpwn** [comment]
+1

**Comment by cabalamat** [comment]
+1, would have saved me effort on a recent project

**Comment by maxcountryman** [comment]
@cabalamat feel free to submit a PR.

**Comment by cabalamat** [comment]
What's a PR?

**Comment by SirCmpwn** [comment]
A pull request. He's suggesting you implement it yourself and send the changes upstream.

**Comment by ioparaskev** [comment]
Is there a way to achieve different "remember_me" times now?
Somehow to implement a min cookie duration and a max cookie duration?

**Comment by alanhamlett** [comment]
Implemented with #361.
