### ISSUE TITLE
avoid trigger load_user() for static resource(url)

### ISSUE THREAD

**Issue by shoujs** [maxcountryman/flask-login#11]
I observed the load_user() method is trigger even when loading a static resource like a css file.  I confirmed it after looking into the source code.  it all happens in my development environment.
It may be ok in production for we will use a web server to handle the static resources.

**Comment by SantjagoCorkez** [comment]
So any chance the check-disabling code is back into tree? Just provide a configuration option for those who haven't ever heard of 'frontend server'. Like ``LOGIN_FORCE_STATIC_PATH_CHECK``
