### ISSUE TITLE
Support force-logout for active sessions

### ISSUE THREAD

**Issue by ThiefMaster** [maxcountryman/flask-login#155]
Right now you can only force-logout a remember-me token by using a custom token. It would be nice if there was a clean way to do this for active sessions, too.

From a quick look at the code this could probably be done by making `get_id` return e.g. a tuple of `userid, token` and the `user_loader` handling this token accordingly (retrieving the user from the DB and checking if the tokens match). However, the documentation is quite clear about the user id having to be `unicode` and a second look at the code shows that the user id actually converted to a string at some point: `data = encode_cookie(str(session['user_id']))` (actually, shouldn't this be `unicode` and not `str`?).

Sure, I could use a custom string representation such as `id:token` but it feels dirty.

**Comment by AusTiNQ** [comment]
@maxcountryman Can u advice me - how can be force logout implemented? Just a use case - I need to revoke all active sessions of some user to force him to re-login without using fresh_login_required in application code.

**Comment by ddorian** [comment]
Change the app.secret_key ?

**Comment by ThiefMaster** [comment]
That sounds like a terrible idea if you just want to logout a single user.

**Comment by AusTiNQ** [comment]
@ddorian No, this will cause force logout of ALL users, not single one.
@ThiefMaster why? For example, I want to implement a functionality like "Terminate all sessions except this" - and this will be helpful.

I've already solved my problem by using custom-generated auth token which signed with user ID and some randomly-generated hash which is stored in the database along with user ID and other credentials. When I need to perform a force logout of specific user - I can change this hash and all previous remember tokens will cease to be valid - problem solved :) Why not?

**Comment by ThiefMaster** [comment]
Yes, terminating all sessions for all users is one thing. Then changing the secret key would be ok.

But just to force-logout one user? Nope..

**Comment by ddorian** [comment]
@all
Sorry guys, misread it at force-logout for all.

**Comment by philipithomas** [comment]
We just implemented this on our end. It was pretty hacky with flask-login, requiring hijacking of the get_id function to incorporate both a user_id and session_id. 

Some better separation of `id`

**Comment by tyan4g** [comment]
I find this is needed, on my situation

1. the user fresh login in current session
2. the user reset the password in another session
3. the user is still login in the current session

really need some way to force that user to reenter the password. cause they already reset there password.right??  and please support....

**Comment by alanhamlett** [comment]
This can easily be done by returning a unique session id for the user along with or instead of their id. Change the session id and the user is logged out.

To require re-entering password without logging out, just set a key on the Flask session and check for that key in your login_handler, then redirect to your password re-enter page preserving the original url.

**Comment by alanhamlett** [comment]
An example of force-logging out a user's sessions has been added to the docs:

https://flask-login.readthedocs.io/en/latest/#alternative-tokens
