### ISSUE TITLE
question: protection against replay attacks?

### ISSUE THREAD

**Issue by joernhees** [maxcountryman/flask-login#190]
does flask-login protect you against replay attacks?

**Comment by maxcountryman** [comment]
Flask-Login itself does not do anything specific to protect against replay attacks. However, since login state is held in a cookie, short of a malicious program copying the cookie, it should be fairly nontrivial to compromise. In other words, I can't presently think of a relevant replay attack.

**Comment by joernhees** [comment]
sorry if my memory faded a bit since i asked this question...

I think at the time i was looking into an app which uses flask and flask-login mostly with http (not https) requests. I wasn't sure at the time if there is the possibility for a replay attack based on listening in to a user who is logged in. Neither flask-login nor the default flask session (based on secure cookies as well) seem to have any counters / timeouts in them. So if i just record both, couldn't i come back even days later, set them and the application would just treat me as if i was the user?

**Comment by alanhamlett** [comment]
We can put a timestamp in the cookie and have the login session expire after a certain time, but it could be bypassed if they capture the remember me cookie.

**Comment by joernhees** [comment]
It seems to me that by default (without saving anything on the server) the server can't know if it has seen a request before. Timeouts can only reduce the time of vulnerability but never close it.

Thing is that flask and flask-login are very convenient for developers (big compliment) and names like "secure cookie" and "session protection" (http://flask-login.readthedocs.org/en/latest/#session-protection) seem to imply to developers that things are pretty secure...

but then take the open wifi behind NAT scenario in a starbucks combined with HTTP traffic and suddenly i have the same IP, i could set the same user agent, and i could set all the same cookies and just re-use them it seems (i'm happy if someone proves me wrong here).

Maybe flask-login would do developers a big favor if it by default logged warnings for non HTTPS requests?

**Comment by maxcountryman** [comment]
In general, where possible, I think it's always better to use HTTPS, so I agree.

I think maybe a nonce might function a bit better than a timestamp.

**Comment by alanhamlett** [comment]
Yea, a nonce stored per user is better. Then just revoke that nonce to invalidate the user's session.

**Comment by davidism** [comment]
Going to need persistent storage for that if this is going to work across app restarts.  Hooks for `create_nonce` and `check_nonce` should be available so devs can choose to use memcached, database, etc., along with a default that uses a global dict with a lock or something.  I don't have time for a proper pr at the moment, but something like:

~~~python
class NonceSource:
    def create(user):
        raise NotImplementedError

    def check(data):
        raise NotImplementedError

class DictNonce(NonceSource):
    def __init__(self):
        self.cache = defaultdict(set)
        self.lock = Lock()

    def create(user):
        with lock:
            self.cache[user.id].add(str(uuid4()))

    def check(data):
        id = int(data['user_id'])
        value = data.get('nonce')
        
        if value is None:
            return False

        with lock:
            values = self.cache[id]

            if value in values:
                values.discard(value)
                return True

            return False

login_manager.nonce_source = DictNonce()
~~~

But this could really just be left to the developer.  It's already possible to implement this by adding a `Flask.before_request` handler which gets/sets a value in the session on every request.

**Comment by gjhawar** [comment]
So nonce will be like a server side cookie implementation. Correct?

**Comment by xcash** [comment]
You don't need to modify anything in flask-login for this.
It's up to the developer to use a secure login mechanism. If one is developing an intranet portal, logging a warning or force https or making the session expire is useless and noisy.
If you're developing a public app then you must deal with what type of authentication you want. 
One thing i love of flask-login is i can customize the object used to check credentials, so you can use an UserSession object which expires, do other checks or anything you want.
What is called userid in flask-login could be also an authsessionid in a separate table.

@joernhees If you can sniff everything there's no protection as you're a MITM. Only full https in this case can help. And an expiring session if you're only collecting cookies.

**Comment by alanhamlett** [comment]
@xcash is right, this should be handled in the `login_manager.user_loader` by returning the user's ID along with some session token/timestamp that you can change/check to invalidate all of the user's sessions.
