### ISSUE TITLE
User-friendly flashed messages 

### ISSUE THREAD

**Issue by eleweek** [maxcountryman/flask-login#193]
Hi, I'd like to add user friendly messages. 

I.e. "You must be signed in to send messages" instead of "You must be signed in to access '/send_message'.

If I understand correctly, there is no elegant way to do this with flask-login. I am considering adding another decorator @login_required_msg("You must be signed in to send message"). Is it a good way? The other way is to make @login_required decorator take optional params, which requires a hack(IIRC).

**Comment by maxcountryman** [comment]
I think wrapping the existing methods is actually the way to go here. No need to introduce this into flask-login proper.
