### ISSUE TITLE
Flask login message

### ISSUE THREAD

**Issue by iho** [maxcountryman/flask-login#203]
How to translate this login message? 
When  i try flask-babel with ```login_manager.login_message = lazy_gettext('Login message')```
I  get error 
TypeError: l'Ввійдіть будь ласка' is not JSON serializable . 
I get this error because json do not know how to encode lazy srings. 
I cannot change json serializable.

**Comment by aborovyi** [comment]
If I understood correctly your question, then according to the section [Customizing the login process] (https://flask-login.readthedocs.org/en/latest/#customizing-the-login-process) :

> The default message flashed is `Please log in to access this page`. To customize the message, set **LoginManager.login_message**:

> ```login_manager.login_message = u"Bonvolu ensaluti por uzi tio paĝo."```

**Comment by markgalup** [comment]
I don't believe that is the answer to his question. I am having the same issue with the user object generating a TypeError, stating it is not JSON serializable. It would be great to find an authoritative answer on this as it seems to have changed somewhat recently since most of the code examples I have found.

**Comment by maxcountryman** [comment]
@markgalup please provide a full stack trace and a minimal test case so we can look into this. Thanks!

**Comment by markgalup** [comment]
Thanks for your quick attention to this! I will do my best to provide the information you mentioned, along with two (apparent) solutions I found to the problem. I would be grateful to hear your opinion on which of the situations is the more appropriate solution, or if both are optimal and potentially work together. I am new to markdown so my apologies if there are issues...

Below is the python code to for login() via Flask-Login. Please note that this only handles a user which is inactive (user.is_active() == False) in the current state:
```python
@app.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # jsonify(user = user)    # This is the more complex solution - implementing a JSONEncoder class.
        if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
                user.authenticated = True
                db.session.add(user)
                db.session.commit()
                login_user(user, remember=True)
                # session['user_id'] = user.id  # This is the far simpler solution which seems to work.
                if not current_user.is_active():
                    flash('Detected user is inactive.')
                    return redirect(url_for('index'))
```
Below is the python code for the custom JSONEncoder class (in __init__.py), which operates on the User class (in models.py):
```python
class UserJSONEncoder(JSONEncoder):
    def default(self, obj):
        if isinstance(obj, models.User):
            return {
                'id': obj.id,
                'email': obj.email,
                'username': obj.username,
                'authenticated': obj.authenticated,
                'active': obj.active,
            }
        return super(UserJSONEncoder, self).default(obj)

app.json_encoder = UserJSONEncoder
```

and the User class:

```python
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True)
    _password = db.Column(db.String(128))
    username = db.Column(db.String(64), unique=True)
    authenticated = db.Column(db.Boolean, default=False)
    active = db.Column(db.Boolean, default=False)

    @hybrid_property
    def password(self):
        return self._password

    @password.setter
    def _set_password(self, plaintext):
        self._password = bcrypt.generate_password_hash(plaintext)

    # Flask-Login User Methods

    def is_authenticated(self):
        return self.authenticated

    def is_active(self):
        return self.active

    def is_anonymous(self):
        return False

    def get_id(self):
        try:
            return unicode(self.id) # Python 2
        except NameError:
            return str(self.id) # Python 3

    def __repr__(self):
        return "<User %r>" % (self.username)
```

And the HTML which is posting via a form...
```html
{% block content %}



<h1 id='login-header'>Sign In</h1>
<form class='pure-form' action="" method="post" name="login">
    {{ form.hidden_tag() }}
    <p>

        <p>{{ form.email(size=50, placeholder='Email') }}</p>
        <p>{% for error in form.email.errors %}
            <span class='login-error'>[{{ error }}]</span>
        {% endfor %}<br></p>
    </p>
    <p>

        <p>{{ form.password(size=50, placeholder='Password') }}</p>
        <p>{% for error in form.password.errors %}
            <span class='login-error'>[{{ error }}]</span>
        {% endfor %}<br></p>
    </p>
    <!-- <p>{{ form.remember_me }} Remember Me?</p> -->
    <ul id='login-buttons'>
        <li><input class='pure-button pure-button-primary' type="submit" name="button" value="Sign In"></li>
        <li><input class='pure-button' type="submit" name="button" value="Create Account"></li>
    </ul>
</form>
{% endblock %}
```

Apologies if that's too much information. A little detail about the solutions...
I first found that creating the JSONEncoder class solved the issue of logging in and not generating a TypeError (object not JSON serializable). But after logging in, the current_user remained the anonymous user, which I've seen documented as a problem elsewhere. So I used the second solution - settings session['user_id'] = user.id manually - and that solved the issue of current_user being the logged in user. I then commented out the jsonify(user=user) solution, and the login process continued to work along with the current_user remaining the currently logged in user. Also, please note that I needed to manually remove the site's cookie to get the behaviors to reset, and also I am only accessing my app via localhost.

Thank you very much for your excellent contributions and your assistance with this. Hopefully my documentation will help some other folks experiencing the same issue.


All the best,
Mark Galup

**Comment by DmonteiroD** [comment]
I am having exactly the same issue, like iho.

**Comment by DmonteiroD** [comment]
This solves the issue:

`
from flask.json import JSONEncoder

class CustomJSONEncoder(JSONEncoder):
    """This class adds support for lazy translation texts to Flask's
    JSON encoder. This is necessary when flashing translated texts."""
    def default(self, obj):
        from speaklater import is_lazy_string
        if is_lazy_string(obj):
            try:
                return unicode(obj)  # python 2
            except NameError:
                return str(obj)  # python 3
        return super(CustomJSONEncoder, self).default(obj)

app.json_encoder = CustomJSONEncoder
`
Source:
http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xiv-i18n-and-l10n

**Comment by markgalup** [comment]
Thanks DmonteiroD!

**Comment by maxcountryman** [comment]
Good to close this now?

**Comment by iho** [comment]
> I cannot change json serializable.
@maxcountryman custom JSONEncoder is bad design. It will be nice have  callback than attribute.

**Comment by maxcountryman** [comment]
@iho feel free to propose a change in the form of a PR.

**Comment by iho** [comment]
> localize_callback
I do not see it before :|

**Comment by maxcountryman** [comment]
@iho please refer to the [documentation](http://flask-login.readthedocs.org/en/latest/#localization) in the future.
