### ISSUE TITLE
AnonymousUserMixin.is_authenticated is not a property

### ISSUE THREAD

**Issue by skyler** [maxcountryman/flask-login#208]
Documentation shows `is_authenticated` being accessed as a property

https://flask-login.readthedocs.org/en/latest/#anonymous-users

> By default, when a user is not actually logged in, current_user is set to an AnonymousUserMixin object. It has the following properties and methods:
>
> is_active and is_authenticated are False
> is_anonymous is True
> get_id() returns None

However, 
````
In [1]: from flask.ext.login import AnonymousUserMixin
In [2]: a = AnonymousUserMixin()
In [3]: a.is_authenticated
Out[3]: <bound method AnonymousUserMixin.is_authenticated of <flask_login.AnonymousUserMixin object at 0x68b4a10>>
```
```
In [6]: import flask.ext.login
In [7]: flask.ext.login.__version__
Out[7]: '0.2.11'
```

**Comment by skyler** [comment]
It looks like this is a change that isn't available yet:
https://github.com/maxcountryman/flask-login/blob/a96de342eae560deec008a02179f593c3799b3ba/CHANGES#L6-11

This may be an interesting change for code that depends on the truthiness of `current_user.is_authenticated` because a method will always be "true".

E.g.
```
# old code, new version of Flask-Login
if current_user.is_authenticated:
    do_dangerous_things()
    # except is_authenticated is now a method and the user isn't actually logged-in
```

**Comment by maxcountryman** [comment]
Please use the version of the documentation that corresponds to your flask-login, e.g. http://flask-login.readthedocs.org/en/0.2.11/#your-user-class.
