### ISSUE TITLE
How to protect generic <username>-routes?

### ISSUE THREAD

**Issue by karland** [maxcountryman/flask-login#209]
Hi, thanks for Flask-Login.

I have routes that are constructed similar to for instance github-routes (e.g. `https://github.com/karland`)

```python
@auth.route("/<username>")
@login_required
def username(username):
    if username != current_user.username:
       return redirect(url_for('main.login'))
    user = User.query.filter_by(username=username).first_or_404()
    ...
```

Unfortunately, all generic routes need to be protected to prevent that a logged in user can access all `<username>`-routes and not only his ones. Therfore, the `if`-statement is necessary. Unfortunately, it is not very DRY and I wondered whether it would be possible to get something like

```python
@login_required(username)
```

as part of the standard library. What do you think? Thanks.

**Comment by maxcountryman** [comment]
I think this is something best implemented in your project, where you can write a custom decorator that does what you want (DRYs things out) but doesn't necessarily belong in Flask-Login proper.

I'd think something like this might do the trick:

```python
def username_required(fn):
    @login_required
    def decorated(*args, **kwargs):
        if username != current_user.username:
            return redirect(...)
        return fn(*args, **kwargs)
    return decorated
```

**Comment by karland** [comment]
@maxcountryman Thanks for your fast reply and suggestion. I agree, that a custom decorator is probably best in this context, especially since the `current_user.username` depends on my model. Your suggestion did not work though, but never mind, it pointed me into the right direction. Now, it took me a little while before I had a chance to come up with a solution. Here is my custom decorator:

```python
def login_and_username_required(func):
    @wraps(func)
    @login_required
    def function_wrapper(*args, **kwargs):
        if kwargs is None or 'username' not in kwargs:
            raise NameError("'username' is not defined")
        elif kwargs['username'] != current_user.username:
            flash("You can only access your own directory!")
            return redirect(url_for('main.login'))
        return func(*args, **kwargs)
    return function_wrapper
```

Best and thanks again.
