### ISSUE TITLE
Can we make a new release as there were bunch of changes pushed to master since 0.2.11?

### ISSUE THREAD

**Issue by lipis** [maxcountryman/flask-login#210]

**Comment by alanhamlett** [comment]
We should merge the refactor branch to master too.

**Comment by maxcountryman** [comment]
I'd like to do a release soon. There's a number of breaking changes that need to be documented properly first (some of them are in the CHANGELOG but I need to review the changes to make sure we haven't missed anything).

As @alanhamlett there are other unmerged changes that would be good to get in as well.

**Comment by michael-kehoe** [comment]
Ping on doing a release. Really need the X-Forwarded-For fix

**Comment by maxcountryman** [comment]
@michael-kehoe use a pinned rev for now.

**Comment by akkumar** [comment]
The docs here -https://flask-login.readthedocs.org/en/latest/ - refer to 0.3.0 .  Can 0.3.0 be pushed to pip please ? 

"  Could not find a version that satisfies the requirement flask-login==0.3.0 (from -r requirements.txt (line 7)) (from versions: 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11) " 

This would be useful. Thanks in advance.

**Comment by maxcountryman** [comment]
@akkumar use a pinned rev for now.

**Comment by jmagnusson** [comment]
@maxcountryman AFAIK it's not possible to rely on packages external to PyPI in your own package. It won't install with pip. So a release would be awesome :smile:

**Comment by maxcountryman** [comment]
@jmagnusson please use Google next time:

`pip install -e "git+https://github.com/maxcountryman/flask-login.git@253f5fe704550434de05d77f97273012ff55a52c#egg=Flask-Login"`

**Comment by maxcountryman** [comment]
We will do a release when we have time to do a release. Until then, as has already been said: use a pinned rev.

**Comment by maxcountryman** [comment]
`0.3.0` is live on PyPI now.
