### ISSUE TITLE
[Security] Open redirect vulnerability in sample code (documentation)

### ISSUE THREAD

**Issue by TimVaes** [maxcountryman/flask-login#211]
Hi,

There is an open redirect vulnerability within the sample code of the documentation.
People could copy-paste it without thinking about the consequences (such as phishing attacks).

It might be good to state explicitly that the "next" argument has to be validated before passing it to the redirect function.

Talking about the following lines in the documentation:
`        login_user(user)`
`        flash("Logged in successfully.")`
`        return redirect(request.args.get("next") or url_for("index"))`

/Tim

**Comment by maxcountryman** [comment]
Thanks for pointing this out! I will update the documentation.
