### ISSUE TITLE
I want get username from session instead of parameter what is in url

### ISSUE THREAD

**Issue by dayiguizhen** [maxcountryman/flask-login#215]
@main.route('/about')
    def user():
         return '<h1>Hello,%s</h1>' %user.email;
    
    @main.route('/about/<username>')
    def user(username):
        user = User.query.filter_by(username=username).first();
        return '<h1>Hello,%s</h1>' %user.email;

can I get username from session or browser cookie? What do I should do?

**Comment by eleweek** [comment]
You can use ```current_user```: https://flask-login.readthedocs.org/en/latest/#flask.ext.login.current_user

**Comment by dayiguizhen** [comment]
Thanks.I did it.
