### ISSUE TITLE
Request: Don't disable @login_required on the TESTING flag

### ISSUE THREAD

**Issue by SheepGotoHeaven** [maxcountryman/flask-login#216]
From the flask-login docs:

> It can be convenient to globally turn off authentication when unit testing. To enable this, if either of the application configuration variables LOGIN_DISABLED or TESTING is set to True, this decorator will be ignored.

This has been frustrating me recently, as I want to leave

```python
flask.Flask.config['TESTING'] == True
```

to disable Flask's internal error-handling and get better error printouts, but I also want to be able to write tests ensuring that I'm applying proper authentication requirements to all of my endpoints.

There are simple enough ways around this, but it seems like unnecessary coupling, especially when there's an alternate flag already provided.

**Comment by davidism** [comment]
Flask-Login itself is already tested, you don't need to test that `login_required` really requires logins in your own app.  You can use `login_user()` and `current_user` without needing the decorator enabled.

However, this seems to be "fixed" in #117 and 2fc6a7e06b560233eadb44f8eba74e2a1bce88be.  There just hasn't been a new release yet.

**Comment by SheepGotoHeaven** [comment]
@davidism, appreciate you linking to that pull request. Looking at the comments there allowed me to figure out that setting

TESTING = True
LOGIN_DISABLED = False

actually provides the functionality I want. The language in the docs seem to indicate that if either value is set to `True` then the logins are disabled (basically an `or` operation on disabling). In light of that discovering, closing the ticket.
