### ISSUE TITLE
Set-Cookie header is injected into static content requests, breaking caching.

### ISSUE THREAD

**Issue by fake-name** [maxcountryman/flask-login#226]
Right now, if `LoginManager()` is installed in a flask-app, it adds a `set-cookie` header to ALL requests, *including* static content.

This breaks (at least) Nginx reverse-proxy caching, as [nginx disables caching](http://stackoverflow.com/a/9232739/268006) if it sees a set-cookie header, even if the flask app itself returns the proper HTTP 304 for the relevant resource.

Realistically, setting cookies on static content is kind of silly anyways, and probably shouldn't happen in the first place.

It'd be nice if flask-login only set cookies on things that actually can change.

**Comment by maxcountryman** [comment]
Try `master`.

**Comment by maxcountryman** [comment]
@fake-name Can you give 0.3.0 a try and let me know if you're still experiencing this issue?

**Comment by fake-name** [comment]
Sorry, I've been busy with work. Let me have a poke in a bit.

**Comment by fake-name** [comment]
I'm still seeing `set-cookie()` responses in 304 responses for static content:

```
Remote Address:10.1.1.8:5000
Request URL:http://10.1.1.8:5000/static/css/bootstrap.css
Request Method:GET
Status Code:200 OK
Response Headers
view source
Cache-Control:max-age=43200, public
Content-Length:145291
Content-Type:text/css; charset=utf-8
Date:Fri, 11 Sep 2015 02:12:46 GMT
ETag:"flask-1434251896.1921802-145291-3847100388"
Expires:Fri, 11 Sep 2015 14:12:46 GMT
Last-Modified:Sun, 14 Jun 2015 03:18:16 GMT
Server:Werkzeug/0.10.4 Python/3.4.0
Set-Cookie:session=.eJwlzUEKAjEQRNG79HoWyWSS2HOZELurUBSFRFfi3R1w_x__I40D8yI7-31ikXZ12cVT2IBQNHbUbunMQKfytMIrYpdFbA621_OGx9GzhKwpU2NO6rVvbk5sNRuLIUFVa4aVw70nxn-yyvcHw9QmOA.CNPKHg.wyMfNl93s7UvGRpspzrVQAje0lY; HttpOnly; Path=/
Request Headers
view source
Accept:text/css,*/*;q=0.1
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Cookie:remember_token=2|8cf5bef028ec5741c33f0f289fb4027e2de65ee5; fldt=hide; session=.eJwlzUEKAjEQRNG79HoWyWSS2HOZELurUBSFRFfi3R1w_x__I40D8yI7-31ikXZ12cVT2IBQNHbUbunMQKfytMIrYpdFbA621_OGx9GzhKwpU2NO6rVvbk5sNRuLIUFVa4aVw70nxn-yyvcHw9QmOA.CNPKHg.wyMfNl93s7UvGRpspzrVQAje0lY
Host:10.1.1.8:5000
Pragma:no-cache
Referer:http://10.1.1.8:5000/
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2300.0 Iron/43.0.2300.0 Safari/537.36
```

**Comment by fake-name** [comment]
Ok, derp. 

I fiddled around with my test-case, and even with login manager completely removed, I'm *still* getting session cookies. 

I'm actually not sure /where/ they're coming from, I'm not using much other then just plain flask and sqlalchemy.

**Comment by maxcountryman** [comment]
That sounds like a potential issue with Flask itself, yeah.

**Comment by fake-name** [comment]
I could have sworn I disabled `flask-login`, and the cookie went away, but I have no idea what I did, and it doesn't seem to do that now.

**Comment by Ismael-Hery** [comment]
@Garrett-R: you save my day!
