### ISSUE TITLE
Docs: backward-incompatibility notice

### ISSUE THREAD

**Issue by xcash** [maxcountryman/flask-login#230]
It would be useful to put a notice in the docs regarding the change of methods->properties in your user class.
Probably 99% of apps out there uses the `current_user.is_authenticated()` call in templates or code.
I needed some time yesterday to figure out why that code started to fail on a production environment. :D

I can do a pull-request for this if you like.

**Comment by maxcountryman** [comment]
Sure, that's fine if you want to submit a PR. It's also mentioned in the CHANGES document which is where people should look to find this information canonically.

**Comment by xcash** [comment]
@maxcountryman sure, but try to find it within the docs. :) There are no release notes nor changelog links. I can add those too. ;)

**Comment by dpgaspar** [comment]
+1

**Comment by Atorich** [comment]
+100

```
why that code started to fail on a production environment.
```
+1000

**Comment by Atorich** [comment]
Why this issue closed due to issue in another repo with non-constructive solution (to use flask-login==0.2.11) ?

**Comment by maxcountryman** [comment]
@Atorich version pinning is the correct solution.
