### ISSUE TITLE
Flask WTF and session_protection = 'strong'

### ISSUE THREAD

**Issue by shipperizer** [maxcountryman/flask-login#231]
This https://github.com/maxcountryman/flask-login/commit/9c8f3ca7441fa0abb506093c7161b5aa4cad88df has created me a lot of problems using forms with csrf token enabled and session protection set to strong
this is the issue that I was getting as well https://github.com/lepture/flask-wtf/issues/197 and unsetting the session_protection made it work.

I can't figure out how I can make it work again using 'strong', could you please provide me some useful links or examples?

**Comment by Avrong** [comment]
I have the same problem

**Comment by maxcountryman** [comment]
It would be helpful if you can narrow the problem down a bit: are you able to construct a minimal example demonstrating your issue?

**Comment by shipperizer** [comment]
sure...

I had this on the template:
```html5
      <form action="" method="post" name="register" enctype="multipart/form-data" class="form-horizontal form-register" novalidate>


        {{ form.hidden_tag() }}
```
 nothing special on the form, just plain fields

```python
class CustomerForm(Form):
    name = StringField(
        'Contact name', [validators.Required()],
        description={'tooltips': 'Please provide your full name'}
    )
    position = TextField(
        'Job title', description={'placeholder': 'Optional'}
    )
    exhibitor = StringField(
        'Exhibitor name', [validators.Required()],
        description={'tooltips': 'The name of the cinema chain'}
    )
```
this as configuration of the login_manager
```python

def init_login(app):
    login_manager.init_app(app)
    login_manager.login_view = 'public.login'
    login_manager.session_protection = 'strong'
```
and a normal view with nothing special:
```python
def post(self):
        form = CustomerForm(request.form)
        partner = False
        if request.url_rule.endpoint == 'public.become_partner':
            form = PartnerForm(request.form)
            partner = True
        .....
```

What happens is that with session protection set to 'strong' every requests has an empty cookie that takes out all the info inside the session, i added some debug logging in the library code and found that I got 2 extra fields inside the session compared to the only one with the 'strong' settings:

```python
<SecureCookieSession {'_id': 'd39d1e0b473c7ac50717c6b445702c6995a9c15577e60a24e53f0a8fc1dfbb061d12e2854d53157e260992a25b7b0f57bb0cfee146c5ccb689abc3174e7220f0', '_fresh': True, 'user_id': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiJwcmVzaWRlbnRAd2hpdGVob3VzZS5nb3YiLCJsYXN0X3VwZGF0ZWQiOiIyMDE1LTA5LTE0VDExOjQwOjU4LjgzMFoiLCJwYXNzd29yZF9oYXNoIjoieWVsbG93ZG9nMTIzIiwiYXBwcm92YWxfc3RhdHVzIjp7ImFwcHJvdmVkIjp0cnVlLCJ2ZXJpZmllZCI6dHJ1ZX0sImRhdGVfcmVnaXN0ZXJlZCI6IjIwMTUtMDktMTRUMTE6NDA6NTguODMwWiIsInJlZ2lzdHJhdGlvbl9kZXRhaWxzIjp7ImVtYWlsIjoicHJlc2lkZW50QHdoaXRlaG91c2UuZ292IiwibWVtYmVyIjoiVHJ1ZSIsInBob25lIjoiKzQ0NzU2NDkxMTA3OSIsInBvc2l0aW9uIjoiIiwic2VydmljZXMiOlsiU3VnYXIgQ29hdGluZyJdLCJuYW1lIjoiSlcgQnVzaCIsInNjcmVlbnMiOjMsImFkZHJlc3MiOiI5M2EgU291dGhnYXRlIFJvYWQiLCJzaXRlcyI6MSwidGVycml0b3JpZXMiOiIiLCJleGhpYml0b3IiOiJXYWxtYXJ0IiwidG1zX21ha2VyIjoiIn0sImlhdCI6MTQ0MjU3MTE4M30.-WXUoCSYtoI1yMb1JondnQraYlkk6qGdR-xe0js6M5w', 'csrf_token': 'b1a492b79dcba4bfa15629b8727979e11d160de5'}>
```
versus 
```python
<SecureCookieSession {'csrf_token': '11954ab4d7414dc3eedd75b5b30ac59549f517f5'}>
```
the _id field is not present at all, and it's definitely not something I add in my code

**Comment by maxcountryman** [comment]
Still would be helpful to have a running example to work with. I can't reproduce your results unfortunately.

**Comment by miguelgrinberg** [comment]
@maxcountryman I think this is a similar problem to the one I addressed back in 0.2.10.

The way you have the strong session protected implemented causes Flask-Login to declare the session invalid everytime a client that is not logged in sends a request. This is because the session has no `_id`, so the conditional [here](https://github.com/maxcountryman/flask-login/blob/51defb5c3ecf498ec5040c80976f32e782cfc343/flask_login.py#L366) is true.

As a result of declaring the session invalid, Flask-Login clears it, but not only it clears its own data from the session, it wipes it out completely. This creates a conflict with Flask-WTF, which stores the form's CSRF token in the session. So essentially with the current version it is impossible to submit a Flask-WTF form if the user is not logged in.

Maybe Flask-Login should only clear its own variables from the session and leave the remaining data alone?

**Comment by shipperizer** [comment]
@miguelgrinberg is totally right, yesterday night I was checking the example on his ticket, totally the same....if you pick the code on that "issue ticket" you will have a way to reproduce the problem

**Comment by maxcountryman** [comment]
@miguelgrinberg Ah I see what's going on now. Yes: previously I suggested Flask-Login use its own cookie. I think it's time we did that.

**Comment by miguelgrinberg** [comment]
@maxcountryman I don't see any problem with Flask-Login using the Flask `session`, it's just that session invalidation should be scoped to the Flask-Login data, not the whole session.

Moving Flask-Login to use its own cookie seems more work, for little or no gain. Why can't you just erase the four items you store in there? Looks like it is `'user_id'`, `'remember'`, `'_id'` and `'_fresh'`. Just get rid of these four when you need to invalidate. Happy to send a PR with this change if it saves any time.

**Comment by maxcountryman** [comment]
@miguelgrinberg the main reason to use a separate cookie is to prevent accidental clobbering. For example, Flask-Seasirf does this.

**Comment by miguelgrinberg** [comment]
@maxcountryman I'd like to suggest you apply the quick fix and make a release. It's not good to leave things broken for long.

While using a separate cookie provides more isolation, you'll have to provide your own encryption and tamper-prevention. There's also the problem that by not using the session you can't take advantage of custom server-side session handlers. Seems to me a change of that magnitude needs a lot of thought and a major release bump, not something you should do in a rush to address a broken release.

**Comment by maxcountryman** [comment]
@miguelgrinberg I'm fine with your solution in the interim. I'm on vacation until Monday so I probably won't be able to do a bugfix release until then. 

It would also be fine to use Flask-Seasurf as a guide: it does provide its own security for its cookie and I feel it's generally a better way to do this sort of thing. 

Anyway I'll check in again on Monday.

**Comment by drewbutcher** [comment]
I'm having the same problem, Thank you Miguel for all the help!!

**Comment by shipperizer** [comment]
thanks guys, last question, are we gonna get a new release soon?
