### ISSUE TITLE
is_authenticated property breaking flask security and other extensions

### ISSUE THREAD

**Issue by gtalarico** [maxcountryman/flask-login#233]
Kept getting the error below.
I had to roll back to 0.2.9 to keep other modules from breaking

if current_user.is_authenticated():
TypeError: 'bool' object is not callable

https://github.com/mattupstate/flask-security/issues/416
https://github.com/GovLab/noi2/issues/7
https://github.com/miguelgrinberg/flasky/issues/74

**Comment by maxcountryman** [comment]
https://github.com/maxcountryman/flask-login/blob/master/CHANGES
