### ISSUE TITLE
User's logged out after server restart

### ISSUE THREAD

**Issue by PavSidhu** [maxcountryman/flask-login#235]
I have Flask-login running on a website of mine. It works perfectly however I have an issue with the remember me button and remaining logged in after the server restarts. When I update the application, I have to restart the server to update the changes but the user gets logged out.

Is this a bug issue or just something which I cannot change? I don't want users who are using the website to be signed out when I update the server? Thanks.

**Comment by richgieg** [comment]
Is your application's SECRET_KEY regenerated on each launch?

**Comment by alanhamlett** [comment]
Thanks @richgieg, that must be the case. @PavSidhu make sure your `SECRET_KEY` is hard-coded and does not change when you restart the server.
