### ISSUE TITLE
Migrate from flask.session to a dedicated cookie

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/flask-login#238]
This has been on my mind for a while, especially as there have been multiple bugs related to incorrectly or partially purging Flask's `session` of our library's keys. While `session` may seem like a convenient place to store Flask-Login's state, it risks clobbering application data (what happens when the application has a `user_id` key, for instance; we have a conflict and data loss occurs). A much more robust solution is to use a separate cookie: this is how Flask-Seasurf has always worked. A downside to this approach is that libraries which facilitate server-side session objects are no longer viable. However, I see this as a feature: server-side cookies do not scale and are in my opinion not worth supporting--it isn't the kind of design we should be promoting.

This is a planned feature of `0.4.0`.

**Comment by davidism** [comment]
Alternatively, prefix all Flask-Login session keys with `flask_login.`, and then only delete keys that start with it.  That would avoid the clobbering unless a user was much more deliberate about naming their own keys.  I'd rather not see support for the session completely dropped.

**Comment by maxcountryman** [comment]
@davidism Unfortunately that still doesn't prevent accidental clobbering, although it does make it more unlikely. The more correct solution is what I've outlined above. Expect to see `flask.session` replaced by our own session-like object. (I think simply instantiating our own `flask.session` might be enough, which would mean the same tools that operate on that type would continue to work for us.)

**Comment by maxcountryman** [comment]
@davidism If there's a strong reason to keep using Flask's `session` instance directly, I'll certainly consider it. So far the best argument has been server-side sessions, which as I stated above I don't really feel is worth supporting.

**Comment by davidism** [comment]
I think using a separate instance of Flask's session interface sounds good.  If a user does want server side sessions, they just change `login_manager.session_interface` like they would with `app.session_interface`.

**Comment by davidism** [comment]
One argument for keeping everything in Flask's session is that the developer then knows that everything is stored there, rather than having to remember other cookies.  I don't think there's any expectation that everything lives in the session though, so it's a weak argument.

**Comment by p-vital** [comment]
It does not seem appropriate to me for a library (not even a framework at that) to make policy decisions for applications using it as to where session data should be stored.

Two scenarios come to mind:

1. As an application, I may not want to expose user ids or other user keys publicly. For example, user ids may be sequential where session keys are not.

2. As an application, I may want to forcibly expire specific sessions. Cookie session storage as far as I can tell does not support this use case - the only way to expire sessions is to expire all of them by e.g. changing the cookie name, or the application must keep server-side sessions shadowing cookie sessions.

**Comment by maxcountryman** [comment]
@p-vital I don't think you understand the thrust of this change: the machinery for storing flask-login data would be abstracted and by default would be placed into its own cookie. Applications would be free to use this abstraction to put the data wherever else they might like.

This change is important because it ensures that flask-login does not mangle application-level data. E.g. data stored in the session. It also makes it easier for flask-login to purge its own data without accidentally leaving behind stale bits.

I can think of no reason why providing an abstraction which would allow anyone to do whatever they please is not quantifiably better than what we have today--at the same time it fixes the previous issues we've run into.

**Comment by p-vital** [comment]
@maxcountryman if the changes proposed here do not remove functionality then I don't understand your opposition to #245. If anything, by merging #245 you gain test coverage for logging a user in in tests.

**Comment by maxcountryman** [comment]
@p-vital because we can't using `flask.session` anymore.

**Comment by alanhamlett** [comment]
So the requirements for moving to a separate cookie are:

* Use existing Flask configuration settings
* Reuse an instance of `Flask.session` because we don't want to implement all that logic again

The [docs on sessions](http://flask.pocoo.org/docs/0.11/api/#session-interface) don't seem very intuitive... is it absolutely necessary to use a separate session cookie? Is this just to prevent deleting non-Flask-Login related session keys when logging the user out? We could just have a boolean config that let's the user choose to clear the whole session or only Flask-Login related keys?

**Comment by maxcountryman** [comment]
I think we want to get away from using Flask's session object--there isn't really a benefit to it and it leads to complications. Ultimately Flask's session object is outside the scope of this library and so we risk any number of unintended consequences by not bringing that scope back into the library.

What I suggest is we implement an abstraction that allows the library consumer to decide what class sessions are built with. Such objects should be compatible with Flask's sessions (i.e. present the same API) and could simply default to `flask.sessions.SecureCookieSession` to begin with. Once that's done, we should bring the entire interface into the library and use our own implementation as the default.
