### ISSUE TITLE
current_user in jinja template is not a User instance

### ISSUE THREAD

**Issue by mohierf** [maxcountryman/flask-login#239]
I am trying to user `current_user` in a jinja template and I get this exception: 
```
TypeError: unbound method get_name() must be called with User instance as first argument (got nothing instead)
```

My template contains:
```
{% if current_user.is_authenticated %}
  Hi1 {{ current_user.name }}!
  Hi1 {{ current_user.get_name() }}!
{% endif %}
```

I am using a user class declared as:
```
class User(UserMixin):
...
    def get_name(self):
        return self.username
```

Note that whe, I am using a property, there is no problem but as soon as I am using a class function, the exception is raised ...

**Comment by davidism** [comment]
How are you loading the user?  You appear to have assigned the User class rather than an instance.

**Comment by maxcountryman** [comment]
The error should give you some clue:

> TypeError: unbound method

This means you're attempting to access a method on a class before the class has actually been created (presumably this is not what you want). You'll need to ensure that your class is instantiated before using `get_name`.

**Comment by mohierf** [comment]
I am locate din a view decorated with @login_required ... and the Flask-Login doc says that : *You can then access the logged-in user with the current_user proxy, which is available in every template:* ... so I supposed that the `current_user` is an intantiated user. Or not ?

If not this means that I must create a User object on my own when the login process is successfull and then assign it to the current_user ?

**Comment by mohierf** [comment]
I found the solution to my problem ... the object returned from my `token_loader` or `user_loader` methods was not an object but a class !

I saw there is a PR for adding a simple example in the documentation and I think that it should be merged to help new users :-)

Moreover, a richer example will not be too much ...

**Comment by acalvino4** [comment]
It seems the documentation is still in the same state as what @mohierf quoted back in 2015, leading me to the same confusion that he listed. I think some updates would in order addressing the questions  he listed in this comment: https://github.com/maxcountryman/flask-login/issues/239#issuecomment-145211750

@mohierf you identified the cause of the problem as being the implementation of your load_user method - what was your solution? The documentation shows `return User.get(user_id)` as the implementation of `load_user()`, but db.model doesn't have a .get method in SQLAlchemy, so I tried `User.query.get(user_id)` which apparently returns a class like you were experiencing.
