### ISSUE TITLE
Add option to disable sessions

### ISSUE THREAD

**Issue by joshfriend** [maxcountryman/flask-login#240]
Because I use token auth instead of the session for my REST API, I was running into a recursive loop with Flask-Principal as described here: mattupstate/flask-principal#22

Being able to use `login_user` without setting a session cookie would help get rid of the chained signal catching I have to do.

**Comment by maxcountryman** [comment]
Thanks for pointing this out. I think it was a design mistake that Flask-Login ever used the session object in the first place. I'm in favor of replacing the cookie with a custom cookie (see #238) and making the cookie configurable and optional would go hand in hand with that.

**Comment by joshfriend** [comment]
Sounds good. I'll just close this and keep an eye on #238 instead.

**Comment by maxcountryman** [comment]
Sure. I'm open to contributions as well. I'm a little busy at the moment so I don't know when I'll actually be able to get to this.
