### ISSUE TITLE
Exempt OPTIONS calls from login_required

### ISSUE THREAD

**Issue by joshfriend** [maxcountryman/flask-login#243]
When you define an endpoint using a `MethodView` or Flask-RESTful `Resource` class, you can apply decorators to all HTTP methods in the class. If the resource class overrides the `options` method, Flask-Login will require the user to be logged in to make an OPTIONS call.

Example:

```python
class Foo(Resource):
    decorators = [
        login_required,
    ]

    def options(self):
        # Do special things here...
        pass

    def get(self):
        return 'ok', 200
```

The W3 standards doc for CORS requests specifically states that OPTIONS calls should ["Exclude user credentials"](http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0), thus a 401 response would never be appropriate.

Flask-HTTPAuth specifically [makes OPTIONS calls exempt from login checks](https://github.com/miguelgrinberg/Flask-HTTPAuth/blob/v2.7.0/flask_httpauth.py#L51-L55).

**Comment by maxcountryman** [comment]
Okay I say we explicitly whitelist OPTIONS.

**Comment by joshfriend** [comment]
I have a fix with tests almost ready

**Comment by maxcountryman** [comment]
3e1715ec456d2f3f4e15772aaee65e06ff32b39e makes this configurable by moving exempt methods into a module-level set.
