### ISSUE TITLE
Login required for all views

### ISSUE THREAD

**Issue by jabbas** [maxcountryman/flask-login#247]
I couldn't find this anywhere in the docs (or miss it somehow?)

Is there a possibility to make flask-login enabled for all views in the app and just use `@login_notrequired` for some (eg login page)?

The more blueprints/views you have the chances that you forgot to decorate each view are growing :)

**Comment by maxcountryman** [comment]
No. This is not possible.

**Comment by alanhamlett** [comment]
@jabbas you can use `flask.before_request` to check if the user is authenticated before every request.
