### ISSUE TITLE
Session protection triggering unnecessarily, causing "remember cookie" to be wrongfully cleared when in "strong" mode

### ISSUE THREAD

**Issue by richgieg** [maxcountryman/flask-login#248]
I've been working through Miguel Grinberg's "Flask Web Development" book, which makes use of Flask-Login. I'm using version v0.3.2. The book's example project sets the session protection to "strong" mode and utilizes the "remember me" feature. I noticed that my login session is only remembered on the very first request upon returning to the site after closing my browser then re-opening it. On the second request, my login session is wiped out. I dug through the code to help me see what was going on. Here's what I came up with:

1. User opens browser, navigates to site
2. User logs in, with "remember me" enabled
3. session['_id'] is initialized with call to _create_identifier()
4. The "remember cookie" is created
5. User closes browser, while still logged in
6. User opens browser, navigates to site, expecting their session to still be active
7. User info is loaded from the "remember cookie" on the first request (gives the user the impression they're still logged in and everything is fine)
8. On the very next request, however, session protection is wrongfully triggered due to there no longer being a session['_id'] value (therefore it doesn't match the per-request-generated challenge value)
9. Since session protection is triggered while the mode is "strong", all of the SESSION_KEYS are popped from the session and the "remember cookie" is cleared
10. The user is now logged out

The issue is not quite as bad in "basic" mode. Session protection is still wrongfully triggered, on all requests after the first one, due to the missing session['_id'] value, but the only side effect is that session['_fresh'] is set to False (which is the value it already would have anyway as a result of a previous call to _load_from_cookie()). The user still remains logged in after closing and re-opening the browser in "basic" mode.

I experimented with the code and came up with an idea that seemed to accomplish my goal. I altered _set_cookie() and _load_from_cookie() in such a way that the "remember cookie" stores session['_id'] along with session['user_id']. With this method in place, session protection is not wrongfully triggered (see step 8 above), since session['_id'] was loaded in from the "remember cookie." I'm not sure if this is the best long-term solution or if it's a potential security issue. It seems that if the cookie ended up in the wrong hands, session protection would kick in and drop the session when it compares the _id value from the cookie to the newly generated one which uses the attacker's IP and user agent string.

**Comment by richgieg** [comment]
I forked Flask-Login and created a few commits for demonstration purposes:

**Add additional session protection "remember me" tests**
These tests demonstrate how the second request (see step 8 above) causes session protection to trigger. At this commit, these two new tests will fail.
https://github.com/richgieg/flask-login/commit/0e240b99c99f7a367965ac283f234888c733edfd

**Add debug output to `_session_protection()`**
When the tests fail, there will be output showing the state of `sess` and `ident`.
https://github.com/richgieg/flask-login/commit/de5449399c8706f35247812f7b4a511aed4924aa

**Add comments to debug output statements**
Describe the failure situation in detail.
https://github.com/richgieg/flask-login/commit/7b26365147a68b1311650327686822f0cc387a3e

**Create a hack to get the new tests to pass**
I decided to go a simpler route in this demonstration than to do what I described in the last paragraph of my initial post. In `_load_user()`, if `has_cookie` is `True`, call `_create_identifier()` in order to initialize `session['_id']`. I don't feel that this method is very secure.
https://github.com/richgieg/flask-login/commit/f681852c708b8b320b4ab25e6b52e142cca063fd

**Comment by maxcountryman** [comment]
I'm not convinced this isn't the intended behavior. As has been discussed before, remember me and strong session protection aren't really meant to work together.

**Comment by maxcountryman** [comment]
Please see #156 for further discussion on this. Closing as remember me is not compatible with strong session protection.

**Comment by richgieg** [comment]
Even with "basic" session protection I've noticed an issue when the remember cookie is present, although it's a different one. It causes the session_protected signal to fire on every subsequent request (after the first) after the user re-opens their browser when a remember cookie is present. Is that the intended behavior?

Is it safe to say that "remember me" functionality should only be used in session protection is off?

**Comment by maxcountryman** [comment]
The idea of preserving a session and protecting a session are necessarily diametrically opposed as implemented, in my opinion. Basic protection is supposed to be passive, so perhaps that's a bug.

**Comment by DmonteiroD** [comment]
> As has been discussed before, remember me and strong session protection aren't really meant to work together.

@maxcountryman this should be added to docs, don't you think?
