### ISSUE TITLE
Tutorial on how to combine authentication between Flask-JWT and Flask-Login

### ISSUE THREAD

**Issue by rlam3** [maxcountryman/flask-login#253]
Tutorial on how to combine authentication between Flask-JWT and Flask-Login? 

I'd like to know how I can integrate flask-jwt username and password authentication to flask-login.

Or should these authentications be kept separate?

**Comment by davidism** [comment]
You just call `login_user` like normal.  Flask-Login isn't concerned with *how* you authenticate the user, so using Flask-JWT is just as valid as any other method.

**Comment by rlam3** [comment]
@davidism what do you mean just call login_user? i still need to be able to pass the token back to the user correct? Could you please clarify?

**Comment by maxcountryman** [comment]
@rlam3 what do you mean by "pass the token back to the user"?

**Comment by rlam3** [comment]
@markhildreth for jwt tokens to work I send it from server side to the client so they can use it whenever they the next request. I'm not sure how exactly by just doing login_user would work with jwt tokens as login_user just creates a session for the user but doesnt utilize flask-jwt

**Comment by alanhamlett** [comment]
Flask-JWT and Flask-Login are two different ways to handle user authentication. They can be used separately or together, but not on the same Flask view.
