### ISSUE TITLE
Session expiring unexpectedly

### ISSUE THREAD

**Issue by divs1210** [maxcountryman/flask-login#260]
Hi!

I have 2 different `User` models, both kinds of users need to be able to login, and I need to be able to manage their sessions. To achieve this, I have defined a custom login manager as follows:

```python
class SmarterLoginManager(LoginManager):
    def login_required(self, func):
        login_required_func = login_required(func)

        @wraps(func)
        def decorated_view(*args, **kwargs):
            current_app.login_manager = self
            return login_required_func(*args, **kwargs)

        return decorated_view

    def login_user(self, *args):
        current_app.login_manager = self
        return orig_login_user(*args)

    def logout_user(self):
        current_app.login_manager = self
        return orig_logout_user()
```

I always set the login manager for the current session at `login` time.
For some reason, the session expires while I'm logged in and doing something, and receive a `403`.
Can someone help me figure out why this is happening?

**Comment by cliedeman** [comment]
Hi there

Can you create a minimal flask app that displays the problem?

Ciaran

**Comment by alanhamlett** [comment]
@divs1210 you could do this in your `login_manager.user_loader` without needing a custom login manager class. Just return the correct user model from your user loader function depending on the type of id passed to your user loader function. Have your get_id method on both your user models prepend their id's with a custom string so you can distinguish between the two types.

**Comment by divs1210** [comment]
Sorry for the late reply, guys.

@alanhamlett thanks for the suggestion, but I'm using this custom manager in place of a `role` system to manage access to different parts of the app.

@cliedeman working on it.

**Comment by divs1210** [comment]
Hey @alanhamlett  thanks a lot for that, I thought about it a bit and could get authorization working with it.
