### ISSUE TITLE
logout_user() does not work with POST request

### ISSUE THREAD

**Issue by ggundersen** [maxcountryman/flask-login#262]
I have tried to use logout_user() with a POST request, but it does not work. Would it be possible to support this?

**Comment by alanhamlett** [comment]
It's just a normal Flask view, so if you're following the example in the docs just specify the request method for Flask:

`@app.route("/logout", methods=['POST'])`

**Comment by ggundersen** [comment]
Weird. I thought I had both the route and form set correctly, but my Selenium test kept failing. Now it's passing, so I must have done something wrong the first time. Sorry for the silly issue.
