### ISSUE TITLE
Authentication curl command with flask-login

### ISSUE THREAD

**Issue by ueg1990** [maxcountryman/flask-login#266]
Hello, I could not find an IRC channel to ask for help so I thought I could ask here. Apologies in advance if this is not ok.

I am using flask-login in my flask app. i want to use one of the api routes that i have defined via a curl command (this curl will be used in a cron job). and i wanted to ask if there is a way to authenticate this curl command via flask-login? I would really appreciate your help in this. The route that i have defined can be found here:

https://github.com/ueg1990/towatchlist/blob/master/app/main/views.py#L55

**Comment by alanhamlett** [comment]
Add a `@login_required

**Comment by alanhamlett** [comment]
Add a `@login_required` decorator to that view, then add a request loader handler to your Flask Login `login_manager` to authenticate the curl request using an api key:
https://flask-login.readthedocs.org/en/latest/#custom-login-using-request-loader

**Comment by ueg1990** [comment]
i am considering that too after reading the documentation again. i just do not get why do i need a login_required decorator? i want to use a curl command and i will pass the user credentials, won't the request loader handler be sufficient?

**Comment by alanhamlett** [comment]
Without the login required decorator, you have to check if the user is authenticated inside your view like:

```
if not app.current_user.is_authenticated:
    abort(401)
```

It's just easier to decorate your view with `@login_required`.

**Comment by ueg1990** [comment]
oh you are right! i did not consider that. just to verify, is_authenticated means that user exists in the database right?

**Comment by alanhamlett** [comment]
If you returned a user from a database in your `user_loader` or `request_loader`. `app.current_user` is just the user returned from your `user_loader`. If you return `None` from the `user_loader` then `app.current_user` is an instance of the `AnonymousUser` class, which should return `False` from it's `is_authenticated` property.

**Comment by ueg1990** [comment]
thanks for the clarification and for your help...i really appreciate it :smile:

**Comment by alanhamlett** [comment]
Anytime, let's close this issue if it's resolved.
