### ISSUE TITLE
AnonymousUserMixin not using properties, breaks all current code checks.

### ISSUE THREAD

**Issue by iaz3** [maxcountryman/flask-login#268]
The 3.0 change  
> BREAKING: The `is_authenticated`, `is_active`, and `is_anonymous` members of
  the user class are now properties, not methods. Applications should update
  their user classes accordingly.

Was not done to the AnonymousUserMixin, causing anything using the proper code check to break, if a user is not logged in.

The simple fix would be to add the property decorator to the methods.

Issue #261 is likely caused by this.

**Comment by maxcountryman** [comment]
I'll do a release soon, please be patient.

**Comment by iaz3** [comment]
No no it's already fixed, somehow it seems my copy, despite being the newest, didnt have the correct properties in the mixin. uninstalled and reinstalled to fix. Dont know how that happened, though.
