### ISSUE TITLE
Can I use it with multiple APP

### ISSUE THREAD

**Issue by ench4nt3r** [maxcountryman/flask-login#274]
Like below:

    from flask import Flask
    from flask_login import LoginManager, login_required
    from werkzeug.wsgi import DispatcherMiddleware
    from werkzeug.serving import run_simple
    
    app1 = Flask(__name__ + '1')
    app2 = Flask(__name__ + '2')
    
    login = LoginManager(app1)
    login.init_app(app2)
    
    
    @app1.route('/app1')
    @login_required
    def app1_fun():
        pass
    
    
    @app2.route('/')
    @login_required
    def app2_fun():
        pass
    
    
    app = DispatcherMiddleware(app1, {
        '/app2':     app2
    })
    
    if __name__ == '__main__':
        run_simple('localhost', 5000, app,
                   use_reloader=True, use_debugger=True, use_evalex=True)

The above code is the normal run.Is this it will go wrong? thank!

**Comment by GedRap** [comment]
A bit late to the party but it does work indeed, when mounting multiple applications using `DispatcherMiddleware`.
