### ISSUE TITLE
decorator for logout_user?

### ISSUE THREAD

**Issue by SkyLeach** [maxcountryman/flask-login#275]
I am developing an enterprise REST/web application and I was looking for an example of a decorator or closure wrap for logout_user but I don't see one mentioned in the docs?

According to the documenation logout_user removes the userid from the session.  The problem is that I don't use the user_id, I use the User object itself (serialization and deserialization are handled by __repr__ and __init__ via json).  I do this because authentication and authorization for my users is via LDAP to a windows PDC and user profile information is via the database.  Security requires group membership from LDAP while profile information is in the Database and thus my User object would be useless to come from the faster DB connection unless I replicated group information in the database.  I am prohibited from storing group membership outside of the LDAP authority but connecting to LDAP is very slow and I only want to do it once, at authentication, with authorization simply querying the stored inforamtion for the life of the session.

Thus I need to remove the 'user' entry from the session on logout_user independent of the user_id.  How should I go about this?

**Comment by alanhamlett** [comment]
Flask-Login doesn't deal with groups or permissions, it just says the user with `user_id` is logged in. Is your question how to use Flask Login or how to use Flask?

To log the current user out with Flask-Login, call `logout_user()` from your Flask app or Flask view.

To delete a key from Flask's session: `del session[key]`.

**Comment by SkyLeach** [comment]
My question is neither of those.  I wanted to know if there was a way to decorate logout_user so that if I want to perform operations that are specific to my application I know they will be performed no matter where or how logout_user is called by other developers.

**Comment by alanhamlett** [comment]
There is no way to do that with Flask-Login.

You can handle that many ways in your Flask application, the easiest of which is documenting your app and code reviewing other developers so they don't call logout_user without also doing your extra steps.
