### ISSUE TITLE
There should be a not_login_required for convenience

### ISSUE THREAD

**Issue by voanhcuoc** [maxcountryman/flask-login#276]
For instance, it is used to decorate **register** and **login** views, auto redirect to **index** view if the user is logged in.

**Comment by maxcountryman** [comment]
I'm not exactly sure what you're suggesting here but you can always write custom decorators for your app.

**Comment by alanhamlett** [comment]
@voanhcuoc here is a decorator I've used in the past:

```python
def login_not_allowed(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if app.current_user.is_authenticated:
            return redirect(url_for('views.index'))
        return f(*args, **kwargs)
    return decorated
```
