### ISSUE TITLE
cant work

### ISSUE THREAD

**Issue by zeratullich** [maxcountryman/flask-login#279]
version : 0.3.2
i define @login_manager.user_loader in models.py(models for db).
but it cant work !
the error is:
Exception: No user_loader has been installed for this LoginManager. Add one with the 'LoginManager.user_loader' decorator.

**Comment by zeratullich** [comment]
models.py:
#============================================================
from app import db, login_manager
from flask_login import UserMixin, AnonymousUserMixin


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False, unique=True)
    users = db.relationship('User', backref='role')

    @staticmethod
    def seed():
        db.session.add_all(map(lambda r: Role(name=r), ['Guests', 'Administrators']))
        db.session.commit()


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False, unique=True)
    email = db.Column(db.String(64), nullable=True)
    password = db.Column(db.String(64), nullable=True)
    # addr = db.Column(db.String(128))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    @staticmethod
    def on_created(target, value, oldvalue, initiator):
        target.role = Role.query.filter_by(name='Guests').first()


@login_manager.user_loader
def user_load(user_id):
    return User.query.get(int(user_id))

**Comment by alanhamlett** [comment]
Maybe you're using the current_user before setting the user_loader? What's the full traceback message?

**Comment by zeratullich** [comment]
Sorry, i have found the cause of the error....its about the environment of my python project!!! Thanks a lot !!

**Comment by adeolabadmus** [comment]
Hi @alanhamlett. Your suggestion just solved my issue. Thanks!

**Comment by greyli** [comment]
@alanhamlett In this case, what's the best place for `user_loader` callback? `models.py` or `views.py`?

**Comment by alanhamlett** [comment]
Mine's in `auth.py`.
