### ISSUE TITLE
Docs: Jinja template example broken because of missing parantheses

### ISSUE THREAD

**Issue by markasbach** [maxcountryman/flask-login#280]
In the current docs, a Jinja template example for Flask Login is given as:

    {% if current_user.is_authenticated %}
      Hi {{ current_user.name }}!
    {% endif %}

Unfortunately, this code is broken and will always render the "Hi" text as it is missing the parantheses for the method call. Instead of *calling* the method `is_authenticated()`, it evaluates the method name `is_authenticated`, which exists, so the condition of the if clause is always true.

This is what is intended:

    {% if current_user.is_authenticated() %}
      Hi {{ current_user.name }}!
    {% endif %}

Let's hope, nobody copied the example to production code without checking ;-)

**Comment by alanhamlett** [comment]
@markasbach what version of Flask-Login are you using? The old way was to use it as a method, now it's a property so the example is correct.

**Comment by markasbach** [comment]
Oops, my bad. I was totally sure to have installed a fresh flask-login using pip into that virtual-env where I tried out some code, but obviously it had been installed as a dependency by some other package (maybe flask-blogging) in an older version (namely 0.2.11).

So, confirmed: the current docs are correct for flask-logging 0.3.x, but not working for 0.2.11 (and vice versa). Sorry for the hassle.

Will be closing this issue.
