### ISSUE TITLE
Backdated datetime beyond Jan 01, 2011 is does not allow User to login - Flask-Login v0.3.2

### ISSUE THREAD

**Issue by VipulRJ** [maxcountryman/flask-login#287]
I installed Flask-Login v0.3.2 from https://pypi.python.org/pypi/Flask-Login
It is working correctly. But when i make datetime backdated beyond Jan 01, 2011 then it creates user-login and cookies but UI shows Internal Server Error.

Please replicate this issue and assist. If required correct me.

Regards,
Vipul Jain

----------------------------------------------------------------------------------------------------
Make sure these boxes are checked before submitting your issue--thank you!

- [Y ] Ensure you are using the latest PyPI release.
- [ Y] Read the [CHANGES](https://github.com/maxcountryman/flask-login/blob/master/CHANGES) document thoroughly.
- [ Y] Provide a clear and simple set of steps to reproduce your issue for others.

**Comment by alanhamlett** [comment]
Which datetime? How did you make datetime backdated beyond Jan 01, 2011. Need more info to reproduce this.

**Comment by davidism** [comment]
Possibly related to pallets/itsdangerous#46.

**Comment by alanhamlett** [comment]
@davidism you're correct, it was fixed with pallets/itsdangerous#46 so once new versions of itsdangerous and Flask are released it will be fixed in Flask-Login.

**Comment by VipulRJ** [comment]
My target board has debian linux with python2.7
I changed local time with command -
# timedatectl set-time "1980-01-01 11:13:54".

Now,  if user attempt to login then UI shows Internal Server Error. Even it shows same error incase of existing logged users.

This issue do not reproduce if datetime is ahead of Jan 1, 2011.

Regards, 
Vipul

**Comment by maxcountryman** [comment]
This is not a flask-login issue.

**Comment by VipulRJ** [comment]
What new changes i need to pull in to get this resolved?

**Comment by alanhamlett** [comment]
@VipulRJ we have to wait for pallets/itsdangerous#46 to make it into a Flask release then it will be fixed.
