### ISSUE TITLE
login_view not works for nonstandard port url

### ISSUE THREAD

**Issue by inming** [maxcountryman/flask-login#293]
When using nonstandard port, 8080 for example, the login_view will redirect to 80 port instead of 8080.

**Comment by alanhamlett** [comment]
If your Flask app is setup correctly, you should be able to use `Flask.redirect`:

```python
@login_manager.unauthorized_handler
def unauthorized_handler():
    return redirect(url_for('views.login', next=request.url))
```

**Comment by davidism** [comment]
I can't reproduce this issue.  Please provide a reproducible example.
