### ISSUE TITLE
current_user is set to False after long running sessions

### ISSUE THREAD

**Issue by HUSSTECH** [maxcountryman/flask-login#295]
Hi everyone,

I'm having an odd intermittent issue with I think specifically the request context, and the value of the `current_user` object. I'll try my best to state it all as clearly as possible

#### Pre-conditions:

1. having already successfully logged on earlier and a session cookie is set and present
2. some long-ish time has elapsed with the python server running still
3. return to the browser and try to navigate directly to a view that is protected with `@login_required`
4. `AttributeError` error appears

#### Environment details:

1. Flask 0.10.1
2. Flask-login 0.3.2
3. Flask development server
4. browser chrome

#### The problem
The error I get is an `AttributeErrorr: 'bool' object has no attribute 'is_authenticated'`. I think odd, because there should be no bool values anywhere near the user_object. So I traced back through the debug output and discovered that `current_user` was set to False. I have created a gist here: https://gist.github.com/HUSSTECH/92ffadf11c938f14847f47d8690d9fad

In the gist I have the full traceback, an expanded view of the code that raised the error in the decorator (line 7), and some outputs from the debug console from within the request context showing the False values. So the big mystery for me is how the user_object was ever set to False. I see nothing in the flask-login code that could have caused it to be False (the documents are very clear about returning `None` and not `False`!). Also in my code, I don't set it to False anywhere. It's doubly strange as the traceback does not even enter my app code, it goes from the request handler to the view handler, where it is intercepted by `@login_required` and then we get the error. I've confirmed none of my code is called, it never steps into the `user_loader` or anything like that.

#### The fix?
The two ways that I stop the problem are one of:

1. navigate to the login view on the browser, re-authenticate myself and I think that "cleans" things up and it all works again...or
2. delete the session cookie from my browser and refresh the exact same page that has the error and I'm redirected to the login view automatically, and again all is good.

In my mind, I'm drawn towards asking the questions, how does `current_user` get set to False? If I'm reading the code right, it's set from the `_request_ctx_stack.top.user`, so how is that False? and why does deleting the session stop the error?

Sorry for the obscure and long description, I've searched this repo and the internet with no luck on this, so hopefully it may be of use to others too. Big thanks for the library, and thanks for any light you may be able to shed here! :smile:

**Comment by HUSSTECH** [comment]
Ok I got it, with a fresh set of eyes I found the issue. Basically as my `user_loader` function attempted to reload the user, the token had expired. An expired token returns a `False` when it fails to validate the signature. So I just needed to refactor the `user_loader` function slightly so that the `False` was not returned directly, but instead `None` as is required.

Simple in the end, but hidden many layers in. I learned a lot about this library in the process as I was reading through the source over and over. So not all wasted time! :smiley:

**Comment by maxcountryman** [comment]
@HUSSTECH is there any way the documentation could have been improved in such a way this would have been easier for you from the start?

**Comment by HUSSTECH** [comment]
Hey @maxcountryman, hard to say. The error was certainly with my code and not the library. Upon reading the code, which is easy to follow, I was able to see it. There is a good line of docstring on the `login_manager.init_app()` method which mentions adding a context_processor. That line immediately reminded me that Flask runs the context processors for each request, so I followed that execution path in the code it went: `_user_context_processor() < _get_user() < current_app.login_manager._load_user() < loging_manager.reload_user() < @user_loader function`. That then pointed my investigation back into my own user_loader callback function and I found the error. 

You could add some more of those function docstrings onto the main documentation page. For me at least they were interesting and explained a bit more about how things work internally. The "API Documentation" section at the bottom of the page looks like the ideal place for that, and seems like you've already added some info in there. Just gotta expand it. 

Secondly, really the `user_loader` callback should only ever return `None` or a instance of the `User` object, nothing else. The docs do say it should return `None` and not raise an exception if the ID is invalid, but it could be worth explicitly saying that `None` and `User` instance are the ***only two valid return values***. That way I could have remembered when I edited my `user_loader` function to take a token rather than `user_id`, to not allow the token loading to return `False` at any point.
