### ISSUE TITLE
'LOGIN_DISABLED = True' raises an exception when used with  '@login_manager.request_loader'

### ISSUE THREAD

**Issue by TrilceAC** [maxcountryman/flask-login#296]
Hi,

I'm developing a Flask app which requires a certificate to authenticate the user. Using Flask-Login 0.3.2 I can check the user when Apache is used and properly configured. The certificate is available to the Flask app through some environment vars of the request. I can decorate a function to check them with '@login_manager.request_loader' and it works fine. So far so good, but during the development, the server fired by Flask when running the application does not handle those certificates. At this moment of the development, I don't want to check whether the user is logged in.

Looking for some info, I found a way to [globally disable login_required](http://www.pythondoc.com/flask-login/index.html#flask.ext.login.login_required) by using 'LOGIN_DISABLED':

>It can be convenient to globally turn off authentication when unit testing. To enable this, if the application configuration variable `LOGIN_DISABLED` is set to `True`, this decorator will be ignored.

This is just what I need, though unit testing is not my current scenario. But LOGIN_DISABLED is not working when used in combination with '@login_manager.request_loader' decorator. What happens instead is that the application raises an exception caused by LoginManager.reload_user() method, which expects a user_callback to be defined:
```
        if user is None:
            user_id = session.get('user_id')
            if user_id is None:
                ctx.user = self.anonymous_user()
            else:
                if self.user_callback is None:
                    raise Exception(
                        "No user_loader has been installed for this "
                        "LoginManager. Add one with the "
                        "'LoginManager.user_loader' decorator.")
                user = self.user_callback(user_id)
                if user is None:
                    ctx.user = self.anonymous_user()
                else:
                    ctx.user = user
```

### Workaround
To deal with this issue, I have just defined a fake user_loader only when LOGIN_DISABLED is set to some value that is evaluated to True. Actually, It doesn't have to return a User, or do anything. Just declaring it on the app makes the app.login_manager object happy when it calls to its self.reload_user() This is just a workaround, but not a proper solution (unless it becomes documented somewhere):
```
if app.config.get('LOGIN_DISABLED'):
    @login_manager.user_loader
    def load_fake_user(user_id):
        return None
```

### Solution?
Since (1) I don't want mess-up things, (2) I'm not really familiar with the code of Flask-Login and (3) I haven't thought about this thoroughly, I feel that I shouldn't edit the code, but a possible solution might be to modify the LoginManager.reload_user() method so that the other callbacks are also checked:

Instead of: 
```
                if self.user_callback is None:
                    raise Exception(
                        "No user_loader has been installed for this "
                        "LoginManager. Add one with the "
                        "'LoginManager.user_loader' decorator.")
                user = self.user_callback(user_id)
```
check whether any of the other callbacks (request, header...) are defined and fire the one defined. The exception should only be raised when no callback is defined.

Or maybe just check the value of  LoginManager._login_disabled before / in- reload_user()

If needed, I can provide a full stack of calls, but basically there is a context.update(func()) which fires the following chain calls of Flask-Login:
_user_context_processor 
_get_user
_load_user
reload_user

Cheers

**Comment by HUSSTECH** [comment]
Hello,

Are you using the key `'user_id'` in the session anywhere? If you don't intentionally set `'user_id'` in the session, then maybe clear any cookies on your browser for your app's url in case something old is hanging about. 

looking at the `reload_user()` function, the only way to end up with the "No user_loader..." exception is to have `reload_user` called with `user = None` and `user_id = something other than None`. Then because no user_callback is defined the exception is raised. 

With your workaround, because you do set a user_callback (via user_loader) this suppresses the exception from firing. But as that user_callback returns `None` itself, an anonymous_user is set later anyway and the function completes.

In your suggested solution, the code does check the other callbacks already but it does it in the `_load_user()` function. e.g. [https://github.com/maxcountryman/flask-login/blob/05b8f8602ee81f7d131607ab4757899883462ba6/flask_login/login_manager.py#L312](url)

**Comment by TrilceAC** [comment]
Hello HUSSTECH,

The base template checks whether the user is authenticated:
```
				{% if current_user.is_authenticated %}
					<p>Hi {{ current_user.cn }}!</p>
				{% endif %}
```
But as far as I am aware, I don't intentionally set `user_id` in the session.

It seems that you guessed right. I have cleared the cookies from localhost and I have commented the workaround and now it seems to work without the exception, as expected. Sorry for the novice oversight.

Thank you for pointing out the issue with the cookies,

**Comment by alanhamlett** [comment]
Out of curiosity, what was the Traceback message you were getting?

**Comment by TrilceAC** [comment]
I see what is happening. I'm testing and developing two different Flask applications: 
- The one that was failing is a native Flask application with Flask-Login and the request_loader.
- The other one is just a prove of concepts: a test to check whether [Flask-AppBuilder](http://flask-appbuilder.readthedocs.io/en/latest/) could help. Flask-AppBuilder also uses Flask-Login and right now it is configured to use login through `AUTH_DB`.

I run both apps from the same host, though they use different ports. I just wanted to check Flask-AppBuilder as a way to save a full development from scratch but both apps shared their host and many config params. Since both apps are being served from the same host and accessed through localhost, I didn't realize that both apps were sharing the same `session` cookie. Furthermore, I didn't changed the `SECRET_KEY`. Therefore both apps understood, could read and could write the same session cookie. 

Firstly, I have changed the `SECRET_KEY`of one of those apps: 
Once the `SECRET_KEY` is changed the cookie contents are not shared anymore between apps, but the cookie name `session` and its site `localhost` are. Now when any of both applications tries to read the `session` cookie, it only succeeds if the cookie has been signed by the application itself and not by the other one. Otherwise  the application replaces the cookie with an own one.

Secondly, I have set a different `SESSION_COOKIE_NAME` for each app. This actually has solved the problem: Cookies with different names are generated for each app.

Now it is clear to me that I have messed up two different sessions and that was causing the unexpected behaviour. (*ashamed*)

@alanhamlett this is the traceback of a failure, in case you are still interested on:
```
Traceback (most recent call last):
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask_login.py", line 789, in decorated_view
    return func(*args, **kwargs)
  File "~/devel/eiweb/app/views/tier0.py", line 46, in index
    return render_template("tier0/index.html", form=form)
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask/app.py", line 765, in update_template_context
    context.update(func())
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask_login.py", line 891, in _user_context_processor
    return dict(current_user=_get_user())
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask_login.py", line 858, in _get_user
    current_app.login_manager._load_user()
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask_login.py", line 389, in _load_user
    return self.reload_user()
  File "~/devel/eiweb/venv/lib/python2.6/site-packages/flask_login.py", line 348, in reload_user
    "No user_loader has been installed for this "
Exception: No user_loader has been installed for this LoginManager. Add one with the 'LoginManager.user_loader' decorator.
```
