### ISSUE TITLE
Can't use strong session_protection with permanent sessions

### ISSUE THREAD

**Issue by codermpl** [maxcountryman/flask-login#297]
Steps:
1. Set session.permanent = True
2. Set SESSION_PROTECTION='strong'

Flask-login treats this as if the session_protection were basic and marks the session as _fresh = False, even though I set session_protection to 'strong'.  That means I have to manually check whether the session is fresh, rather than relying on the session_protection to automatically delete the session.  

I am not using Remember Me tokens, but I'm using permanent sessions for my session cookie.

**Comment by ioparaskev** [comment]
Same here, I only use permanent session without the flask-login "remember me" stuff. Setting SESSION_PROTECTION to 'strong' is the same as if setting it to 'basic'. Permanent and non-permanent sessions are marked as non-fresh when I change the user agent
