### ISSUE TITLE
Include documentation for preserving URL hashes for login redirects

### ISSUE THREAD

**Issue by mattboehm** [maxcountryman/flask-login#299]
When a user tries to visit `http://www.mysite.com/page#hash`, they are redirected to `http://www.mysite.com/login?next=page#hash`. After logging in, they are redirected to `http://www.mysite.com/page`. Note that this does not include the hash that they typed.

This happens because the url hash is never sent to the server, so the value of `next` is just `page`. The browser is preserving the original URL hash and sticking it on the login url, but additional code is required to send this hash to the server.

If the next url is being stored in the login form in a hidden input named `next`, the hash can be added to this attribute with the following javascript code on the login page:

```
document.querySelector("[name=next]").value += window.location.hash;
```

Since users are creating their own custom login forms, I wouldn't expect this code to be added anywhere in flask-login (although making a jinja2 helper that included it would be possible.) However, perhaps it'd be nice if this information were included in the docs somewhere?

I don't mind creating the PR, but wanted to run this by folks to see what they think of the idea and if they have any suggestions on how to word this.

**Comment by alanhamlett** [comment]
Code examples for preserving fragments is outside the scope of Flask-Login, but we could add a note near the redirect docs like:

`Because the fragment/hash part of urls is not sent to the server, the next url does not preserve fragments/hashes when redirecting. Use JavaScript to preserve window.location.hash.`
