### ISSUE TITLE
the class User  have no function get().

### ISSUE THREAD

**Issue by guzhenping** [maxcountryman/flask-login#301]
Hello：

l find the class User extends flask_login.UserMixin.

but it  have  no function get()，l only see get_id().

So, am l wrong?

**Comment by davidism** [comment]
The only reference I could find to `User.get()` was in the [`user_loader` example](http://flask-login.readthedocs.io/en/latest/#how-it-works).  That's just a hypothetical function you would use to fetch a user instance, it's not related to the methods that Flask-Login requires.  For example, it might be `User.query.get(id)` with Flask-SQLAlchemy.

**Comment by alanhamlett** [comment]
@guzhenping you must define a `get` method in your user model. Inheriting from `UserMixin` is just to implement the methods that Flask-Login needs. For a `get` method you could also inherit from a `SQLAlchemy` model.
