### ISSUE TITLE
Incompatible with multiple apps with different loader

### ISSUE THREAD

**Issue by timothyqiu** [maxcountryman/flask-login#304]
`LoginManager` stores configs like `user_loader` in the manager object itself instead of `app.extensions['NAME']`.

This means that using the same `LoginManager` instance with multiple apps (each app running `login_manager.init_app(app)` won't work as expected: You can't use different `user_loader` for different apps.

Extensions like Flask-SQLAlchemy and Flask-Mail store their state in `app.extensions['NAME']`, so multiple apps can be configured separately.

**Comment by davidism** [comment]
Extensions are meant to work this way, the behavior is the same (barring app.config differences) across apps.  If you need different loaders for different apps, use different instances of the extension.  Flask-SQLAlchemy is no different, you're misunderstanding what the state object is in those.

**Comment by timothyqiu** [comment]
[The document](http://flask.pocoo.org/docs/0.11/extensiondev/) does not limit multiple application support to supporting only `app.config` differences.

How to load user from the session is application specific logic. Bounding application logic to the extension instance, IMHO, is not good multiple app support. Anyway...
