### ISSUE TITLE
Where does user id come from when user_loader decorates the method which load the user?

### ISSUE THREAD

**Issue by penguin-penpen** [maxcountryman/flask-login#306]
Make sure these boxes are checked before submitting your issue--thank you!

- [x] Ensure you are using the latest PyPI release.
- [x] Read the [CHANGES](https://github.com/maxcountryman/flask-login/blob/master/CHANGES) document thoroughly.
- [x] Provide a clear and simple set of steps to reproduce your issue for others.

I'm starting to use `flask-login` recently. I followed the `README` file to create a demo and it goes well.

When I'm trying to use a mysql database instead of the mock, I'm confused how does the `login_manager.user_loader` get the user `id`.

My `User` table is structured like this:
```
+----------+--------------+------+-----+---------+----------------+
| Field    | Type         | Null | Key | Default | Extra          |
+----------+--------------+------+-----+---------+----------------+
| id       | int(11)      | NO   | PRI | NULL    | auto_increment |
| name     | varchar(64)  | YES  | UNI | NULL    |                |
| phone    | int(11)      | YES  | UNI | NULL    |                |
| voice_id | varchar(100) | YES  | UNI | NULL    |                |
+----------+--------------+------+-----+---------+----------------+
```

But the id passed to my load function by the `user_loader` decorator is always `foo@bar.tld` which appears in the demo. 

Is the `id` stored in the `session`? How to remove the one that has logged in?

**views.py**
```
@login_manager.user_loader
def user_loader(id):
    return User.query.get(int(id))
```

**models.py**
```
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    phone = db.Column(db.Integer, unique=True)
    voice_id = db.Column(db.String(100), unique=True)

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return unicode(self.id)
```

**Comment by alanhamlett** [comment]
To logout a user, call `flask_login.logout_user`. Currently the logged in user's id is stored in the Flask Session, but you should use Flask-Login instead of interacting with the user_id from the session directly.

I'm not sure what you mean by the id always set to `foo@bar.tld`. The user gets logged in and the user_id set in the Flask Session after you call `flask_login.login_user`.

**Comment by penguin-penpen** [comment]
Sorry that I'm not familiar with how Flask deal with sessions. Where does it store its session data? Why relaunch the server doesn't clear the user logging data?

I tried to check `session` in Python console when the server is running, but it alerts that the object is not defined?

**Comment by alanhamlett** [comment]
Flask sessions are stored in browser cookies. It's `from flask import session` but you shouldn't need to use it for auth because Flask-Login abstracts everything you need.

**Comment by wormholesepiol** [comment]
I have the one million dollar question. Why every single example about this is about sqlalchemy? If even the docs say that then people is free to use whatever, why still every single post all around the Internet is about sqlalchemy? Thanks to this, I'm stuck right now, if I choose to use orm, I'm just quitting to think. If somebody know how I can do this with db instructions it would be helpful...
