### ISSUE TITLE
Current_user is not synchronize with users logged in in session while not using object inherited from Mixin?

### ISSUE THREAD

**Issue by penguin-penpen** [maxcountryman/flask-login#307]
Make sure these boxes are checked before submitting your issue--thank you!

- [x] Ensure you are using the latest PyPI release.
- [x] Read the [CHANGES](https://github.com/maxcountryman/flask-login/blob/master/CHANGES) document thoroughly.
- [ ] Provide a clear and simple set of steps to reproduce your issue for others.

I haven't look deep into the source of flask-login so I'm not sure whether this is a bug.

In other issues I find that flask-login allows developers to use user class inherited from classes other than `Mixin`, for example, `sqlalchemy`.

However, I noticed that `current_user.is_authenticated` is still `False`  after `flask_login.login_user(user)` is executed.

My User model is:
```
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    phone = db.Column(db.String(12), unique=True)
    password = db.Column(db.String(20))
    voice_id = db.Column(db.String(100), unique=True)

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return unicode(self.id)
```

**Comment by alanhamlett** [comment]
There must be something else going on here, the tests prove this is impossible. Check that the user object you're passing to `login_user` returns `True` from `user.is_authenticated`.

Also, your user model should have `is_authenticated` as a property not a method, but just use the `UserMixin` so you don't even need to worry about them:

```python
class User(UserMixin, db.Model):
    ...
    def get_id(self):
        return unicode(self.id)
```
