### ISSUE TITLE
Unauthorized handler doesn't get the 'request' variable.

### ISSUE THREAD

**Issue by Serubin** [maxcountryman/flask-login#308]
When using a custom Unauthorized handler the request variable is never past into the context.

This is on python2 with all modules (flask and flask-login included) up to date.

**Comment by alanhamlett** [comment]
That's as intended:
https://flask-login.readthedocs.io/en/latest/#customizing-the-login-process

If you need the `request` variable you can always get it with `from flask import request` at the top of the file containing your custom unauthorized handler.
