### ISSUE TITLE
Circular dependency in python setup.py build

### ISSUE THREAD

**Issue by romeojulietthotel** [maxcountryman/flask-login#309]
Make sure these boxes are checked before submitting your issue--thank you!

- [x ] Ensure you are using the latest PyPI release.
- [ x] Read the [CHANGES](https://github.com/maxcountryman/flask-login/blob/master/CHANGES) document thoroughly.
- [ x] Provide a clear and simple set of steps to reproduce your issue for others.

Running python3.5.2 

```
git clone https://github.com/maxcountryman/flask-login
cd flask-login
python setup.py build

```

Output:

```
running build
running build_py
file flask_login.py (for module flask_login) not found
file flask_login.py (for module flask_login) not found

```

I see flask_login.py in an install so this seems like a circular dependency that can only be met if you first install flask-login.

**Comment by alanhamlett** [comment]
Try `python setup.py install`.

**Comment by romeojulietthotel** [comment]
@alanhamlett,
What is your prediction or have you tried this already your self? If that's the case what was the outcome for you?

**Comment by alanhamlett** [comment]
It installed successfully for me using the install command. You should also probably use a virtual environment:

```
virtualenv venv
. venv/bin/activate
python setup.py install
```
