### ISSUE TITLE
Backwards compatible imports (_create_identifier)

### ISSUE THREAD

**Issue by jirikuncar** [maxcountryman/flask-login#314]
Can we keep the global import namespace compatible with 0.3.x version for `utils` introduced in 088ac3cf5e0597d59224fcfb0536bea031a9ae17 ?

**`__init__.py`**
```python

from utils import _create_identifier, ...

__all__ = ('_create_identifier', ...)
```

Thanks!

--
Make sure these boxes are checked before submitting your issue--thank you!

- [x] Ensure you are using the latest PyPI release.
- [x] Read the [CHANGES](https://github.com/maxcountryman/flask-login/blob/master/CHANGES) document thoroughly.
- [x] Provide a clear and simple set of steps to reproduce your issue for others.

**Comment by alanhamlett** [comment]
That's a private function, it only happened to be in the package-level namespace because everything was in one single file before. Why not just do `from flask_login.utils import _create_identifier` if you need to use private functions?

**Comment by jirikuncar** [comment]
Unfortunately, we do. Yes, we can bump the version, but it's suboptimal as we try to be compatible with as lower version as possible in case somebody needs to pin his/her requirements.

**Comment by alanhamlett** [comment]
This happens to us all the time too, namespaces change in packages we depend on. Even if we add `_create_identifier` to the global namespace, there will still be incompatible versions with your library since it's already been released this way. The way we usually handle namespace changes is by gracefully handling an import error and trying the alternate namespace:

```python
try:
    from flask_login.utils import _create_identifier
except ImportError:
    from flask_login import _create_identifier
```

**Comment by jirikuncar** [comment]
I would rather say `Flask-Login>=0.3.0,!0.4.0`. It was more for the future. Right now we can move this import for `_compat.py` but it seems ugly in long term. I understand the need for refactoring, but we should try to be as compatible as possible (even with "internal" functions).

**Comment by alanhamlett** [comment]
Yep, thanks for understanding. ❤️

**Comment by jirikuncar** [comment]
@alanhamlett I would still like to get this fixed in 0.4.1 if possible.

**Comment by maxcountryman** [comment]
You shouldn't be using functions that are intended to be private to the library. That's what the leading underscore is meant to indicate. We don't aim to support or encourage this.

**Comment by jirikuncar** [comment]
@maxcountryman I am afraid that this function is too important since the [session id validation](https://github.com/maxcountryman/flask-login/blob/05b8f8602ee81f7d131607ab4757899883462ba6/flask_login/login_manager.py#L321) is based on it. We have similar code in our package which handles OAuth authentication and tries to make it work nicely with Flask-Login. It was a bit unfortunate design decision that this function is not available on LoginManager, hence reachable for other libraries.

**Comment by jirikuncar** [comment]
There is a rough idea:

```python
class LoginManager(object):
    def __init__(...):
        ...
        self.session_identifier_generator = _create_identifier

    def init_app(self, app, ...):
        ...
        app.extension['login(-manager)'] = self

    def _session_protection(self):
        ...
        ident = self.session_identifier_generator()
```

**Comment by alanhamlett** [comment]
For the use cases Flask-Login supports, this private method is never needed. Even Flask itself has the try/except pattern for imports with two possible namespaces, so that's your best solution.

**Comment by davidism** [comment]
I'm really unclear why you can't change your imports.  Single underscore methods are, by convention, subject to change any time.  If you'd like to propose a change to the extension class, we welcome PRs for discussion.

**Comment by jirikuncar** [comment]
Ok. I will say it different words. Can we make the `_create_identifier` publicly available so we don't need to be worried on future change? See my previous https://github.com/maxcountryman/flask-login/issues/314#issuecomment-258172984

**Comment by bschumacher** [comment]
Why don't you just add the function to your code if you are worried about it changing? There's nothing that it requires Flask-Login for, that isn't easily implementable.

    def _create_identifier():
       user_agent = request.headers.get('User-Agent')
        if user_agent is not None:
            user_agent = user_agent.encode('utf-8')
        base = '{0}|{1}'.format(_get_remote_addr(), user_agent)
        if str is bytes:
            base = text_type(base, 'utf-8', errors='replace')  # pragma: no cover
        h = sha512()
        h.update(base.encode('utf8'))
        return h.hexdigest()

**Comment by jirikuncar** [comment]
Because this function must be the same that is used by Flask-Login.

**Comment by bschumacher** [comment]
It sounds like you made some serious design mistakes then, I would update your requirements.txt and setup requirements with specific Flask-Login version numbers if that is the case.

**Comment by jirikuncar** [comment]
@bschumacher can you comment on https://github.com/maxcountryman/flask-login/issues/314#issuecomment-258172984 ? Forget about the imports, I would like to make sure that I can reliably generate session id used by Flask-Login in my code. Can we please move the discussion there?

**Comment by alanhamlett** [comment]
Is your code open-source? If we knew your use case we could make a better decision if this is something we want Flask-Login to handle or not.

**Comment by bschumacher** [comment]
@jirikuncar I have no idea why that would be any different than defining the function yourself.

All the function does is generate a hash from the User-Agent header and the remote address.

Like @alanhamlett suggested, seeing your use case would be the optimal approach.

**Comment by jirikuncar** [comment]
> I have no idea why that would be any different than defining the function yourself.

@bschumacher I have answered in https://github.com/maxcountryman/flask-login/issues/314#issuecomment-258176676

> All the function does is generate a hash from the User-Agent header and the remote address.

I know, but sometimes one might like to change it or extend it.

> Is your code open-source?

@alanhamlett Sure!

> ... seeing your use case would be the optimal approach.

I don't think it will help much but you can see the code in https://github.com/inveniosoftware/invenio-oauthclient (there is some monkeypatching in tests).

> ... we welcome PRs for discussion.

@davidism please check #316. The point here is that even though `_create_identifier` is "marked-as-private", it is heavily used around the package and it would be nice if, in some way, one can reliably get the function that generates `session['_id']`.
