### ISSUE TITLE
how to handle @login_required session expired in Ajax Request

### ISSUE THREAD

**Issue by erwinyusrizal** [maxcountryman/flask-login#318]
Hi I have an ajax request and in my route I use login_required decorator, but if I do the request and the login session is expired, my ajax callback returns html 

any idea how to handle login session expiration / timeout, so when it's expired I can do something
Thanks

**Comment by erwinyusrizal** [comment]
I got this working for now by doing this in my error handler

`@main.app_errorhandler(401)
def unauthorized(err):
    if request.is_xhr:
        return jsonify({"success": False, "message": "You need to relogin to continue"})
    return redirect(url_for('auth.login', next=request.url))`

any other idea?

Thanks

**Comment by alanhamlett** [comment]
@erwinyusrizal that's exactly how I would do it.

**Comment by alanhamlett** [comment]
I would do the same thing, but use Flask-Login's [unauthorized_handler](https://flask-login.readthedocs.io/en/latest/#module-flask_login) with the exact same code as your `unauthorized` function above.
