### ISSUE TITLE
how to implement remember me option

### ISSUE THREAD

**Issue by piyushgohel** [maxcountryman/flask-login#319]
Hello,

I am using flask-login in my app. I have one problem like remember me option not work  in my app.I have used login_user(user,remember=True) but It is not work.

**Comment by alanhamlett** [comment]
@piyushgohel it's working for me. Can you provide more details on how it doesn't work?

**Comment by piyushgohel** [comment]
Here Is My Login Method and  I have override login template.

@api_user_blueprint.route('/api/user/login',methods=['POST'])
def user_login():	
	request_data = request.json
	data = {}
	username = request_data['username']
	password = request_data['password']

	pw_hash = bcrypt.generate_password_hash(password)

	if Users.Users.query.filter_by(email=username).first():
		user = Users.Users.query.filter_by(email=username).first()
		check_pass = bcrypt.check_password_hash(user.password, password) # returns True
		if check_pass == True:
			if user.active:
				login_user(user,remember=True)
				for role in user.roles: 
					data['admin'] = 0
					if role.name == "Admin":
						data['admin'] = 1
				flash('You were successfully logged in')
				data['id'] = user.id
				data['email'] = user.email
			else:
				data['id'] = -1
				data['message'] = "Please Confirm Your Email."

		else:
			data['id'] = -1
			data['message'] = "Invalid Password !"
	else:
			data['id'] = -1
			data['message'] = "No such email found !"
	return jsonify(data)

**Comment by alanhamlett** [comment]
That looks fine, but can you describe how it's not working?

**Comment by piyushgohel** [comment]
When I login and by default i made remember password true for testing Purpose and then logout. In Login screen User name and password not fill and in browser's network tab, I found remember_token but that token remove when user logout.

**Comment by alanhamlett** [comment]
That's the intended behavior. The remember me cookie allows restoring the logged in user when the Flask Session has expired or the user closes their browser:
http://flask.pocoo.org/docs/0.11/api/#flask.session.permanent

I'll improve the description of Remember Me in the docs.

**Comment by piyushgohel** [comment]
Can you give me situation in that user accidentally getting logged out?

**Comment by alanhamlett** [comment]
When they close their browser, they would be logged out accidentally. "Remember Me" just keeps them logged in even after they close and re-open their browser.

**Comment by bcambel** [comment]
@alanhamlett we are having the issue as described here, so your last sentence is currently not correct http://stackoverflow.com/questions/39938199/flask-login-remember-me-not-working-if-login-managers-session-protection-is-se

**Comment by bcambel** [comment]
thanks @davidism
