### ISSUE TITLE
How to logout from a non-flask app?

### ISSUE THREAD

**Issue by charyorde** [maxcountryman/flask-login#320]
Since `flask_login.logout_user()` doesn't require the `user_id`, how do we identify the logout request?
For the sake of curiousity.

- [x ] Ensure you are using the latest PyPI release.
- [ x] Read the [CHANGES](https://github.com/maxcountryman/flask-login/blob/master/CHANGES) document thoroughly.
- [ x] Provide a clear and simple set of steps to reproduce your issue for others.

**Comment by neilsh** [comment]
It removes the `user_id` from the `session` cookie: https://github.com/maxcountryman/flask-login/blob/6b940803d58b308f3c13327724ce0e1d14557d23/flask_login/utils.py#L162

**Comment by charyorde** [comment]
Yeah. but for a non-flask app, can we add `user_id`? Probably make it optional?

**Comment by alanhamlett** [comment]
@charyorde Flask-Login doesn't support usage with non-Flask apps.
