### ISSUE TITLE
PyPI release outdated

### ISSUE THREAD

**Issue by mattgaviota** [maxcountryman/flask-login#339]
Make sure these boxes are checked before submitting your issue--thank you!

- [x] Ensure you are using the latest PyPI release.
- [x] Read the [CHANGES](https://github.com/maxcountryman/flask-login/blob/master/CHANGES) document thoroughly.
- [ ] Provide a clear and simple set of steps to reproduce your issue for others.

Hello, thanks for the great work. Can you update the version in PyPi ?, because it does not have USE_SESSION_FOR_NEXT for example, which is discussed and explained in the latest documentation.

Thanks in advance.

**Comment by alexandersoto** [comment]
I'd like to second this. I thought my code was broken and then realized that flask-login's documentation is ahead of its latest PyPI release. If a release isn't imminent, reverting the docs would also correct this issue.

**Comment by davidism** [comment]
Read The Docs defaults to the latest build. Click the menu at the bottom right of the window and select "stable" (or whatever version you're on).

**Comment by maxcountryman** [comment]
@alanhamlett @davidism should we author a release to PyPI?

**Comment by alanhamlett** [comment]
Yea, looks like the only thing needing to be added to changelog is the new `USE_SESSION_FOR_NEXT` config.

**Comment by alanhamlett** [comment]
I'd like to go through the open PRs first to see if any should be included in the release.

**Comment by Omeryl** [comment]
@alanhamlett @maxcountryman So, what's the status on a release? I'd love to use `USE_SESSION_FOR_NEXT`.

**Comment by maxcountryman** [comment]
We can do a release whenever I think.

**Comment by fenhl** [comment]
I've been trying to figure out why `USE_SESSION_FOR_NEXT` isn't working for me. If at all possible, Read The Docs should be configured to default to stable.

**Comment by maxcountryman** [comment]
@alanhamlett have you had a chance to review the PRs? Should we do a release?

**Comment by alanhamlett** [comment]
@maxcountryman yes, ready for a release.
