### ISSUE TITLE
module __version__

### ISSUE THREAD

**Issue by YKdvd** [maxcountryman/flask-login#341]
In 0.3.2, it appears that a \_\_version__ variable was set for the module.  In 0.4.0, it looks like things have been re-organized into a module?  The \_\_version__ and others have been moved into a file called \_\_about__.py, but this isn't imported or executed, so \_\_version__ is not defined at the module level.  

Was this change deliberate?  Many other modules (sqlalchemy, marshmallow, flask itself) define \_\_version__  at the main level:  "import someModule /  print someModule.\_\_version__".

**Comment by alanhamlett** [comment]
It's currently not imported because it's not needed anywhere, except in `setup.py`.

**Comment by YKdvd** [comment]
I've got a webpage in my flask app that diagnostically dumps out \_\_version__  from a list of various libraries used.  They all supply one except (as of 0.4) flask_login.  If there isn't any objection, it might be nice if flask_login restored this.  While [PEP 396](https://www.python.org/dev/peps/pep-0396/) was never official, the convention seems very common.
