### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by dtenenba** [maxcountryman/flask-login#349]
Make sure these boxes are checked before submitting your issue--thank you!

- [X] Ensure you are using the latest PyPI release.
- [X] Read the [CHANGES](https://github.com/maxcountryman/flask-login/blob/master/CHANGES) document thoroughly.
- [X] Provide a clear and simple set of steps to reproduce your issue for others.

flask-login is an awesome module and I got it working in a very short time. However, there were a few issues with the documentation that I spent some time trying to figure out. So here is a list of those issues so hopefully people in the future will not run across them again.

### Incomplete examples (or missing imports)

Every code snippet (IMO) should include the corresponding imports. Instead of this:

```python
login_manager = LoginManager()
```

do this:

```python
from flask_login import LoginManager

login_manager = LoginManager()
```

Otherwise the user has to go hunting around for the import. Maybe it's obvious where the import should come from, after all, this is the documentation for a specific module and likely it comes from there. But as Flask is a microframework, it's conceivable the user is working with multiple modules.

In the [Login Example](https://flask-login.readthedocs.io/en/latest/#login-example) the problem, in addition to missing imports, is that the example is incomplete. IMO it should include the full code (the definition of `app`, the full source of `LoginForm`, the creation of `login_manager`, the Jinja2 template, etc). Without this information the documentation assumes a level of familiarity with Flask, WTforms, and Jinja which may not exist.

There are a couple other issues with this example, see below:

#### Validation fails without CSRF snippet in template

Because the template is not shown in this example, it took me a while to figure out that validation was failing because this line was missing in the template:

```
{{ form.csrf_token }}
```

#### Setting the `flash` message is of limited usefulness without an example template

Another reason to include the template in this example is that without knowing how to display the flash message in a template, we never get to see the message that we set in the code.

At the very least, link to the [documentation](http://flask.pocoo.org/docs/0.12/patterns/flashing/#simple-flashing) for flashing so that an example is easily at hand.

#### `next` argument is not preserved between `GET` and `POST`

Say I have a page called `/settings` for which login is required (as described in this example).
When I go to that in my browser (`http://localhost:5000/settings`) and I'm not logged in, the URL changes to `http://localhost:5000/login?next=%2Fsettings`. However, when I then log in, when hitting the `/settings` endpoint with the `POST` method, the `next` argument is lost.

I fixed this by adding the following to my form:

```python
nexturl = HiddenField('next')
```

and then, inside the `login()` method. making sure that gets populated:

```python
    if request.method == 'GET':
        form.nexturl.data = request.args.get('next')
```

Then, when handling the `POST` method, instead of 

```python
next = flask.request.args.get('next')
```

I have:

```python
nexturl = form.nexturl.data
# ...make sure nexturl is safe, then redirect to it...
```

Note that I call the variable `nexturl` throughout (instead of `next`) because `next` conflicts with the built-in Python keyword and causes a warning in PyLint.

(Side note: is there a reason `is_safe_url()` is not part of `flask-login`?)

#### Make it clear that methods on `current_user` are implementation-specific

The example suggests using this snippet to show the name of the authenticated user:

```jinja
{% if current_user.is_authenticated %}
  Hi {{ current_user.name }}!
{% endif %}
```

That didn't work for me. I finally realized that `name` is an attribute of my `User` class which I've never set. Since my `User` class in my trivial example is `flask_login.UserMixin`, I just changed the snippet to 

```jinja
{% if current_user.is_authenticated %}
  Hi {{ current_user.get_id()  }}!
{% endif %}
```

...but really the documentation should make clear that the method you call on `current_user` is going to be specific to your implementation of `User`.

#### Example of a `login_required` route should be valid

In the following snippet:

```python
@app.route("/settings")
@login_required
def settings():
    pass
```

...when you actually visit that route in your browser, you get an error (because the view function did not return a response). Just change `pass` to `return "secret stuff!"` or some such.

#### Example log in view

In a trivial Flask application (which most users will be writing in order to understand/follow along with the documentation), you are not likely to have views like `users.login`. In the documentation's own example, the name of the login view is `login`, so I would suggest the example be changed from

```python
login_manager.login_view = "users.login"
```

to

```
login_manager.login_view = "login"
```

### Summary

That's as far as I have explored the module; as I look into other parts of it, I may come across other issues. But in general, full usable examples with imports would help much of the time. I realize that makes the documentation longer and perhaps more cluttered but it will save your users some time, as I can attest.

**Comment by davidism** [comment]
Please submit a pull request with these changes, although it would be easier to evaluate multiple smaller requests.

**Comment by alanhamlett** [comment]
These all look like great improvements, can you add a PR with these changes?

Some tips to render the docs locally as HTML, run these commands inside your virtualenv:

```
pip install sphinx
cd docs
mkdir -p _build/html
make html
```

Then open the html file at `_build/html/index.html` to preview your changes.
