### ISSUE TITLE
after login, i have login page refreshed instead of redirecting to dashboard.

### ISSUE THREAD

**Issue by senaps** [maxcountryman/flask-login#351]
hi, i have created this login page, it is working on local, but on server it just "started to fail".
the thing is, after i enter my login credentials, instead of redirecting to admin panel, i get the login page again.

`@mod.route('/login', methods=['GET', 'POST'])
@license
def login():
    print 'oooooooooooooooooooooo'
    if request.method == "POST":
        print 'ppppppppppppppppppppppppp'
      
        if request.form.get('username'):
            print request.form.get('username')
            user = User.query.filter_by(username=request.form.get('username')).first()
            print user.username
            print user.email
            print user.first_name
            print user.role_id
        else:
            flash('Please enter username.')
            return redirect(url_for('auth.login'))
        password = request.form.get('password').encode('utf-8')
        try:
            auth_log = AuthLog(username=request.form.get('username'),
                           is_available=True if user is not None else False,
                           status=True if user is not None and user.verify_password(password) else False,
                           ip=request.remote_addr
                   )
            print "Password Is ",str(user.verify_password(password))
            db.session.add(auth_log)
            db.session.commit()
            print "DB commit Successfully for auth log"
        except Exception as e:
            print e
        if user is not None and user.verify_password(password):
            print "User Authentication status",str(user.is_authenticated)
            print user.is_authenticated
            login_user(user, False)
            session.permanent = True
            user.last_last_login_ip = user.last_login_ip
            user.last_login_ip = request.remote_addr
            user.last_last_login = user.last_login
            user.last_login = datetime.now()
            user.last_login_show = False
            user.force_logout = True
            user.is_online = True
            db.session.commit()
            print "user loged and next url is :"
            next = request.args.get('next')
            print next
            print url_for("honeypot.dashboard")
            return redirect(next or url_for('honeypot.dashboard'))
        else:
            flash('Username or password is not correct.')
        return redirect(url_for('auth.login'))
    return render_template('auth/login.html')`

i have entered these print's so that i can check where i am. and i could trace up untill line 33( print user.is_authenticated)

any body able to help me find the error?

**Comment by alanhamlett** [comment]
@senaps, this type of question should be asked on [StackOverflow](http://stackoverflow.com/questions/tagged/flask-login). GitHub Issues is only for bugs and feature requests in the library itself.
