### ISSUE TITLE
Make REMEMBER_COOKIE_DURATION accept an integer like PERMANENT_SESSION_LIFETIME

### ISSUE THREAD

**Issue by jboegeholz** [maxcountryman/flask-login#357]
I want to configure my Flask app from a json file. At the moment I cannot set the value of REMEMBER_COOKIE_DURATION because it expects a datetime.timedelta(). 
PERMANENT_SESSION_LIFETIME can either be set to a datetime.timedelta() or to an integer representing seconds.

It would be great if REMEMBER_COOKIE_DURATION can also be assigned an integer

**Comment by alanhamlett** [comment]
Fixed with #370.
