### ISSUE TITLE
@login_required decorator 

### ISSUE THREAD

**Issue by GrayHatter** [maxcountryman/flask-login#383]
Is this a bug, or an intentional design decision? https://github.com/maxcountryman/flask-login/blob/master/flask_login/utils.py#L258 If I disable logins, (perhaps for server maintenance) any pages that you used to need to have authorization to view becomes public. That can't be what's intended. Perhaps instead; before ignoring the @login_required decorator, the app should be running in debug/development mode?

If it's intentional, shouldn't there be a few warnings through out the docs that the login_required decorator can't be used for security/authorization/authentication?

**Comment by davidism** [comment]
The documentation above what you linked:

>It can be convenient to globally turn off authentication when unit testing. To enable this, if the application configuration variable `LOGIN_DISABLED` is set to `True`, this decorator will be ignored.

So only set that configuration when testing. There doesn't need to be another check, it's assumed you're only going to set it during testing. I don't see why that suddenly makes `login_required` not suitable for the things it's designed for.

**Comment by GrayHatter** [comment]
The in-source documentation is insufficient when you're readme points to the "Complete" documentation on readthedocs. The docs on read the docs mentions that you can use the login_required decorator, but contains no mention that the decorator, may be disabled by a single unrelated config setting. Not disabled as in we'll block access, but disabled as in: When you disable login, we disable the security features you're trying to gain by requiring users to be authenticated. I clicked through to read the source code on a whim, if I hadn't I'd never had known I can disable security features unintentionally....

If that's really the design you guys have chosen, wtf? 

It's fine to make the assumption, but it's not okay to name it LOGIN_DISABLED, when what it does is disable security features. If the reasoning that this is wrong isn't clear. I can cite plenty of standards or implementations that, when disabling the ability to login, doesn't also disable the requirement that a user is logged in before accessing restricted sections. 

>  I don't see why that suddenly makes login_required not suitable for the things it's designed for.

1. The login_required decorator is likely being used as access control.
2. Wanting to prevent users from being able to login is a valid, and common use case (you even support that idea with "fresh sessions".
3. If I disable login, without reading the source. Instead of increasing security by prohibiting users from logging in. What I'm actually doing is disabling ALL security features.

If you're fine with a security feature that you can completely disable. That's fine too, just document it correctly so no one gets screwed, and I'll just write my own authorization manager.

**Comment by GrayHatter** [comment]
updated the usage example line 2 to read:

2. Wanting to prevent users from being able to login is a valid, and common use case (you even support that idea with "fresh sessions", where a user has to have logged in recently to access higher security settings).

**Comment by davidism** [comment]
The source documentation builds to what's seen on RTD. http://flask-login.readthedocs.io/en/latest/#flask_login.login_required
