### ISSUE TITLE
Flask-Login for multiple users table(like admin and user)

### ISSUE THREAD

**Issue by yiludege** [maxcountryman/flask-login#384]
how user_loader  distinguish between the different user classes.
just like:
```python
@login_manager.user_loader
def load_user(user_id):
    if request.path == "/apiv1.0/admin/":
        return Admin.query.get(int(user_id))
    else:
        return User.query.get(int(user_id))
```
the same question https://stackoverflow.com/questions/26242922/flask-login-for-multiple-users

**Comment by alanhamlett** [comment]
It's good that you posted to StackOverflow, that's the right place for questions which aren't bugs or feature requests.

**Comment by TechComet** [comment]
this bad method
