### ISSUE TITLE
Make an abstract user class to implement

### ISSUE THREAD

**Issue by Tadaboody** [maxcountryman/flask-login#387]
- [X] Ensure you are using the latest PyPI release.
- [X] Read the [CHANGES](https://github.com/maxcountryman/flask-login/blob/master/CHANGES) document thoroughly.
- [x] Provide a clear and simple set of steps to reproduce your issue for others.

### Have a class `AbcUser` to inherit from, which will in turn document the methods that must be implemented from.
```py
from typing import Text #Text is the typing for unicode strings, see https://docs.python.org/3/library/typing.html#typing.Text
from abc import ABC,abstractmethod #see https://docs.python.org/3/library/abc.html
class AbcUser(ABC):
     @abstractmethod
     def get_id(self) ->Text:
        """This method must return a unicode that uniquely identifies this user,
and can be used to load the user from the user_loader callback. Note that this must be a unicode -
 if the ID is natively an int or some other type, you will need to convert it to unicode."""
        pass
```

this way we can introduce both typing and documentation inside the built into the code and have it loosely enforced  

----
This way

```py
class MyUser(AbcUser):
def my_method():
...    pass
# Doesn't implement get_id()

user = MyUser()
```
results in
```
TypeError                                 Traceback (most recent call last)
<ipython-input-12-baad56b7d4c5> in <module>()
      4 # Doesn't implement get_id()
      5
----> 6 user = MyUser()

TypeError: Can't instantiate abstract class MyUser with abstract methods get_id
```

**Comment by Tadaboody** [comment]
Note that I'm aware of `UserMixin` but it would like a class that lets me override the methods myself while still knowing I've remembered to implement them all and correctly.

**Comment by alanhamlett** [comment]
An abstract class **is** a mixin, just a different name.
