### ISSUE TITLE
can't work with gunicorn with multiple workers

### ISSUE THREAD

**Issue by platec** [maxcountryman/flask-login#388]
If the worker_number is 1, everything is ok.
If the worker_number is greater than 1, I can't login in with flask-login.

**Comment by davidism** [comment]
Given that projects use this across multiple workers all the time, you'll need to provide an example that actually reproduce this issue.

**Comment by platec** [comment]
My `app.secret_key` was set as `os.urandom(24)`, so every worker will have another secret key and flask_login can't work
