### ISSUE TITLE
flask-login: is_authenticated is inconsistent

### ISSUE THREAD

**Issue by biertie** [maxcountryman/flask-login#389]
I have the impression that using is_authenticated from flask_login doesn't work properly. Giving the following logs that I get on my test environment:

    user_id
    True
    2018-06-04 17:05:15,350 - root - INFO - GET - /ngin/static/media/oval.svg? - 304 NOT MODIFIED
    False
    2018-06-04 17:05:15,369 - root - INFO - GET - /ngin/api/v2/menu/main? - 200 OK
    user_id
    True
    2018-06-04 17:05:25,697 - root - INFO - GET - /ngin/static/media/ngin_electricity.svg? - 304 NOT MODIFIED
    False
    2018-06-04 17:05:25,719 - root - INFO - GET - /ngin/api/v2/menu/lvgo? - 200 OK

The log line with the url is in the after_request block, so is printed at the end. The username ('user_id') comes from the login_manager.user_loader ; and the True or False come from the current_user.is_authenticated.
It seems that the user_loader isn't always called. And when it does, the user shows authenticated, but when the call doesn't happen, the is_authenticated returns false. 

My code is structured like this:

    class usrmgmr():

      def __init__(self, app):
        self.login_manager = fl.LoginManager()
        self.login_manager.init_app(app)
        self.login_manager.session_protection = 'strong'
    
        @self.login_manager.user_loader
        def load_user(user_id):
          print(user_id)
          return User(user_id)
    
      #Function to check if a user is authenticated.
      # returns True or False
      def is_loggedin(self):
        return fl.current_user.is_authenticated
    
      #only for debug purposes!
      def do_debug_login(self):
        user = User('user_id')
        fl.login_user(user, remember=True, duration=datetime.timedelta(seconds=7200)) 

And the code is used like this in run.py:

    usrmgmr = login.usrmgmr(app)
    @app.before_request
    def before_every_request():
      #check if for this endpoint a login is required.
      #if yes, and the user is not logged in, force the login method.
      #else we can just move on. Also the user probably is logged in then.
      if msec.needs_login(page_security):
        print(usrmgmr.is_loggedin())
        if usrmgmr.is_loggedin() == False:
           usrmgmr.do_debug_login()

So for every request we check if a user needs to be logged in to see the endpoint, and we check if the user is already logged in.

The strange thing is that sometimes I get 'True' and sometimes I get 'False'. So that doesn't seem very consistent. 

Does anyone know how to fix this, or what the reason is for this behaviour?

**Comment by alanhamlett** [comment]
Without seeing the whole picture with all your code I can't debug it. Can you post this question on StackOverflow since this isn't a bug report?
