### ISSUE TITLE
Please add @admin_required and @guest_required

### ISSUE THREAD

**Issue by TechComet** [maxcountryman/flask-login#398]
Hi,

Please add @admin_required and @guest_required
@admin_required is Necessary

@app.route('/guest')
@guest_required
def guest_page():
	return 'Guest Page .. Hi guest! (register page, login page)'

@app.route('/admin')
@admin_required
def admin_page():
	return 'Admin Page !'

**Comment by davidism** [comment]
You can build whatever decorators you need for your specific authorization scheme. Call `current_app.login_manager.unauthorized()` to enter the authentication flow.

```python
def admin_required(f):
    @functools.wraps(f)
    def wrapped_view(**kwargs):
        if not current_user_is_admin():
            return current_app.login_manager.unauthorized()
        return f(**kwargs)
    return wrapped_view
```

**Comment by alanhamlett** [comment]
@TechComet here's an [example permissions decorator](https://gist.github.com/alanhamlett/f9c8d6414cdd81502442fb5631b41fd9) using oauth scopes. You could modify it for your non-oauth permission check.

**Comment by TechComet** [comment]
This not my request but Ok!

Thanks
