### ISSUE TITLE
Strong Session Protection clobbers 'next' parameter in session

### ISSUE THREAD

**Issue by joearasin** [maxcountryman/flask-login#401]
Strong session protection means that the 'next' parameter gets clobbered when a user is redirected to the login page if current_user is called (As it may be in a shared template). This works fine if you drop the SESSION_PROTECTION to `"basic"` or `None`, or if you comment out the `current_user` noop

Here's a failing test case:

```python

    def test_unauthorized_with_next_in_strong_session_where_current_user_is_called(self):
        self.login_manager.login_view = 'login'
        self.app.config['SESSION_PROTECTION'] = 'strong'
        self.app.config['USE_SESSION_FOR_NEXT'] = True

        @self.app.route('/login')
        def login():
            if(current_user.is_authenticated):
                # A noop that touches current_user
                pass
            return session.pop('next', '')

        with self.app.test_client() as c:
            result = c.get('/secret')
            self.assertEqual(result.status_code, 302)
            self.assertEqual(result.location,
                             'http://localhost/login')
            self.assertEqual(c.get('/login').data.decode('utf-8'), '/secret')

```

**Comment by joearasin** [comment]
FWIW, using a few print statements as the noop makes debugging a bit easier

```python
print(session)
print(current_user)
print(session)
```

**Comment by joearasin** [comment]
A simpler reproduction:

```
    def test_current_user_does_not_clobber_next(self):
        self.app.config['SESSION_PROTECTION'] = 'basic'
        with self.app.test_request_context():
            session['next'] = '/next_url'
            self.assertTrue(current_user.is_anonymous)
            self.assertEqual('/next_url', session['next'])
```

**Comment by joearasin** [comment]
I think an approach to mitigating this could be to always put an identifier in the session, even for anonymous sessions. Or more specifically, always put an identifier in the session any time a key in SESSION_KEYS is being set.

**Comment by joearasin** [comment]
An alternative approach would be to always initialize the session, even when a user is logged out. That may be cleaner.

**Comment by cancan101** [comment]
is anyone else confused by the docs as to what `strong` does?
