### ISSUE TITLE
Missing warning in documentation for `login_required`

### ISSUE THREAD

**Issue by Vtec234** [maxcountryman/flask-login#405]
The [documentation for `login_required`](https://github.com/maxcountryman/flask-login/blob/master/flask_login/utils.py#L223) is missing a rather important point - that `@login_required` has to be placed below the `@app.route` decorator. Otherwise, the route will be registered before the login check code is added, and hence the route handler will not actually check whether the user is logged in, leading to security issues. Now, maybe this is obvious to everyone else, but it certainly isn't to me, and I think it would be worth at least mentioning it in the docs.

**Comment by slavkoja** [comment]
Flask [documentation](https://flask.palletsprojects.com/patterns/viewdecorators/#login-required-decorator) states:

> When applying further decorators, always remember that the route() decorator is the outermost.
