### ISSUE TITLE
AD user not logged in if "()" is in their First Name

### ISSUE THREAD

**Issue by thetechuser** [maxcountryman/flask-login#418]
Any user with parentheses in their First name in AD is not logged in by Flask. I am using Flask-ldap3-Login for ldap authentication and the user is getting authenticated successfully, per my AD logs. However, the user is not logged into the app. This is the error I get and nothing else. This is the only error that is shown even with debug mode on. How can I debug Flask-Login itself?

`[Wed Oct 31 13:01:25.253096 2018] [wsgi:error] [pid 11868] [remote 10.10.2.52:60101] ERROR:flask_ldap3_login:malformed filter`

This is my user class

`class User(UserMixin):`
    `def __init__(self, dn, username, data):`
        `self.dn = dn`
        `self.username = username`
       ` self.data = data`
    `def __repr__(self):`
       `return self.dn`
   ` def get_id(self):`
       ` return self.dn`

**Comment by davidism** [comment]
That's an issue with the LDAP filter, not Python, and would be handled by Flask-LDAP3-Login.
