### ISSUE TITLE
Ability to disable flashing of `login_message` on `login_manager.unauthorized()` handler 

### ISSUE THREAD

**Issue by shyamz-22** [maxcountryman/flask-login#419]
When trying to access a protected page directly, after the user is successfully authenticated and the landing page reads the flashed messages, `Please login to access the page` message is shown always, which is surprising when you see at first as the user just authenticated themselves. 

A work around would be to customize the category for login_message and filter flashed message on the template based on category so as to not show this. But this seems to be an work around nevertheless

A nice to have would be to disable the `login_message`  by default and enable it if needed.

**Comment by shyamz-22** [comment]
To reproduce this issue, run the application in https://github.com/shyamz-22/bankingPy/releases/tag/v0.1

Set up an user in the MySQl database users table, password hash can be generated by 
```
>>> from werkzeug.security import generate_password_hash
>>> hash = generate_password_hash('foobar')
>>> hash
```
*Step 1:*  Access http://127.0.0.1:5000/account/debit
*Step 2:*  Login successfully
*Step 3:*  Then you will see the flashed message.

**Comment by alanhamlett** [comment]
The recommended way to customize the flashed message is with a custom `unauthorized_handler`:
https://flask-login.readthedocs.io/en/latest/#customizing-the-login-process
https://flask-login.readthedocs.io/en/latest/#flask_login.LoginManager.unauthorized_handler
