### ISSUE TITLE
Login Required with role validation

### ISSUE THREAD

**Issue by brennoflavio** [maxcountryman/flask-login#421]
Often in my implementations of Flask Login, I need to implement a role system, so I can make admin only views. The way I did it is to implement a new decorator based on ```login_required```, called it ```login_with_role```:

```
def login_with_role(role, *args, **kwargs):
    def login_required(func):
        @wraps(func)
        def decorated_view(*args, **kwargs):
            if not current_user.is_authenticated:
                return current_app.login_manager.unauthorized()
            elif current_user.role() not in role:
                return current_app.login_manager.unauthorized()
            elif request.method in EXEMPT_METHODS:
                return func(*args, **kwargs)
            elif current_app.config.get('LOGIN_DISABLED'):
                return func(*args, **kwargs)
            return func(*args, **kwargs)
        return decorated_view
    return login_required
```

This also needs implementation of ```role()``` method on User class. This allow creating views like this:
```
@app.route("/", methods=["GET"])
@login_with_role("admin")
def my_view():
...
```

So only admins will be allowed to see the view.

Is there any discussion about this topic? I think this can be very useful for many cases!

**Comment by jslay88** [comment]
I think a better proposed solution would be something along the lines of this, as authenticating should be separate from permission levels.

This would redirect per usual if not authenticated via `login_manager.unauthorized()` and would return a `403 Forbidden` when permissions levels are not met.

You could even do something where a list of any roles can be required, or a list of all roles can be required

```
def role_required(role):
    def _role_required(f):
        @wraps(f)
        def decorated_view(*args, **kwargs):
            if not current_user.is_authenticated:
                return login_manager.unauthorized()
            if not current_user.has_role(role):
                return 'Forbidden', 403
            return f(*args, **kwargs)
        return decorated_view
    return _role_required


def roles_required(roles, require_all=False):
    def _roles_required(f):
        @wraps(f)
        def decorated_view(*args, **kwargs):
            if not current_user.is_authenticated:
                return login_manager.unauthorized()
            if require_all and all(current_user.has_role(role) for role in roles):
                return 'Forbidden', 403
            if not any(current_user.has_role(role) for role in roles):
                return 'Forbidden', 403
            return f(*args, **kwargs)
        return decorated_view
    return _roles_required
```

**Comment by DTHerrera** [comment]
Hey, how you doing?

I know that this issue is already closed, but implement what is mentioned here as a Work.Around roll validation management.

as follows:

class User(UserMixin, PaginatedAPIMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(64),nullable=False) 
    lastname = db.Column(db.String(64),nullable=False) 
    username = db.Column(db.String(32), index=True, unique=True)
    ...
    def has_role(self, role):
        return any(role == role_assignment.role.name and role_assignment.role.active
                   for role_assignment in self.role_assignments)

class Role(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))
    active = db.Column(db.Boolean, default=True, nullable=False)

    def __init__(self, name, description, active=True):
        self.name = name
        self.description = description
        self.active = active

class RoleAssignment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    role_name = db.Column(db.VARCHAR(80), db.ForeignKey('role.name'), nullable=False, unique=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False, unique=True)
    role = db.relationship('Role', backref=db.backref('role_assignments', lazy='joined'), lazy='joined')
    user = db.relationship('User', backref=db.backref('role_assignments', lazy='joined'), lazy='joined')

    def __init__(self, role_name, user_id):
        self.role_name = role_name
        self.user_id = user_id

def role_required(role: str):
    def _role_required(f):
        @wraps(f)
        def decorated_view(*args, **kwargs):
            if not current_user.is_authenticated:
                return login.unauthorized()
            if not current_user.has_role(role):
                return 'Forbidden', 403
            return f(*args, **kwargs)
        return decorated_view
    return _role_required


def roles_required(roles: list, require_all=False):
    def _roles_required(f):
        @wraps(f)
        def decorated_view(*args, **kwargs):
            if len(roles) == 0:
                raise ValueError('Empty list used when requiring a role.')
            if not current_user.is_authenticated:
                return login.unauthorized()
            if require_all and not all(current_user.has_role(role) for role in roles):
                return 'Forbidden', 403
            elif not require_all and not any(current_user.has_role(role) for role in roles):
                return 'Forbidden', 403
            return f(*args, **kwargs)
        return decorated_view
    return _roles_required

and I use it as follows

@bp.route('/settings', methods=['GET', 'POST'])
#@login_required
@roles_required('admin')
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash(_l('Configuración actualizada.'), 'success')
        return redirect(url_for('main.index'))
    settings = Admin.query
    form.blog_title.data = settings.blog_title
    form.blog_sub_title.data = settings.blog_sub_title
    form.about.data = settings.about
    return render_template('admin/settings.html', form=form)

when validating the user has the role "admin", it always sends error, but when validating the method "has_role" in the class user it turns out that it receives it character by character

127.0.0.1 - - [27/Jul/2020 00:14:18] "POST /auth/login?next-%2Fsettings HTTP/1.1" 302 -
role: 'a'
role: 'd'
role: 'm'
role: 'i'
role: 'n'
127.0.0.1 - - [27/Jul/2020 00:14:18] "GET /settings HTTP/1.1" 403 -

You know what I'm doing wrong?

thank you very much for your support

regards

**Comment by jslay88** [comment]
`roles_required` takes a list, not a string.

```py
@roles_required(['admin'])
def settings():
```

**Comment by DTHerrera** [comment]
Thank you so much for helping me.

was confused in using decorators

regards
