### ISSUE TITLE
Deprecate the Remember Me implementation in favor of a "freshness expiry" time

### ISSUE THREAD

**Issue by dcosson** [maxcountryman/flask-login#422]
I've recently been digging into the internals of flask-login to make sure sessions in my app are behaving as needed, and the current implementation of Remember Me cookies seems less than ideal. I realize this is a big change but I'm curious if you'd be open to changing it.

From what I have gleaned, and please correct me if my starting assumption is wrong, the purpose of the Remember Me cookie is to enable the freshness behavior in Flask Login. One obvious use case of which is to allow overall sessions to be longer lived so users are not constantly having to re-enter their passwords, but be able to add an extra layer of security to certain routes by requiring a fresh login.

It doesn't seem like the current Remember Me functionality is a very good way of enabling this though, for a few reasons:

  - it doesn't work well for anyone using stateful sessions since it lives outside of Flask's session abstraction. If you are using stateful sessions, and want to be able to reliably expire old sessions for users, maybe when their password changes, or if they have had an account takeover, etc. the Remember Me cookie breaks this since any live cookie in the wild can always come back and create a new logged in session for the user. 

  - it's unintuitive for new users of this library, because for all intents and purposes real session object is now the Remember Me cookie and not the flask session object, so for instance you may think you are setting a max age on your sessions with PERMANENT_SESSION_LIFETIME but you're not. 

  - The first paragraph in the docs seems to be flat-out wrong. It says `By default, when the user closes their browser the Flask Session is deleted and the user is logged out. “Remember Me” prevents the user from accidentally being logged out when they close their browser.` It's surprising to me that this could be so wrong, maybe it was once true but it isn't anymore. The PERMANENT_SESSION_LIFETIME defaults to 31 days per the [Flask docs](http://flask.pocoo.org/docs/1.0/api/#flask.Flask.permanent_session_lifetime). This sets the max-age on the session cookie, and any modern browser will treat a cookie that has a max-age as a [persistent rather than a session cookie](https://en.wikipedia.org/wiki/HTTP_cookie#Session_cookie) which means they're not cleared when the browser is closed. So basically, unless I'm missing something it seems like the initial reason for having the Remember Me cookie is no longer valid and it has evolved to just control the freshness bit.

It would be nice if there were a global config option to disable Remember Me cookies altogether (rather than allow the `remember` boolean being passed to invocations of `login_user`). It should probably even be marked deprecated in the docs since it no longer serves its original purpose.

And then separately, it would be great if the freshness could be controlled as a separate freshness expiration time and live within the session data itself. This way it fits Flask's session abstraction a lot better, and it just seems like a much less convoluted model to understand, without giving anything up.

**Comment by RazerM** [comment]
> The PERMANENT_SESSION_LIFETIME defaults to 31 days per the Flask docs. This sets the max-age on the session cookie, and any modern browser will treat a cookie that has a max-age as a persistent rather than a session cookie which means they're not cleared when the browser is closed. So basically, unless I'm missing something it seems like the initial reason for having the Remember Me cookie is no longer valid and it has evolved to just control the freshness bit.

This is only used if [`session.permanent`](http://flask.pocoo.org/docs/1.0/api/#flask.session.permanent) is set to `True`, which is not the default. It might be possible you're affected by #424, which I just filed.

**Comment by maxcountryman** [comment]
Closing this for now.
