### ISSUE TITLE
Please release 0.4.2

### ISSUE THREAD

**Issue by GuilloOme** [maxcountryman/flask-login#425]
There was a lot of commit since the last release (and some fixing some important issue).
Why there was no release since Dec. 2017?

Thanks,

**Comment by mark-schulze** [comment]
I just installed it this way now: 
pipenv install git+https://github.com/maxcountryman/flask-login.git#egg=flask-login

**Comment by singingwolfboy** [comment]
I suggest making the next release 1.0, since Flask-Login is already widely used. [ZeroVer](http://0ver.org) is a bad look.

**Comment by maxcountryman** [comment]
What’s the objection to ZeroVer?

**Comment by singingwolfboy** [comment]
@maxcountryman: a version number below 1.0 indicates that the software is immature and unstable. See the [SemVer](https://semver.org/) spec, point 4:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Flask-Login is widely used enough that the public API _should_ be considered stable. Making a backward-incompatible change at this point would cause a lot of software that depends on Flask-Login to break. Therefore, we should formalize this state of affairs, and just release a version 1.0 to indicate that Flask-Login is mature and stable.

**Comment by singingwolfboy** [comment]
Also note, from the [ZeroVer about page](http://0ver.org/about.html):

> ZeroVer is satire, please do not use it. We sincerely hope no project release schedules were harmed as a result of this humble attempt at programmer humor.

**Comment by maxcountryman** [comment]
That's fine with me.
