### ISSUE TITLE
Set remember me cookie HttpOnly flag by default

### ISSUE THREAD

**Issue by skylerberg** [maxcountryman/flask-login#426]
I believe flask login should default to secure settings where possible. The remember me token currently defaults to not having the `HttpOnly` flag. This means that if the website is vulnerable to any cross-site scripting attacks (which is very common) then an attacker can steal the remember token. The `HttpOnly` flag can be used to limit the impact of cross-site scripting by not allowing javascript on the site to access the cookie, thus preventing the attacker from stealing the user's session completely.

Accessing the remember token in javascript seems like an uncommon use case. This means that changing the default to HttpOnly is not likely to impact most users.

Let me know your thoughts.

**Comment by maxcountryman** [comment]
That seems pretty reasonable to me.

**Comment by Dreamsorcerer** [comment]
It appears the documentation change was merged, but not the code change. So, this issue is still open.

**Comment by Dreamsorcerer** [comment]
@maxcountryman ?

**Comment by alanhamlett** [comment]
Code change merged with #488.
