### ISSUE TITLE
Modifying/extending current_user

### ISSUE THREAD

**Issue by macfire** [maxcountryman/flask-login#427]
It it possible to add a key/value pair to the current_user object after log in?

<s>If not, would a global variable `g` be the way to go?</s>

For example, after login, the user is redirect to a home page -- at which point I'd like to assign a key/value (based on some user-action) that can be used throughout the site.

Non-working example:
Python
```python
current_user['mykey'] = 'my value'
```
Jinja2
```jinja2
{{ current_user.mykey }}
```

--
Updated: After some research, I've ruled out `g` variable.

**Comment by alanhamlett** [comment]
Current user is not defined by Flask-Login, it's whatever your [user_loader](https://flask-login.readthedocs.io/en/latest/#flask_login.LoginManager.user_loader) callback returns. Normally you return an object that allows setting attributes with [setattr](https://docs.python.org/3/library/functions.html#setattr).

**Comment by macfire** [comment]
[flask_login.current_user](https://flask-login.readthedocs.io/en/latest/#flask_login.current_user) is a proxy for the current user.
I understand that current_user is not defined by Flask-Login ...    
but  is the value of `flask_login.current_user` set to what is returned by `user_loader` method?

(If it matters, I'm using Flask-Security, which uses Flask-Login)

**Comment by alanhamlett** [comment]
> but is the value of flask_login.current_user set to what is returned by user_loader method

Yes, the value of `flask_login.current_user` is the same object as what's returned by `user_loader` so modifying an attribute on one will also modify that attribute on the other.
