### ISSUE TITLE
Signals for user_registered and invalid_login_attempt

### ISSUE THREAD

**Issue by asselinpaul** [maxcountryman/flask-login#437]
flask-login provides signals described here: https://flask-login.readthedocs.io/en/latest/#signals

It would be helpful to expand these to cover:

- `user_registered` as provided by FlaskUser (https://flask-user.readthedocs.io/en/latest/signals.html?highlight=signals)

- `invalid_login_attempt` would also be useful (for threat/security monitoring)

- `password_reset`

**Comment by maxcountryman** [comment]
Seems like a good addition. We’d be happy to review a PR.

**Comment by AlanSwenson** [comment]
I attempted to work on this issue. But I have a huge question.  All of these actions would be coded on the business side of the app.  AKA, Flask-Login only logs a user in when the business logic outside of Flask-login permits it, therefore Flask-Login never knows if there is an invalid attempt made, likewise for a user being registered and password reset, these things don't happen in Flask-Login to the best of my knowledge and therefore I don't think a signal could fire from within the app. Am I horribly wrong? If so let me know where to look and Ill work on this issue.

**Comment by davidism** [comment]
@AlanSwenson you're correct, the events asked for here are not within Flask-Login's scope, so there would be no place within the code to send these signals from.
