### ISSUE TITLE
Flask Login ignores REMEMBER_COOKIE_DURATION

### ISSUE THREAD

**Issue by Yakuza-UA** [maxcountryman/flask-login#443]
I am trying to make Login sessions persistent (do not expire when browser closes) with certain lifetime (e.g. 15 minutes). Apart from Flask Login my app is also using LDAP3 Flask Login. 

Currently I observe persistence behavior regardless of 'REMEMBER_COOKIE_DURATION'.

I've checked my session dict and can see that session['_permanent'] is set to True, which is weird, as I don't explicitely set this one in my application and I don't believe LDAP3 Flask Login does anything to it. I tried the following as part of my Config class.

`    REMEMBER_COOKIE_DURATION = timedelta(minutes=1)`
(effectively same as app.config['REMEMBER_COOKIE_DURATION'] = timedelta(minutes=1))

This has zero effect on session duration. 
I am able to achieve 'session expired' behavior with this

```
@app.before_request
def before_request():
    session.permanent = True
    app.permanent_session_lifetime = timedelta(minutes=1)
```

This, however, invalidates whole Flask session and not just Login. Basically, if I store some other conveniency parameters in the Cookie - they are invalidated. I don't want to expire Flask session, but rather want to make sure Flask Login is doing what it has to do according to the documentation.

Here's how I login the user:

```
    form = LoginForm()
    if form.validate_on_submit():
        login_user(form.user)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('list')
        return redirect(next_page)
    return render_template('login.html.j2', title='Sign In', form=form)
```

What am I doing wrong?

P.S. Also, according to Flask 1.0.2 documentation, default behavior is 'session expired when browser is closed' which is not true for me and I don't know why it is persistent by default (at Flask level). Anyway, I believe this is unrelated as Flask Login uses separate Cookie for login session. Correct me if I am wrong.

--- update ---
I am using Flask-Login 0.4.1

**Comment by tianhanfangyan** [comment]
if you use flask-login, you need use this func: 
def login_user(user, remember=False, duration=None, force=False, fresh=True)
param:remember: Whether to remember the user after their session expires. Defaults to ``False``.
param duration: The amount of time before the remember cookie expires. If ``None`` the value set in the settings is used. Defaults to ``None``

**Comment by Yakuza-UA** [comment]
> if you use flask-login, you need use this func:
> def login_user(user, remember=False, duration=None, force=False, fresh=True)

Hi. Thanks for this

I beleive I am already doing this, such as below:
`    form = LoginForm()
    if form.validate_on_submit():
        login_user(form.user)
`

As you can see, I don't pass anything for duration and remember, so by default it shouldn't remember my session (as it will be false), or make it sticky, but it does!

**Comment by makeworld-the-better-one** [comment]
Are you doing `flask_login. REMEMBER_COOKIE_DURATION = timedelta(minutes=1)`?

**Comment by makeworld-the-better-one** [comment]
Never mind, I'm experiencing this too. It still stays as the default of a year even with the code above.

**Comment by 5uper5hoot** [comment]
I've just been down a similar rabbit hole.

> Anyway, I believe this is unrelated as Flask Login uses separate Cookie for login session. Correct me if I am wrong.

Flask-Login uses the Flask session primarily. The user_id is stored on there and retrieved from there to load the user for as long as it exists. If the Flask session is expired, and as long as the Flask-Login remember cookie is set (`login_user(..., remember=True)`) and still current, Flask-Login puts the user_id back into the Flask session and sets `session["_fresh"] = False` to re-enable logged in behavior.

> I tried the following as part of my Config class.
> 
> REMEMBER_COOKIE_DURATION = timedelta(minutes=1)
> (effectively same as app.config['REMEMBER_COOKIE_DURATION'] = timedelta(minutes=1))
> 
> This has zero effect on session duration.

The `REMEMBER_COOKIE_DURATION` app config is read when creating the remember cookie, and that is only created if you pass `remember=True` to `login_user()` function. From your example above, you have the "Remember Me" behavior disabled and so that config value is not doing anything.

**Comment by makeworld-the-better-one** [comment]
@5uper5hoot I'll test again later, but I believe I was using `remember=True`

**Comment by 5uper5hoot** [comment]
@makeworld-the-better-one I was specifically addressing the OPs post but the global config variable is `COOKIE_DURATION`, without the `REMEMBER_` part. Both `flask_login.COOKIE_DURATION` and `login_manager.COOKIE_DURATION` are refs to `config.COOKIE_DURATION` and so when you overwrite `flask_login.COOKIE_DURATION` as you have done, it doesn't change the value that `LoginManager` sees when it falls back to the default setting. E.g.:

```
>>> import flask_login
>>> from flask_login import login_manager
>>> flask_login.COOKIE_DURATION is login_manager.COOKIE_DURATION
True
>>> flask_login.COOKIE_DURATION = "Foo"
>>> flask_login.COOKIE_DURATION is login_manager.COOKIE_DURATION
False
>>> login_manager.COOKIE_DURATION
datetime.timedelta(days=365)
```
I can't see anywhere it's documented that Flask-Login should be configured through modifying those library globals and it doesn't appear all that practical to do it that way anyway.

**Comment by maxcountryman** [comment]
A minimal reproduction case, as a test, would be extremely helpful. Closing until then.

**Comment by makeworld-the-better-one** [comment]
@maxcountryman does the bug not occur for you?
