### ISSUE TITLE
async calls to database do not work

### ISSUE THREAD

**Issue by wpmjones** [maxcountryman/flask-login#445]
Maybe I'm not doing something right, but I'm using asyncpg to connect to my postgresql database which houses my users.  The user_loader is synchronous.  I have tried using `loop.run_until_complete` but I get one of the following errors:
`Cannot run the event loop while another loop is running`
`RuntimeWarning: coroutine 'User.get' was never awaited`

Am I trying to do something that just isn't possible with this package or am I missing a step somewhere?

Code at:
https://github.com/wpmjones/studtext/blob/master/temp.py

**Comment by davidism** [comment]
Flask does not yet support ASGI. That's required before any extensions can think about support for async, at which point every extension will still need to be written to support async. If you're interested in adding ASGI support, see https://github.com/pallets/werkzeug/issues/1322.

**Comment by pgjones** [comment]
@wpmjones I would value your thoughts on [Quart-Auth](https://gitlab.com/pgjones/quart-auth) which is roughly an async equivalent of Flask-Login.
