### ISSUE TITLE
login_required OPTIONS exemption may be leading to auth bypasses

### ISSUE THREAD

**Issue by ndavison** [maxcountryman/flask-login#448]
Referring to:

https://github.com/maxcountryman/flask-login/issues/243
https://github.com/maxcountryman/flask-login/pull/244

I'm wondering if these measures may have gone a little far and may be resulting in `login_required` authentication bypasses in apps for some unsuspecting devs.

For example, consider this Flask endpoint:

```
@main.route('/secret', methods=["GET", "OPTIONS"])
@login_required
def secret():
    if request.method == "OPTIONS":
        response.headers['Access-Control-Allow-Methods'] = 'GET, PUT, DELETE'
    response = make_response('This is a secret')
    return response
```

Here the dev is supporting both GET and OPTIONS for `/secret`. The dev is deliberately overriding Flask's behavior of always responding to OPTIONS requests on GET enabled resources so they can include the custom CORS pre-flight header in the response.

What may not be clear to the dev is they have infact created a bypass for authentication - anyone can now issue a OPTIONS request to `/secret` without any authentication, and `This is a secret` will be the response. A GET will suitably return a 401.

The problem as I see it is, because OPTIONS is exempt, the dev will not experience any issues with the above code - it will work largely as intended, because the GET will require authentication and the CORS request that also uses this endpoint will just work. Such a dev would be unlikely to realise they have opened up the endpoint to no authentication when issuing an OPTIONS request, however. I appreciate the docs do mention this, but I don't believe it's an intuitive outcome and, based on the code above, breaks a 'secure by default' approach.

If OPTIONS was not exempt in `login_required`, this dev would likely realise their mistake as soon as they went to test CORS against this endpoint, assuming the test included a preflight condition, as it would 401.

To me, a 401 is the appropriate outcome - the code above is a bad design and as such, probably should fail. I would question whether Flask-Login should be accommodating this sort of design. Perhaps it is best solved by not trying to use `login_required` with OPTIONS at all? e.g. the fix for the code above is to create a new function for this route that responds to only OPTIONS and only includes the relevant CORS headers, and not the authenticated response.

I understand, based on the previous issue ticket that resulted in OPTIONS being exempt, that a different approach to creating a flask endpoint was referenced (MethodView?), which I'm not too familiar with, but it seems to me this exemption is a little easier to hang yourself with security wise when using the decorator and function approach as above.

**Comment by maxcountryman** [comment]
Makes sense to me. Please feel free to address with a PR.
