### ISSUE TITLE
The _id session value is fixated between logins and logouts

### ISSUE THREAD

**Issue by ndavison** [maxcountryman/flask-login#449]
I noticed that the `_id` attribute that flask-login creates in the Flask session appears to be sticking around even after calling `logout_user()` and `login_user()`.

Here's a simple Flask app that will show this:

https://gist.github.com/ndavison/52317885235554bfcfdd13a522aa1b5a

If you `flask run` this, you'll see the session printed to the console before every request. In this example I'm using `flask_login` to create a session for anonymous users as well (when accessing `GET /`). If you note the `_id` in the session given to you when accessing `GET /`, then access `GET /login` and `GET /logout`, and then `/login` again, the `_id` in the session is unchanged since the first anonymous access. I believe this is also an issue if your Flask app doesn't give sessions to anonymous users (in which case, it would be demonstrated by authenticating as one user, logging out, and authenticating as another in the same browser session).

The impact of this seems fairly benign out-of-the-box, but if a dev were to incorporate this `_id` value in their app logic, thinking it uniquely identified a login, then this could effectively amount to a session fixation issue, whereby an attacker could first establish a session cookie, and abuse some other vulnerability (e.g. response header injection) to pass the cookie onto another user (who may be anonymous at this point), and when they authenticated, their authenticated session would still contain this `_id`.

I understand there are issues with completely destroying the Flask session on login and logout as it may be used to store other things not related to flask-login, but I imagine the `_id` value can be destroyed and regenerated on login and logout? if so, I'm happy to put forward a PR with this change.

**Comment by ndavison** [comment]
Apologies, only just noticed this should be fixed in the next release via https://github.com/maxcountryman/flask-login/pull/404

Although it's not immediately obvious to me this PR refreshes the `_id` on login as well as logout (to protect against fixation when a user goes from anonymous to authenticated).

**Comment by ndavison** [comment]
Re-opening because I don't believe #404 prevents the session `_id` from being fixated when going from anonymous to authenticated.

**Comment by maxcountryman** [comment]
0.5.0 is released now, so I'm going to close this. But if this is still an issue please provide a minimal reproduction case and we'll re-open.
