### ISSUE TITLE
Missing REMEMBER_COOKIE_SAMESITE config

### ISSUE THREAD

**Issue by Dreamsorcerer** [maxcountryman/flask-login#452]
The remember cookie equivalent of SESSION_COOKIE_SAMESITE from the flask config doesn't appear to exist.

**Comment by Dreamsorcerer** [comment]
@maxcountryman Any chance of getting a new release? With Chrome having changed the SameSite defaults, this is probably a good time to ensure this option is available.

**Comment by Dreamsorcerer** [comment]
Also, related, please check PR #488 . I think you closed it by mistake, when you actually intended to merge it.

**Comment by maxcountryman** [comment]
@Dreamsorcerer as I've previously mentioned, if someone wants to setup the PyPI release on tag mechanism, I'd be happy to author a new release.
