### ISSUE TITLE
Files served at url are visible to anonymous users

### ISSUE THREAD

**Issue by elamje** [maxcountryman/flask-login#456]
**Describe the bug**
User uploaded file viewer is wrapped in ```@login_required```, but somehow both anonymous users and other users can see that users file.

**To Reproduce**
1. Upload file "X.pdf" as user Y
2. Logout
3. As anonymous user, browse to show/X.pdf
4. File is visible
or 
3. As a different user, browse to show/X.pdf
4. File is visible

**Expected behavior**
I expect to be redirected to my login view when an anonymous person tries to go to this address.

**Desktop (please complete the following information):**
 - OS: MacOS, iOS
 - Browser Safari & firefox
 - Version Latest

**Additional context**
Code 
```python
@app.route('/show/<filename>')
@login_required
def show(filename: str) -> Union[Response, str]:
    filename = secure_filename(filename)  # clean user input
    user_dir = os.path.join(app.config['UPLOAD_FOLDER'], current_user.uuid)
    if os.path.exists(os.path.join(user_dir, filename)):
        return send_from_directory(directory=user_dir, filename=filename)
    else:
        abort(404)
```

I honestly have no clue how this is happening. Each user has a unique uuid that acts as a unique directory where their files get stored to disk. 

My bug might come from a misunderstanding of how cookies and session data are stored here. It might be relevant that I am accessing these file urls shortly after being logged in as the correct user that owns the files.

**Comment by elamje** [comment]
Hmm, it seems like the issue might have been that there were some cookies still hanging around from the session, so it was able to "authenticate" even though I was anonymous user. 

Can someone explain why this might be?

**Comment by ndavison** [comment]
Are you making sure to clean out your unique uuid from the session on login and logout?

https://github.com/maxcountryman/flask-login/pull/404/files

This PR shows a pattern using `.pop()` to remove the value from the session, in this case the inbuilt `_id` value that Flask-Login sets. Note you should also do this when a user logs in and not just logging out, to avoid the anonymous to authenticated user fixation user (logout should cover user to user fixation).

I can't recall which PR/issue it was, but when researching that `_id` fixation I came across discussion on this repo recently about the maintainers being reluctant to clear the entire user session on login/logout, as the Flask session can be used for things other than tracking authentication, so doing that might have unintended consequences. So basically, if you add something to the Flask session and give that value meaning for the user Flask-Login is tracking, you are still responsible for cleaning it up on login and logout.

**Comment by elamje** [comment]
It looks like this might be it:
https://github.com/maxcountryman/flask-login/pull/404/commits/32ff15e1f1b0102d0a8c01ef6da79990846cf085

So what I'm seeing now is that my session has these keys before `logout()`:
`dict_keys(['_fresh', '_id', 'csrf_token', 'user_id'])`
and these keys after `logout()`:
`dict_keys(['_id', 'csrf_token'])`

@maxcountryman Do you mind elaborating on why these session keys are useful to keep around?

**Comment by elamje** [comment]
@ndavison The uuid is not stored in the session, which is confusing. I am still able to reproduce the bug after clearing all session data on logout. Interestingly, even though I have the `show(filename)` function decorated with `@login_required` I can hit the '/show/<filename>' url and I'm not redirected to the login screen like I should be.

I am wondering if Nginx/gunicorn is doing any kind of caching trickery here now, so I'm going to look into that.

**Comment by ndavison** [comment]
What does your `@login_manager.user_loader` callback look like? As your comment above shows, the `_id` is sticky (looks like this will be fixed in the next major release https://github.com/maxcountryman/flask-login/pull/436) so if you're using this for any sort of logic in loading the user from the cookie and session, it may be causing an issue.

In the `/show/x` route, which `current_user` id, name etc does it think is logged in when you're experiencing the issue?

FYI, unrelated but based on your comment above, you'll need to clear the CSRF token on login as otherwise it too is prone to session fixation issues - the attack could be an anonymous user generates a session with a CSRF token they know, somehow gives this session to another user (using some other vulnerability, like response header injection), this other user elevates the session into an authenticated one, and therefore the attacker knows this authenticated user's CSRF token.

**Comment by elamje** [comment]
@ndavison Thanks for the detailed responses. After the entire day, I discovered what my problem was, and I'm sad to say it was Cloudflare for production. I was so confident I was thinking of every part of my stack, but I forgot about how aggressive Cloudflare caches content (images in this case). 

I believe I was reproducing the issue locally because my browser was caching the results, but I'm going to look into it more. 

Thanks again!
