### ISSUE TITLE
New release - 1.0.0

### ISSUE THREAD

**Issue by romanek-adam** [maxcountryman/flask-login#459]
Hi, I can see the last release of this package was on Dec 4, 2017 (0.4.1). So it's almost two years now and since then a lot happened, there's even this 1.0.0 version in CHANGELOG which adds FlaskLoginClient, which I'm particularly interested in.

When do you expect v1.0.0 to be released? Is there anything I can do to push this?

**Comment by romanek-adam** [comment]
The discussion moved to StackOverflow: https://stackoverflow.com/questions/58587311/flask-login-any-chance-for-release-v1-0-0

**Comment by mbierma** [comment]
Since the SO discussion was removed by moderators, were there any relevant updates?
