### ISSUE TITLE
when set USE_SESSION_FOR_NEXT, logout_user() don't pop the 'next'

### ISSUE THREAD

**Issue by wowo878787** [maxcountryman/flask-login#460]
**Describe the bug**
I set _USE_SESSION_FOR_NEXT_ to _True_ and there was a '_next_' in my session, I didn't pop it manually after I use it in my login function, and when I logout with _logout_user()_, the '_next_' is still there. then the next time I login, I got an unexpected redirect.
I'm not sure if this is an issue, should I pop it manually?

**Comment by maxcountryman** [comment]
If you can provide a minimal reproduction case, that will help us diagnose. Closing now for now.
