### ISSUE TITLE
test_unauthorized_uses_host_from_x_forwarded_for_header (test_login.StrictHostForRedirectsTestCase) fails with Werkzeug>=0.15.0

### ISSUE THREAD

**Issue by eriol** [maxcountryman/flask-login#461]
Running the test suite of release 0.4.1 with Werkzeug>=0.15.0 makes `test_unauthorized_uses_host_from_x_forwarded_for_header` fails with the following:
```
======================================================================
FAIL: test_unauthorized_uses_host_from_x_forwarded_for_header (test_login.StrictHostForRedirectsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/flask-login/test_login.py", line 1537, in test_unauthorized_uses_host_from_x_forwarded_for_header
    'http://proxy.com/login?next=%2Fsecret')
AssertionError: 'http://foo.com/login?next=%2Fsecret' != 'http://proxy.com/login?next=%2Fsecret'
- http://foo.com/login?next=%2Fsecret
?        ^ ^
+ http://proxy.com/login?next=%2Fsecret
?    
```
**To Reproduce**
1. Clone this repository and checkout 0.4.1 tag.
2. Create a virtualenv (I used Python 3.7.5)
3. `pip install -r dev-requirements.txt` inside the virtualenv
4. Run `nosetests` and verify that all tests pass
5. pip install Werkzeug==0.15.0
6. Run tests again and verify that test_unauthorized_uses_host_from_x_forwarded_for_header fails with the above error.

In Werkzeug [0.15.0](https://werkzeug.palletsprojects.com/en/0.16.x/changes/#version-0-15-0) the test.Client redirect handling was rewritten, so maybe it is the root cause of this issue.

**Comment by maxcountryman** [comment]
Closing now that 0.5.0 is released; please let us know if this is still an issue in that release.

**Comment by eriol** [comment]
Thanks for addressing, it works in 0.5.0.
