### ISSUE TITLE
session["user_id"] = user.id authenticates user

### ISSUE THREAD

**Issue by danielperna84** [maxcountryman/flask-login#465]
**Describe the bug**
Hi. I am farily new to Flask, so I'm unsure if the following is a bug or not.

My Flask app allows users to register as usual with a username and password. Once registered, they have to add a FIDO2 token to successfully login afterwards. During the next login the username and password are verified. If correct, it continues with the WebAuthn stuff. This happens across two API endpoints (`/begin` and `/complete`).

In the `/complete` part I use `login_user` to perform the final login. For this to work I set `session["user_id"] = user.id` in `/begin` so I know which user has logged in.

The problem arise when I cancel the WebAuthn authentication at the client. `/begin` has already completed at this stage, so the `session["user_id"]...` part has been executed. When FIDO2-authentication is aborted though, I get redirected to the page where logged in users get redirected, __and__ I am authenticated.

I have added a debug-message to the `user_loader`, and apparently this gets called when the mentioned session-variable is set. However, this does not happen if instead of `user_id` I use some other string to identify the users ID within the session.

Since I'm new to Flask I don't know if I'm just doing something stupid there, or if this is actually something to look into. So I figured I rather share this in case it's a security issue.

**To Reproduce**
- Clone and run my project at https://github.com/danielperna84/hass-wh-triggers
- Register, add a FIDO2 token (on Windows 10 the integrated Windows Hello supports FIDO2)
- Logout, Login, Abort FIDO2 authentication
- Authentication failed (redirected to login view)
- Change `session["lid"] = user.id` to `session["user_id"] = user.id` [here](https://github.com/danielperna84/hass-wh-triggers/blob/fd4f49a1cbf578a8cfccbea9b1ceda715af4e45c/hass_wh_triggers/app.py#L527)
- Login, Abort FIDO2 authentication
- User gets authenticated and redirected to the triggers site (which has `login_required`)

**Expected behavior**
The name of a key in the session shouldn't impact authentication, or if so, it should be clearly documented (I did not find anything on this topic yet).

**Desktop (please complete the following information):**
 - OS: Windos 10
 - Browser Google Chrome
 - Version 79

**Comment by davidism** [comment]
Sounds like you've already discovered that you need to use a different key in the session to store the user id while you're completing authentication, and only set it to the `user_id` key once authentication has fully completed. So I guess this is just asking for documentation that `login()` sets the `user_id` key? PRs welcome.

**Comment by danielperna84** [comment]
To clarify: it is expected behaviour that `session["user_id"] = user.id` is equivalent to a successful authentication? If so, then yes, I think the documentation should mention this. I imagine there should be a list of reserved keys for `session` that should not be modified unless the dev knows what he is doing. Any hints at where in the code I should look to find out more about this. And even more importantly: is this a Flask-Login issue, or is it actually Flask itself?

**Comment by majonathany** [comment]
I also stumbled this and am a bit concerned. I just created the following route and then I am authenticated:

`
@app.route('/security_test', methods=['GET'])
def test():
    session["user_id"] = '5e384b62c3f136dd47e65b19'
    return render_template('success.html', title='Success')
`

Even though this is server-side, it would seem that this could be an server-side injection risk. Or would be very difficult for someone to inject such code into Flask Login?
