### ISSUE TITLE
Login redirections are not handled properly when behind a reverse proxy

### ISSUE THREAD

**Issue by ptitdoc** [maxcountryman/flask-login#467]
**Describe the bug**
When behind a proxy such as nginx, login redirection are not handled properly, requiring to tweak the application code or flask-login code.

This has been discussed in https://github.com/maxcountryman/flask-login/pull/371 where `FORCE_HOST_FOR_REDIRECTS` configuration can be used on the flask application or `X-Forwarded-For` or `Host` header is interpreted by flask `Flask.redirect` to fix the url.

However there is no way to fix the protocol or the initial path that is eventually set by a proxy. For instance `X-Forwarded-Proto` may be used or a flask app configuration `FORCE_URL_FOR_REDIRECTS` can be used and interpreted

**To Reproduce**
1. Run a flask app behind a reverse proxy that switch https to http or that use an initial PATH
2. Use flask-login to redirect to the login page
3. The app will be redirected to http when it is running on https from the user perspective

**Expected behavior**
Being able to force the protocol for redirections or initial path without having to change the flask application (eg: to implement a `HTTPFix` middleware)

**Additional context**
https://github.com/maxcountryman/flask-login/pull/371

**Comment by serkin** [comment]
The same issue
