### ISSUE TITLE
Rebuild documentation

### ISSUE THREAD

**Issue by multimeric** [maxcountryman/flask-login#474]
Thanks for the new release. However I've noticed that all the changes to the documentation included in 0.5.0 aren't yet visible on the website. In particular I'm thinking about the custom `test_client`, which is documented [here](https://github.com/maxcountryman/flask-login/blob/master/docs/index.rst#automated-testing) in the repo but not [here](https://flask-login.readthedocs.io/en/latest/) on the website.

**Comment by PanderMusubi** [comment]
Yes, please trigger a build for version 0.5.0 of the documentation.

**Comment by davidism** [comment]
@maxcountryman can you add me as a maintainer on Read the Docs? Username is davidism there too.

**Comment by davidism** [comment]
@maxcountryman looks like the RTD webhook isn't configured in the repository, and I can't add it because I don't have maintainer access. (I just tried adding you to one of my repos, and you're right, personal repos don't allow adding collaborators as maintainers :disappointed:)

**Comment by maxcountryman** [comment]
I added the webhook, lmk if that does it. Longer term I'm happy to look into moving this into an org like you suggested. :)

**Comment by davidism** [comment]
Seems like it didn't pick up any new tags or branches. I tried clicking "Resync webhook" but got "webhook activation failed".

**Comment by maxcountryman** [comment]
I'm getting a permissions error trying to resync the webhook.

**Comment by davidism** [comment]
Maybe try removing it and adding a new one? Might also have leftover old RTD integrations, I know they used to have a different way of registering.

**Comment by maxcountryman** [comment]
This was a brand new one. GH shows it delivered to it successfully so it might just be another RTD quirk; it appears to be correctly setup.

**Comment by davidism** [comment]
@davidfischer any idea how we could debug this? (or who I should ping instead?)

**Comment by davidfischer** [comment]
It does look like the latest build (on `main`) did not succeed: https://readthedocs.org/projects/flask-login/builds/16503881/. It looks like it tried to find `master`. There's an option in the settings to switch the main branch. I think it's supposed to autodetect but I think it doesn't autodetect automatically if you switch to it -- only for new repos.

**Comment by davidism** [comment]
Ah, must have been lagging a bit, I just checked again and now "main" is listed in the inactive versions section. It wasn't before so I couldn't select it.

**Comment by davidism** [comment]
The docs are now up to date, after the last build 3.5 years ago. I've also enabled builds on pull requests, with warnings treated as errors, to ensure the documentation continues to build.
