### ISSUE TITLE
Forcing `is_authenticated` True persistently 

### ISSUE THREAD

**Issue by crablab** [maxcountryman/flask-login#475]
My understanding of the documentation is that `is_authenticated` should be True when whatever authentication mechanism is used to actively authenticate the user and at no other time. The behavior I expected was: 

1. User enters username and password
2. User object created, credentials checked, `is_authenticated` becomes true
3. `login_user()` called and authenticated `user` objected passed
4. Redirect occurs
...
5. New instantiation of `user` as a `login_required` page is visited, `is_authenticated` is now false. Session cookie is checked, user ID validated etc. etc. and page loads 

What actually happens in step 5 is the user is treated as unauthorised, even though they were issued with a valid session cookie having been authenticated. 

In order to get the behavior I expect, I have to hard code `is_authenticated` to return True, regardless of whether the user just entered their password or not. 

Nowhere in the documentation does it say `is_authenticated` should be stateful. Does it exist purely to facilitate logout (eg. manually ending the session)? If so, I think it's a bit of a misnomer as that's more of a `session_enabled` or the like.

**Comment by alanhamlett** [comment]
Yes, the `is_authenticated` property on your User class should always return `True`. Its purpose is to distinguish "real" users from the `AnonymousUser` class, which always returns `False`.

**Comment by crablab** [comment]
@alanhamlett Thanks! I think it's worth looking at updating the documentation. This seems to be acting as a proxy for `AnnonymousUser` which is not intuitive. 

I would suggest either:
- Updating documentation to make clear what the expected behavior is   
- Changing the behavior so `AnnonymousUser` is checked to determine if a user is "real", instead of `AuthenticatedUser` 

I am happy to PR changes to the documentation, as the other option would be a breaking change.

**Comment by alanhamlett** [comment]
For sure, PRs improving docs are very welcome.
