### ISSUE TITLE
[documentation] Disabling Session Cookie for APIs leads to deprecated function header_loader

### ISSUE THREAD

**Issue by guysoft** [maxcountryman/flask-login#478]
In the file:

https://github.com/maxcountryman/flask-login/blob/master/docs/index.rst

There is the line:
```
This prevents setting the Flask Session cookie whenever the user authenticated
using your `~LoginManager.header_loader`.
```
Which leads to header_loader.

But in header loader the docs say:

```
 header_loader(callback)[source]

    This function has been deprecated. Please use LoginManager.request_loader() instead.
```

Located at:
https://github.com/maxcountryman/flask-login/blob/master/flask_login/login_manager.py#L287

I am not sure how to use it (that is why I was looking in the docs in the first place), so I am not sure what a PR should include.

**Comment by guysoft** [comment]
Found how to do this in the end with this minimal example:
http://gouthamanbalaraman.com/blog/minimal-flask-login-example.html
Perhaps something like that might help other people with this issue.

**Comment by guysoft** [comment]
Can someone point me where the doc is to PR?

**Comment by icyphox** [comment]
@guysoft I couldn't really see how to solve it from the blog you've linked. Can you explain what you did?

**Comment by icyphox** [comment]
I figured it out. 


```python
from flask.sessions import SecureCookieSessionInterface
from flask import g
from flask_login import user_loaded_from_request

@user_loaded_from_request.connect
def user_loaded_from_request(app, user=None):
    g.login_via_request = True


# This prevents creation of a session cookie, since we use tokens
class CustomSessionInterface(SecureCookieSessionInterface):

    def should_set_cookie(self, *args, **kwargs):
        return False

    def save_session(self, *args, **kwargs):
        if g.get("login_via_request"):
            return
        return super(CustomSessionInterface, self).save_session(*args, **kwargs)


app.session_interface = CustomSessionInterface()
```

**Comment by icyphox** [comment]
Perhaps this should be added to the docs.

**Comment by guysoft** [comment]
@icyphox I agree, thats why I opened the issue :)
The fact you had to figure it out means its not trivial and should be documented.
Who should add it between us?

**Comment by icyphox** [comment]
> Who should add it between us?

I've already created a PR (#514). :)
