### ISSUE TITLE
keyerror when accessing session variable after upgrading from 0.4.1 to 0.5.0

### ISSUE THREAD

**Issue by avijit1258** [maxcountryman/flask-login#481]
**Describe the bug**
My flask application using flask-login 0.4.1 worked fine for me in my test server. However, when I migrated to a development server, I get keyerror 'user_id' not found in session. I was surprised why this error is given as same code is working fine in my test server. Later, after my investigation I found that my production server is using flask-login 0.5.0 which updated some default values which caused the error. So, I down-graded flask-login version to 0.4.1 and restarted the apache server which worked fine my application then.

**Comment by AmirMohammad2003** [comment]
user id session key is `_user_id` not ``user_id
