### ISSUE TITLE
Logout inactive user

### ISSUE THREAD

**Issue by giuppep** [maxcountryman/flask-login#486]
**Describe the bug**
The `@login_required` decorator does not check if a user is active. I'm not sure if this was a design choice, but intuitively I would expect to be able to log a user out by deactivating it.
 
**To Reproduce**
1. Create a user
2. Login with that user
3. Set `user.is_active = False`
4. User is still able to access view decorated with `@login_required`

**Expected behavior**
Intuitively I would expect this line in the `@login_required` decorator
```python
elif not current_user.is_authenticated:
    return current_app.login_manager.unauthorized()
```
to read
```python
elif not (current_user.is_authenticated and current_user.is_active):
    return current_app.login_manager.unauthorized()
```

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser [e.g. chrome, safari]: N/A
 - Version [e.g. 22]: 0.4.1 (I think it came as a dependency from `flask-security`)

**Additional context**
Again, not sure whether it is a genuine bug or a misunderstanding from my side. 
We could get around it on our side by overriding `user.is_authenticated` in our `User` class to return `super().is_authenticated and self.is_active`.

Addressed in #489

**Comment by WaizungTaam** [comment]
Setting a logged-in user inactive is meaningless. `is_active = False` prevents inactive users from logging in, and `login_user()` is doing the job.

To inactivate an already logged-in user, logout first, and then set `is_active = False` to prevent it from logging in again.

**Comment by giuppep** [comment]
Thanks for the comment. 

My idea was that one should be able to easily logout a user server-side. While what you said is `True`, I can't force a user to log out so that they won't be able to login again. Is there another way of achieving this?

**Comment by WaizungTaam** [comment]
`logout_user()` can logout the current user on the server-side.

**Comment by giuppep** [comment]
yeah, sure, but the user will have to navigate to a view where `logout_user()` is used, no?

Scenario is the following: we have a flask app with passwordless login. User X logs in and starts using the app. Now, for whatever reason, I want to disable their user with immediate effect, i.e. I do not want them to access any view that is decorated with `@login_required`. How would you achieve that with `logout_user()`?

**Comment by WaizungTaam** [comment]
Just return `None` in the `login_manager.user_loader` for the target users. You can use extra data field in database or cache to achieve this.

**Comment by giuppep** [comment]
That does not sound like a very practical solution IMO. 

As said in OP, I easily solved the issue on my side by overriding the `is_authenticated` property in my `User` class. I  just thought it could be useful to implement this by default in the library.

**Comment by alanhamlett** [comment]
If `@login_required` checks the `User.is_active` property it leads people to not check `is_active` in their `is_authenticated` method. That leads to inactive users still able to access resources requiring login when manually checking `current_user.is_authenticated`. Instead, we'll update [UserMixin.is_authenticated](https://flask-login.readthedocs.io/en/latest/_modules/flask_login/mixins.html#UserMixin) to:

```Python
@property
    def is_authenticated(self):
        return self.is_active
```

**Comment by giuppep** [comment]
Fair point @alanhamlett, that seems like a better solution!
