### ISSUE TITLE
[documentation] Dead link in Login Example

### ISSUE THREAD

**Issue by frainfreeze** [maxcountryman/flask-login#490]
Login example [snippet](https://flask-login.readthedocs.io/en/latest/#login-example) tells us to use `is_safe_url` function, provided on http://flask.pocoo.org/snippets/62/. Sadly the url is dead.

Url can be found on wayback machine [here](https://web.archive.org/web/20190128010142/http://flask.pocoo.org/snippets/62/) and snipper code in github repo [here](https://github.com/fengsp/flask-snippets/blob/master/security/redirect_back.py).

**Comment by andrew-womeldorf** [comment]
This was fixed in [dc6103ac](https://github.com/maxcountryman/flask-login/commit/dc6103ac). It doesn't look like the readthedocs site has been updated, though :(
