### ISSUE TITLE
get by id didn't work (tested by self and professor and class)

### ISSUE THREAD

**Issue by Grigoletti2001** [maxcountryman/flask-login#493]
**Describe the bug**
In "How it works section" get (user_id) needs to be changed to get by id(user_id) in order for code to work. 

**To Reproduce**
run the example in the docs in any project, the try it with get by id. 

**Expected behavior**
to get user id info. 
**Screenshots**
attached. 
![Screen Shot 2020-04-28 at 1 09 25 PM](https://user-images.githubusercontent.com/4676859/80522604-74e96d80-8952-11ea-8139-ff2e52e40402.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.4
 - Browser :Chrome
 - Version :80.0.3987.163 (Official Build) (64-bit)

**Smartphone (please complete the following information):** NA

**Additional context**

**Comment by davidism** [comment]
The code you're pointing at is an example, not geared towards a specific database. It sounds like you're using Mongo, so yes, you need to use `get_by_id` to get by id, whereas SQLAlchemy users use `get`.
