### ISSUE TITLE
Redirect doesn't work with directory prefix

### ISSUE THREAD

**Issue by potem** [maxcountryman/flask-login#494]
Flask is accessed via domain.tld/directory/ and nginx has a hook for "location /directory/ { proxy_pass ...}", the moment I include `@login_required` into my code I'm getting redirected to domain.tld and not domain.tld/directory/login or something.

    @app.route('/login')
    def login_handler():
        # do login stuff

    @app.route('/')
    @login_required
    def index_handler():
        # do content stuff`

the debugger says:
`192.168.62.2 - - [07/May/2020 07:10:34] "GET / HTTP/1.1" 302 -`

There seems to be an issue with the redirect, is there a way to fix this or pass the directory to flask-login and prepend it to the redirected uri?

both flask and flask-login running latest versions.

**Comment by XxSamixX123** [comment]
Hi. Sorry if I'm a bit late on this one.
Did you configure the login_manager.login_view ?

For example what I did in my latest project was:
login_manager = LoginManager()
login_manager.login_view = 'users.login'

Then of course I initialized the app with the login manager...
