### ISSUE TITLE
Inactive users pass the @login_required check

### ISSUE THREAD

**Issue by gergelypolonkai** [maxcountryman/flask-login#496]
**To Reproduce**
1. Login with a user account (thus, acquiring a valid login session)
2. Disable the account (e.g. setting the `is_active` flag to `False`)
3. Open a view protected with `@login_required`
4. The view executes as if the user was still active

**Expected behavior**
The user should not access protected views.

-----

It’s easy to workaround this problem by overriding the default `is_authenticated` property of `UserMixin`:

```python
class User(UserMixin):
    @property
    def is_authenticated(self):
        return self.is_active
```

**Comment by davidism** [comment]
Fixed by #530
