### ISSUE TITLE
Login_required reveals 405 method not allowed

### ISSUE THREAD

**Issue by lsabi** [maxcountryman/flask-login#498]
**Describe the bug**
An URL with POST as the only allowed method and login_required, reveals that that URL is valid and returns a 405 status code instead of redirecting to the login page.

**To Reproduce**
```
@bp.route("/myurl", methods=["POST"])
@login_required
def myurl():
    print("HI")
    return ""
```

**Expected behavior**
To be asked to log in or something, as configured in the setup of the extension.

**Screenshots**
The classic 405 method not allowed of flask.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: firefox
 - Version: 76.0.1 (64-bit)

**Smartphone (please complete the following information):**
I'm not using a smartphone.

**Comment by davidism** [comment]
Flask routing happens before the view function runs (because routing is what finds the function). Checking the method is part of routing.

**Comment by lsabi** [comment]
I was expecting that as the reason, but isn't it a security issue for exposing information about methods and URLs?
