### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by davidism** [maxcountryman/flask-login#506]
Just did this with all the Pallets projects and am really happy with the results. Actions gives 10 workers compared to 5 from Travis, and seems to generally be faster. Another thing slowing down our tests is that the suite waits to run twice for PRs made from repo branches, such as Dependabot. Both Travis and Actions have a way to limit running tests to only the main branches.

**Comment by maxcountryman** [comment]
I'm definitely in favor of this.

**Comment by maxcountryman** [comment]
Another benefit would be if we could integrate publishing to PyPI then releases could happen a lot faster (e.g. say they're triggered on tagging).
