### ISSUE TITLE
Drop Python 2 support?

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/flask-login#508]
As many of us are aware, Python 2 has officially been retired. While there are no doubt plenty of projects that haven't migrated, there's never been a better time to call it.

Any opposition to removing Python 2 from our test suite and no longer officially supporting it in this project?

**Comment by davidism** [comment]
I've dropped Python 2 and 3.5 from all Pallets projects, as well as WTForms, new major releases coming in the next few months.
