### ISSUE TITLE
Rename github master branch to main

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/flask-login#515]
Rename github master branch to main.

**Comment by davidism** [comment]
Make sure to point all open pull requests at the new branch before deleting the old one, otherwise GitHub will automatically close them in a way that's hard to undo. I think their `gh` CLI has something for that, and they're working on a broader fix for it too.

**Comment by maxcountryman** [comment]
I've updated the default branch to `main`, but I haven't migrated the outstanding PRs.
