### ISSUE TITLE
Add REMEMBER_COOKIE_SAMESITE cookie setting

### ISSUE THREAD

**Issue by BitPhoenix** [maxcountryman/flask-login#516]
What I'm trying to do: set the SameSite attribute on the remember cookie in accordance with a Chrome change

> To safeguard more websites and their users, the new secure-by-default model assumes all cookies should be protected from external access unless otherwise specified. Developers must use a new cookie setting, SameSite=None, to designate cookies for cross-site access. When the SameSite=None attribute is present, an additional Secure attribute must be used so cross-site cookies can only be accessed over HTTPS connections. This won’t mitigate all risks associated with cross-site access but it will provide protection against network attacks.
https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

I'm able to do this for the session cookie using 
`app.config['SESSION_COOKIE_SAMESITE'] = "None"`

And I can do this for a cookie I create myself like this 

`response.set_cookie("mycookie", "I am cookie", secure=True, httponly=True, samesite="None")`

I was wondering if it would be possible to add this cookie setting so that I can set the attribute on the remember cookie?

**Comment by alanhamlett** [comment]
Was added with #453, it's just not released to pypi yet.

**Comment by alanhamlett** [comment]
You can install the latest version straight from github with:

`pip install -e git://github.com/maxcountryman/flask-login.git@c073d3bdeceb2a9c280c421f57c9770ffd9f183a#egg=Flask-Login`

**Comment by maxcountryman** [comment]
If someone wants to set up releases through GH Actions I'd be happy to provide the token for that.
