### ISSUE TITLE
Disable next parameter

### ISSUE THREAD

**Issue by axc450** [maxcountryman/flask-login#524]
I am working on a simple application. Once logged in, the user is redirected to the homepage (there isn't even another page at the moment). All this works perfectly, however I do not see a way to disable the "next" parameter. I do not check it nor use it in any way, yet it still gets appended to my URLs. A simple `login_manager.next_parameter = False` should do the trick! 🙂

**Comment by alanhamlett** [comment]
Redirecting happens in your code not Flask-Login. You should just not redirect after login.
