### ISSUE TITLE
Logout a specific user

### ISSUE THREAD

**Issue by CesMak** [maxcountryman/flask-login#532]
Hey there,

I would like to logout a user that is inactive which means that this user has not clicked a button or something on the website for 5min. To achieve this I stored a last_clicked entry for each user in my db and I use `from flask_apscheduler import APScheduler ` to check inactivity of the users. This all works fine. 

However I am not able to use flask_logins `logout_user` for a specific user.....

Is there another / better way to achieve the above functionality using session cookies etc.?

Is it somehow possible to logout a specific user using a background process?

The code I currently use is:
```python
def check_inactivity():
    print("\n\nCHECK_INACTIVITY\t:")
    with db.app.app_context():
        users = User.query.all()
        for user in users:
            if user.is_enabled and not user.is_admin:
                td_last_visit =  datetime.now()-user.last_visit
                print("\t-"+str(user.username)+" is inactive for "+str(td_last_visit.seconds))
                if td_last_visit.seconds>15: 
                    user.is_enabled = False # user is not active anymore!
                    db.session.commit()
                    #logout_user()#does not work here!
                    print("\t-"+str(user.username)+" is inactive for "+str(td_last_visit.seconds))
                    #return redirect(url_for('users.logout'))#does also not work here
```

**Comment by alanhamlett** [comment]
Questions about how to use Flask-Login should be asked on StackOverflow, since this question won't result in any code change:

https://stackoverflow.com/search?q=flask-login
