### ISSUE TITLE
CSRF Protection

### ISSUE THREAD

**Issue by NMO13** [maxcountryman/flask-login#533]
Is flask-login vulnerable to CSRF attacks and if yes, how can that be mitigated?

**Comment by alanhamlett** [comment]
Flask-Login is not vulnerable to CSRF because that's not related to auth. CSRF is for any form submit across your whole site, not just login. These are good libraries to use for CSRF:

https://flask-seasurf.readthedocs.io/en/latest/
https://pythonhosted.org/Flask-Security/
