### ISSUE TITLE
Not Working in chrome

### ISSUE THREAD

**Issue by myounus96** [maxcountryman/flask-login#545]
**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version : Latest one as of today.

Working fine in Firefox, so is there any specific configuration for chrome..?

**Comment by myounus96** [comment]
another finding is when frontend and backend both on localhost(I would say same domain) its working fine with chrome.

**Comment by myounus96** [comment]
> i have the same issue, did you find any solution?
> thanks

Nop, I reimplemented login feature with JWT without any flask library and its working fine.

**Comment by eagerman** [comment]
the issue was not in flask-login but a CSRF validation error
https://nickjanetakis.com/blog/fix-missing-csrf-token-issues-with-flask
in my case i had SESSION_COOKIE_SECURE set to True while i still did not have an ssl certificate installed, so i just had to set it to False

**Comment by davidism** [comment]
Closing as there is not enough information to debug.
