### ISSUE TITLE
@login_required decorator is redirecting to login page even if the user is already logged in

### ISSUE THREAD

**Issue by Zlopez** [maxcountryman/flask-login#546]
**Describe the bug**
I'm using `@login_required` decorator for some pages on release-monitoring.org and even if the user is already logged in it's redirected to login page and it needs to log in again. Unfortunately the redirection to authentication server is messing with POST requests and calls GET instead.

**To Reproduce**
1. Go to release-monitoring.org
2. Click on `login` in header (this will redirect you to login page, you need a valid openid login)
3. When logged in click on `settings` page (You will be again redirected to login page)

**Expected behavior**
The Settings page should be displayed without the need to login again

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Browser Firefox (flatpak)
 - Version 81.0.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidism** [comment]
I'm sorry, we can't help you debug your live website. I can't reproduce this issue locally. If you can, please update with a self-contained code example.

**Comment by Zlopez** [comment]
Tested with other browser:
* OS: Fedora 33
* Browser: Eolie (flatpak)
* Version: 0.9.63

This time it's working, so it could be only with Firefox.
