### ISSUE TITLE
Redirect if Authenticated

### ISSUE THREAD

**Issue by yespbs** [maxcountryman/flask-login#555]
Just like login_manager.login_view which redirects to /login from @login_required decorator
could we have a login_manager.home_view which redirects to user home page when /login is called with an authenticated session?

Just reverse of login_manager.login_view but for /login only, a callback kinda thing

**Comment by davidism** [comment]
Flask-Login can't do this automatically unless the login route is already registered before the extension is initialized for the app. Even then, it would have to dig into things that are fairly internal to Flask. Alternatively, it could add a `before_request` handler to inspect ever request to see if it's the login endpoint, but that would add an unreasonable amount of overhead for this feature. Instead, add the following two lines to your login view:

```python
if current_user.is_authenticated:
    return redirect(url_for("index"))
```

**Comment by yespbs** [comment]
thats exactly I was doing but looking for a cleaner approach, like @login_required, a @redirect_authenticated decorator. thanks for your attending the topic.
