### ISSUE TITLE
getting this error ImportError: cannot import name 'UserMixin' from 'flask_login' 

### ISSUE THREAD

**Issue by Reshaniresh** [maxcountryman/flask-login#560]
**Describe the bug**
Am using python 3.8 ,and installed flask-login by the following command

` pip3 install flask-login`  but still facing the same issue

```
from flask import Flask, render_template, request, session,abort

from flask_login import UserMixin

from flask_sqlalchemy import SQLAlchemy
```

```
 from flask_login import UserMixin
ImportError: cannot import name 'UserMixin' from 'flask_login'
```

**Comment by davidism** [comment]
I can't reproduce this issue on the latest code or the latest release (0.5.0). When reporting an issue, be sure to include a minimal reproducible example, including the full traceback. However, this is most likely an issue with your environment in some way, so closing this.
