### ISSUE TITLE
Session Protection incorrectly invalidates sessions where the session cookie has no `_id` field.

### ISSUE THREAD

**Issue by twnk** [maxcountryman/flask-login#569]
Session Protection is designed to prevent a session cookie being captured and replayed to the server. If a session cookie is presented to the server with an `_id` (hash of IP+UA) that does not match the actual IP + User Agent of the browser presenting it, Session Protection invalidates the session and causes the user with the (presumed) stolen cookie to become logged out. 

Session Protection should never be triggered if an `_id` field is not present in the session cookie, because this would imply that someone is attempting to literally **impersonate nobody**. 

However, if an application using Flask Login has an Anonymous User class that includes other data in the session cookie, rather than this being evaluated along the code-path suggested by the comment `# if the sess is empty, it's an anonymous user or just logged out`, it evaluates the session protection. This causes issues with apps that use flask-login and reverse-proxy header authentication, as the `# Load user from Remember Me Cookie or Request Loader` code is never run due to failing strong session protection. 

```python
    def _session_protection_failed(self):
        sess = session._get_current_object()
        ident = self._session_identifier_generator()

        app = current_app._get_current_object()
        mode = app.config.get('SESSION_PROTECTION', self.session_protection)

        if not mode or mode not in ['basic', 'strong']:
            return False

        # if the sess is empty, it's an anonymous user or just logged out
        # so we can skip this
        if sess and ident != sess.get('_id', None):
            if mode == 'basic' or sess.permanent:
                sess['_fresh'] = False
                session_protected.send(app)
                return False
            elif mode == 'strong':
                for k in SESSION_KEYS:
                    sess.pop(k, None)

                sess['_remember'] = 'clear'
                session_protected.send(app)
                return True

        return False
```

https://github.com/maxcountryman/flask-login/blob/fd7984cd645c1e7c34c6af53b0571f7380b17cc3/flask_login/login_manager.py#L362

I would suggest modifying `if sess and ident != sess.get('_id', None):` to `if sess and '_id' in sess and ident != sess.get('_id', None):` to account for the possibility of an `_id`-less session cookie still existing for anonymous or logged out users.

**Comment by twnk** [comment]
Alternatively, if you can confirm that session cookies should never be utilised for anonymous or logged-out users, this would helpful, as that would mean this is definitively related to Calibre-Web's implementation of Anonymous Users.

**Comment by PoshAlpaca** [comment]
I'm getting this same issue when running tests on a `@fresh_login_required` view using `FlaskLoginClient` because it doesn't set `_id` in the session leading to the session being marked as non-fresh.
