### ISSUE TITLE
Flask-Login needs update to work with Flask 2.0

### ISSUE THREAD

**Issue by mosesontheweb** [maxcountryman/flask-login#587]
Hi,

Flask 2.0 was just released and I'm pretty excited to start use it. One thing I recognized is, that calls from extensions have changed. According to the docs from Flask a decorator should now use this method:
`return current_app.ensure_sync(func)(*args, **kwargs)`

See https://flask.palletsprojects.com/en/2.0.x/async-await/#extensions for further details.

Regards, Thomas

**Comment by davidism** [comment]
You only need to do this if you support async callbacks, which flask-login does not. Existing behavior will continue to work without it.

**Comment by mosesontheweb** [comment]
But what if I'd like to cover a coroutine which may need a valid login? The extension won't work, from my point of view.

**Comment by davidism** [comment]
Yes it will. If you want an async `@login_manager.user_loader` then we'd need to wrap things, but it has nothing to do with using loaded data in async views.

**Comment by mosesontheweb** [comment]
I did not mean the user loader. What about something like:
```python
@app.get('/some/path')
@login_required
async def somefunc():
    ...
```

**Comment by TheTechRobo** [comment]
Right now I'm relying on async. Are there any plans to add support for it?

If not I guess I'm searching for another library :/
