### ISSUE TITLE
Make certain routes available only for request_loader users

### ISSUE THREAD

**Issue by Virusmater** [maxcountryman/flask-login#591]
I'm using flask-login with flask-WTF for CSRF protection. Now I want to make few new routes and expose them as REST API. Since request_loader auth will be used for REST API (header token, no cookies) - I will disable CSRF on those routes.
But since Flask makes no difference between users once they are authenticated - the same REST APIs without CSRF will be automatically available for regular user_loader cookie based users.
Is it possible to make certain routes available only from request_loader users?
Or maybe I'm going to complete wrong direction here?

**Comment by davidism** [comment]
See https://github.com/wtforms/flask-wtf/issues/453.
