### ISSUE TITLE
Login stops after tab is close

### ISSUE THREAD

**Issue by nbravulapalli** [maxcountryman/flask-login#618]
**Describe the bug**
 Currently, the user remains logged in when navigating across different parts of my website in a single tab, but when a new tab is opened, or the current tab is closed and then opened, the user is no longer logged.

How am I supposed to keep the use logged in between various browser tabs with flask-login?

**Comment by Sadashii** [comment]
Switching to a new browser tab is equivalent to actually closing the old session and creating a new session, the way with which you can stop that is by passing `remember=True` when you call login_user(...).

[flask_login.login_user(...)](https://flask-login.readthedocs.io/en/latest/#flask_login.login_user)

@nbravulapalli
