### ISSUE TITLE
Document's code doesn't work

### ISSUE THREAD

**Issue by tobylai-toby** [maxcountryman/flask-login#631]
**Describe the bug**
```html
{% if current_user.is_authenticated %}
  Hi {{ current_user.name }}!
{% endif %}
```
I tried to use `{{ current_user.uid }}` instead of `{{ current_user.name }}`

This is what I used:
`/user/{{ current_user.uid }}`

I checked my page in the developer tool,
and I found out there was only `/user/` left

**To Reproduce**

html:
```html
{% if current_user.authenticated %}
<a href="/login" class="mdui-btn">login/register</a> {% else %}
<a href="/user/{{ current_user.uid }}"><img src="/avatar/{{ current_user.uid }}" alt="avatar"></a>
{% endif %}
```
User model:
```python
class User(UserMixin,db.Model):
    uid = db.Column(db.Integer, primary_key=True,autoincrement=True)
    has_avatar=db.Column(db.Boolean,default=0)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(120), unique=False, nullable=False)
    blogData = db.relationship("Blog", backref="user", uselist=False)
    confirmed = db.Column(db.Boolean,default=False)

    def __repr__(self):
        return '<User %r>' % self.username

    def change_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def is_active(self):
        return True

    def get_id(self):
        return str(self.uid)
```

**Versions**
I tried both v0.5.0 and v0.4.1
they act the same

(Well, my English is bad...)

**Comment by rafaVls** [comment]
Hi! Under your html you have

```html
{% if current_user.authenticated %}
```

I believe it should be
```html
{% if current_user.is_authenticated %}
```

I don't know if this is a typo just on your issue text, or if this is also present in your code. Also, I'm not sure if this would affect ```current_user.uid```, but it's worth checking it out.

**Comment by tobylai-toby** [comment]
> Hi! Under your html you have
> 
> ```
> {% if current_user.authenticated %}
> ```
> 
> I believe it should be
> 
> ```
> {% if current_user.is_authenticated %}
> ```
> 
> I don't know if this is a typo just on your issue text, or if this is also present in your code. Also, I'm not sure if this would affect `current_user.uid`, but it's worth checking it out.

thanks, i think it worth a try

**Comment by tobylai-toby** [comment]
```html
{% if current_user.is_authenticated %}
<a href="/user/{{ current_user.uid }}"><img src="/avatar/{{ current_user.uid }}" alt="avatar"></a> 
{% else %}
<a href="/login" class="mdui-btn">login or register</a> 
{% endif %}
```
I logged in and the cookies are right.
but it still shows  me "login or register"

**Comment by rafaVls** [comment]
What does your user_loader look like? It should be something similar to this:
```python
@login_manager.user_loader
def load_user(user_id):
  return Player.query.get(str(user_id))
```

Also, where are you logging in your user? As in, where are you calling the `login_user` function from `flask_login`?

**Comment by tobylai-toby** [comment]
> What does your user_loader look like? It should be something similar to this:
> 
> ```python
> @login_manager.user_loader
> def load_user(user_id):
>   return Player.query.get(str(user_id))
> ```
> 
> Also, where are you logging in your user? As in, where are you calling the `login_user` function from `flask_login`?

```python
@login_manager.user_loader
def load_user(uid):
    return User.query.filter_by(uid=int(uid))
```

**Comment by tobylai-toby** [comment]
> What does your user_loader look like? It should be something similar to this:
> 
> ```python
> @login_manager.user_loader
> def load_user(user_id):
>   return Player.query.get(str(user_id))
> ```
> 
> Also, where are you logging in your user? As in, where are you calling the `login_user` function from `flask_login`?

thanks, i found out my bugs.
`User.query.filter_by(uid=int(uid))` should be `User.query.filter_by(uid=int(uid))[0]`

**Comment by rafaVls** [comment]
Nice! I'm glad you fixed it. Just for reference, the "correct" way to write that line is either

```python
User.query.get(int(uid))
```

or

```python
User.query.filter_by(uid=int(uid)).first()
```
