### ISSUE TITLE
Flask-login will call function multiple times if the wrapped function raises an unhandled AttributeError

### ISSUE THREAD

**Issue by PythonCoderAS** [maxcountryman/flask-login#666]
If the wrapped function raises an unhandled AttributeError, the try-except logic will call the function again, leading to potentially undesired side effects depending on what the function did.

https://github.com/maxcountryman/flask-login/blob/ecd3b59339175e575ba598eb5c5fd3330e0ff73b/src/flask_login/utils.py#L299-L303

**Comment by PythonCoderAS** [comment]
A possible solution would be #660/#662.

**Comment by FrankyBoy** [comment]
#667 is the merge request

**Comment by alanhamlett** [comment]
Fixed with #667.
