### ISSUE TITLE
user_loader receives a string when loading from remember me cookie instead of original object

### ISSUE THREAD

**Issue by michaels-atbay** [maxcountryman/flask-login#673]
**Describe the bug**
When overriding get_id to return an object (dictionary), session cookie is loaded and calls user_loader with the object, but remember me cookie is loaded and called with a literal string of the object.

**To Reproduce**
    
    from flask_login import UserMixin
    login_manager = LoginManager()

    class User(UserMixin):
        def __init__(self, id_, email):
            self.id_ = id_
            self._email = email
    
        def get_id(self):
            return {
                'id_': self.id_,
                'email': self._email,
            }
    
    @login_manager.user_loader
    def load_user(user_id):
        return User(**user_id)

user_id (when loaded from session cookie): `{_id: '123', email: 'example@gmail.com'}`
user_id (when loaded from remember me cookie): `"{_id: '123', email: 'example@gmail.com'}"`

**Expected behavior**
user_id from remember me cookie should behave the same as the session cookie, or document otherwise.

**Comment by alanhamlett** [comment]
The [docs](https://flask-login.readthedocs.io/en/latest/#your-user-class) say `get_id()` must return a `str` not a `dict`.
