### ISSUE TITLE
2nd attempt - every session becomes a remember session when REMEMBER_COOKIE_REFRESH_EACH_REQUEST is set

### ISSUE THREAD

**Issue by elandorr** [maxcountryman/flask-login#684]
Why was #424 closed? It still is broken. A fix was provided in https://github.com/maxcountryman/flask-login/issues/424#issuecomment-579913346 2.5 years ago.

When will you incorporate this?

**Comment by davidism** [comment]
The lead maintainer of this package decided to close old issues. If this issue is important to you, please submit a PR.
