### ISSUE TITLE
don't look at the `X-Forwarded-For` header

### ISSUE THREAD

**Issue by davidism** [maxcountryman/flask-login#700]
Flask-Login has no way to guarantee that this header is correct because it doesn't know how many proxies the app is or isn't deployed behind. Instead, it should always read `request.remote_addr`, and assume that the user has configured `ProxyFix` if necessary.

**Comment by lavish** [comment]
Absolutely agree with this one. I also noticed it 2 days ago while checking the code base of Flask-Login for https://github.com/maxcountryman/flask-login/pull/677 and wanted to report it. 

Reading the IP address from the `X-Forwarded-For` header makes the session `_id` generated via `_create_identifier()` spoofable by an attacker. Assume that an attacker can lure the user to visit a page under the attacker's control, discovering the user's IP address and user agent. The attacker can then establish a session with a flask website with the same `_id` of the victim by doing the following:
1) change the `User-Agent` header to be equivalent to the one of the victim;
2) spoof the IP of the victim via the `X-Forwarded-For` header.

If the attacker is in the position to set cookies in the victim's browser (e.g., a same-site attacker), then the additional protection provided by setting `app.config["SESSION_PROTECTION"] = "strong"` is voided allowing e.g., session swapping.
