### ISSUE TITLE
Still incompatible with Werkzeug 2.2.0 (cannot import 'parse_rule')

### ISSUE THREAD

**Issue by MajorDallas** [maxcountryman/flask-login#702]
**Describe the bug**
Same as #688 

**To Reproduce**
1. `pip install flask==2.1.3 werkzeug==2.2.0 flask-login==0.6.2`
2. `flask shell`

**Expected behavior**
Installing 0.6.2 should resolve the import error.

**Desktop (please complete the following information):**
 - OS: Debian 11

**Additional context**
The same import error occurs: `ImportError: cannot import name 'parse_rule' from 'werkzeug.routing'`

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided.

```
$ pip install flask==2.1.3 werkzeug==2.2.0 flask-login==0.6.2
$ python
>>> from flask_login import LoginManager
# no error
```
