### ISSUE TITLE
no logged in user when using `FlaskLoginClient` with `freezegun.freeze_time`

### ISSUE THREAD

**Issue by theendlessriver13** [maxcountryman/flask-login#712]
**Describe the bug**
The `FlaskLoginClient` for testing does not work as expected when the test is decorated with `@freeze_time`like this:
```python
from freezegun import freeze_time

@freeze_time('2021-05-18 19:00:00')
def test_something(client):
    rv = client.get('/test')
```
also when using a context manager:
```python
from freezegun import freeze_time

def test_something(client):
    with freeze_time('2021-05-18 19:00:00'):
        rv = client.get('/test')
```
When removing the time freeze in my test route I get an user as expected
```python
@data.route('/test')
def test() -> Response:
    print(request.cookies)
    print(current_user)
```
```console
SystemUser(id=73, username='test_user', email='test_user@example.com', password_hash='**', api_keys=[])
```
with the time freeze in place I get an anonymous user:
```python
<flask_login.mixins.AnonymousUserMixin object at 0x7f7eeac06740>
```
Looking at `request.cookies`, I can see that a session cookie is set, but I am assuming that due to the time shift, the cookie is already expired or not valid yet.
```python
ImmutableMultiDict([('session', 'eyJfZnJlc2giOnRydWUsIl91c2VyX2lkIjoiNzQifQ.Y1Vz1A.ACuEVkGic1XA8D_Pb4q7FYyi9q0')])`
```
I would expect to have a user logged in when using the `FlaskLoginClient` even with the time freeze in place.

Do you maybe have any advice for a workaround or can this somehow be fixed by setting the session cookie differently? I am using the time freeze, because my API takes a `days` param which is relative to the current date and time. With the sample data in the database I need to mock the current time to check that I get data as expected.

The problem exists with mocking times in the past and in the future. If the time is close to the actual current time, it works fine, hence I expect the cookie expiration to be the issue ?!

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Browser: NA
 - Version NA
 - Testing with `pytest`

**Additional context**
Installed packages
 ```console
 (venv) $ pip freeze | grep -iE "flask|freezegun"
Flask==2.2.2
Flask-Login==0.6.2
Flask-SQLAlchemy==3.0.0a1
Flask-WTF==1.0.1
freezegun==1.2.2
```

**Comment by davidism** [comment]
You'll need to create the client inside the test. Pytest evaluates fixtures before it evaluates the test functions, so `freeze_time` hasn't run yet.
