### ISSUE TITLE
regenerate & push latest ReadTheDocs documentation

### ISSUE THREAD

**Issue by pwillis-eiq** [maxcountryman/flask-login#716]
**Describe the bug**
The documentation on the ReadTheDocs website is out of date.

There was a broken link that was fixed in 2019 (https://github.com/maxcountryman/flask-login/commit/dc6103ac), but the ReadTheDocs website still has the old link (https://flask-login.readthedocs.io/en/latest/#login-example).

The latest docs should be regenerated/pushed to ReadTheDocs to resolve the bug.

**To Reproduce**
1. Go to https://flask-login.readthedocs.io/en/latest/#login-example
2. Click on 'this Flask Snippet' link
3. See error

**Expected behavior**
Link should go to https://web.archive.org/web/20120517003641/http://flask.pocoo.org/snippets/62/

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version

**Comment by pwillis-eiq** [comment]
Fyi, the dead link is talked about in [this StackOverflow answer](https://stackoverflow.com/questions/60532973/how-do-i-get-a-is-safe-url-function-to-use-with-flask-and-how-does-it-work)

**Comment by PanderMusubi** [comment]
1. See https://github.com/maxcountryman/flask-login/pull/717 (or is better to point to version 2.2.x?)
2. another PR that changes https://github.com/maxcountryman/flask-login/blob/main/docs/conf.py#L234 https://flask.palletsprojects.com/en/2.2.x/
3. another PR that changes https://github.com/maxcountryman/flask-login/blame/main/docs/index.rst#L649 to point to https://stackoverflow.com/questions/60532973/how-do-i-get-a-is-safe-url-function-to-use-with-flask-and-how-does-it-work and also use that in https://github.com/maxcountryman/flask-login/blame/main/docs/index.rst#L140 as the archived link is not getting improved answers over time and the post on stackoverflow is

**Comment by davidism** [comment]
Seems to be building fine.
