### ISSUE TITLE
current_user is not reload between workers

### ISSUE THREAD

**Issue by raimonesteve** [maxcountryman/flask-login#728]
Flask-Login not share current_user in Flask 2.2 with multiples workers

Versions:

```
Werkzeug==2.2.2
Flask==2.2.2
Flask-Login==0.6.2
gunicorn==20.1.0
```

We detect that **current_user** is not reload between workers.

Maybe is related to '_request_ctx_stack' is deprecated and will be removed in Flask 2.3. 

Since https://github.com/maxcountryman/flask-login/commit/359fb004f153635952a7d32ded1bbd6d74ec2561 current_user is from g._login_user. But, In case you run your flask app with differents workers, in some cases "_get_user" is anonymous and other cases,  is the user.

Gunicorn command:

```
gunicorn -w 4 -b 0.0.0.0:8020 --timeout 3600 --max-requests 10000 --disable-redirect-access-to-syslog --capture-output --error-logfile - extranet:app
```

At the moment,  down versions to solve:

```
Werkzeug==2.1.2
Flask==2.1.3
Flask-Login==0.6.1
```

_Originally posted by @raimonesteve in https://github.com/maxcountryman/flask-login/issues/721#issuecomment-1362795460_

**Comment by raimonesteve** [comment]
Are you test it with gunicorn or wsgi? you need to open multiple workers.

**Comment by davidism** [comment]
I ran the app with gunicorn.
