### ISSUE TITLE
address deprecations from Werkzeug 2.3

### ISSUE THREAD

**Issue by guidoiaquinti** [maxcountryman/flask-login#744]
**Describe the bug**
https://github.com/maxcountryman/flask-login/blob/b30758205211c3af4ac6a41601aee17f6aa45f64/src/flask_login/utils.py#L15 is deprecated and will be removed in Werkzeug 2.4

```
/.venv/lib/python3.9/site-packages/flask_login/utils.py:130: DeprecationWarning: 'werkzeug.urls.url_encode' is deprecated and will be removed in Werkzeug 2.4. Use 'urllib.parse.urlencode' instead.
    netloc=netloc, query=url_encode(md, sort=True)
```

**Additional context**
N/A

**Comment by JWaters02** [comment]
I genuinely don't understand how no one else has made an issue/issues about this here or online anywhere else, but since flask_login/flask now depends on a version of wekzeug that has deprecated url_encode and url_decode, how the hell is anyone successfully using this without that import error?

**Comment by iROCKBUNNY** [comment]
Please! I need this.

**Comment by davidism** [comment]
I'm on vacation right now. A maintainer will work on this when they are available. We are aware of it.

**Comment by davidism** [comment]
#746 was merged.

A volunteer maintainer will work on making a release when they have time available.

**Comment by davidism** [comment]
I will merge #813 and start the release process for 0.6.3 tomorrow.

**Comment by davidism** [comment]
[Flask 0.6.3 is available on PyPI.](https://pypi.org/project/Flask-Login/0.6.3/)
