### ISSUE TITLE
Login_Manager.User_Loader is not called

### ISSUE THREAD

**Issue by ryansherby** [maxcountryman/flask-login#765]
**Describe the bug**
Function decorated with @login_manager.user_loader is not called when endpoint is contacted. Any endpoints decorated with @login_required improperly (but successfully) trigger the login_manager.authorized_handler despite a successful activation of login_user during the session.

**To Reproduce**
1. Call login_user on a user.
2. Define user_loader and unauthorized handler.
3. Decorate an endpoint with login_required (such as logout).
4. User_loader is not called.

**Expected behavior**
I expect the user_loader to at minimum be called when an endpoint is contacted.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: localhost 
 - Version:

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided. `user_loader` is called when `current_user` is accessed. `login_required` accesses `current_user`.

**Comment by ryansherby** [comment]
@davidism When you say current user is accessed, are you referring to implicit access through login_required?

**Comment by ryansherby** [comment]
Hi @davidism ,

I just wanted to make note that the reason for my issue is that is_active was not returning True. The default functionality accessed by User class’ “active” property and found that it was null. After setting it to default=True, users can now log in.
