### ISSUE TITLE
0.6.2 issue

### ISSUE THREAD

**Issue by glen020** [maxcountryman/flask-login#768]
I fixed my issue by rolling back to 6.0 and haven't had time to look into this further.

My flask session was intermixing. 
If user one on computer one logged in everything was okay.

If user two navigated to pages where Login was required in on computer two, they would be given user ones logged in session.

I'm just on my mobile phone right now and will include my requirements file when I get a chance.

On my local computer I couldn't replicate the air but it happened in azure web app.

I rolled back to 0.6.0 and that solved it. But a very scary security risk.

**Comment by davidism** [comment]
You're pushing contexts when you shouldn't.
