### ISSUE TITLE
flask-login: ImportError: cannot import name 'url_decode' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by xconnected** [maxcountryman/flask-login#773]
Flask-Login is not compatible anymore  with Werkzeug > 2.2.3
Importing Flask-Login results in:

ImportError: cannot import name 'url_decode' from 'werkzeug.urls'

**Comment by yossivainshtein** [comment]
This seems to be due to the release of Werkzeug==3.0.0 yesterday (sep 30th)
Please fix this!

**Comment by ketaro** [comment]
If you search open issues, you'll find this has already being addressed in #744

**Comment by davidism** [comment]
Duplicate of #744, fixed by #746. A volunteer maintainer will work on making a release when they have time available.
