### ISSUE TITLE
`werkzeug.urls.url_decode` is deprecated and cannot be used in werkzeug 3

### ISSUE THREAD

**Issue by liwii** [maxcountryman/flask-login#775]
**Describe the bug**
In this line, `from werkzeug.urls import url_decode` fails with latest `werkzeug==3.0.0`.
https://github.com/maxcountryman/flask-login/blob/31e20a3cc143b8d07d6a67f18d4613e3ef85f1a0/src/flask_login/utils.py#L14

This is because `werkzeug.urls.url_decode` is already deprecated and removed from `werkzeug==3.0`.
(Ref: https://github.com/pallets/werkzeug/pull/2768/files#diff-342c3ac7878fc8165fb66b641c3a05ae0b4e5da5c9273fd00db272d61422bb89L3)

Their suggestion is to use `urllib.parse.parse_qs` instead.

**To Reproduce**
Import `flask_login` with `werkzeug==3.0.0`

**Comment by davidism** [comment]
Please search for duplicates first.

**Comment by davidism** [comment]
Duplicate of #744, fixed by #746. A volunteer maintainer will work on making a release when they have time available.
