### ISSUE TITLE
Require flask/werkzeug < 3

### ISSUE THREAD

**Issue by hofrob** [maxcountryman/flask-login#783]
Since there are currently a few bugs or incompatibilities with the new versions of flask and werkzeug, it would make sense to block this in `setup.py`. This would just be a quick fix until the new version is released.

Right now, you're letting user discover this themselves which could be prevented.

**Comment by davidism** [comment]
Please search for duplicates first.

**Comment by davidism** [comment]
Duplicate of #744, fixed by #746. A volunteer maintainer will work on making a release when they have time available.
