### ISSUE TITLE
Flask Login 0.6.2 does not support Werkzeug 3.0.0

### ISSUE THREAD

**Issue by adriiamontoto** [maxcountryman/flask-login#784]
When flask 2.3.3 app with flask login 0.6.2 is executed it drops an: `ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)`. I think because of the resent release of Werkzeug from 2.3.7 to 3.0.0.

![image](https://github.com/maxcountryman/flask-login/assets/75563346/5a3579c2-5570-4152-82d0-591e7186edcd)

This happens because of the setup.py from flask-login:
![image](https://github.com/maxcountryman/flask-login/assets/75563346/3d7313e6-c765-4df5-bfa1-60d4722995be)

When in the requirements file I install Werkzeug 2.3.7 before flask-login 0.6.2, it works, but this is not a solution :(.

**Comment by adriiamontoto** [comment]
Duplicated :(

**Comment by davidism** [comment]
Duplicate of #744, fixed by #746. A volunteer maintainer will work on making a release when they have time available.
