### ISSUE TITLE
ImportError with werkzeug.urls.url_decode in Flask-Login

### ISSUE THREAD

**Issue by yunustalip** [maxcountryman/flask-login#786]
Hello,

I encountered an ImportError when Flask-Login's latest version tries to import werkzeug.urls.url_decode. This issue seems to stem from the fact that in the recent versions of werkzeug, the url_encode and url_decode functions are no longer present in the werkzeug.urls module.

Error Message:

arduino
Copy code
File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 14, in <module>
    from werkzeug.urls import url_decode
Proposed Solution:
You can replace these functions using the werkzeug.datastructures.MultiDict class. For example:

python
Copy code
from werkzeug.datastructures import MultiDict

#For url_decode:
md = MultiDict.from_url(encoded_string)

#For url_encode:
md = MultiDict(your_data_dict)
encoded_string = md.to_url()

Thank you!

**Comment by Puyodead1** [comment]
theres already a bunch of issues about this

**Comment by davidism** [comment]
Please search for duplicates first.

**Comment by davidism** [comment]
Duplicate of #744, fixed by #746. A volunteer maintainer will work on making a release when they have time available.
