### ISSUE TITLE
cannot import name 'url_decode' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by gonatienza** [maxcountryman/flask-login#787]
**Describe the bug**
import flask_login fails with ImportError: cannot import name 'url_decode' from 'werkzeug.urls' after latest werkzeug update.

In -> https://github.com/pallets/werkzeug/blob/2.3.x/src/werkzeug/urls.py -> contains the deffinition for  url_decode.
In -> https://github.com/pallets/werkzeug/blob/3.0.x/src/werkzeug/urls.py -> url_decode does not exist anymore.

**Comment by davidism** [comment]
Please search for duplicates first.

**Comment by davidism** [comment]
Duplicate of #744, fixed by #746. A volunteer maintainer will work on making a release when they have time available.
