### ISSUE TITLE
Session key value pairs disappears after leaving the route that set it.

### ISSUE THREAD

**Issue by Thambolo** [maxcountryman/flask-login#795]
**Describe the bug**
The flask session key value pairs go missing. But the flask-login session data is still there, could it be that some function is deleting the regular flask session data
For example, I set session['phone'] = 12345678 in /home route, but when I try to access it in another route /dashboard, it goes missing.

**Flask Log**
ROUTE WHERE SESSION DATA WAS SET:
<SecureCookieSession {'_flashes': [('message', 'Please log in to access this page.'), ('message', 'Please log in to access this page.')], '_fresh': True, '_id': 'REDACTED', '_user_id': '1', 'csrf_token': 'REDACTED', **'phone': '12345678'**}>

127.0.0.1 - - [09/Oct/2023 22:56:48] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [09/Oct/2023 22:57:57] "GET /?code=REDACTED HTTP/1.1" 200 -

IT DISAPPEARS HERE:
<SecureCookieSession {'_flashes': [('message', 'Please log in to access this page.'), ('message', 'Please log in to access this page.')], '_fresh': True, '_id': 'REDACTED', '_user_id': '1', 'csrf_token': 'REDACTED'}>

**Additional context**
-using Flask-login with regular flask's sessions
-requests are done using ajax on the client

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided. When reporting an issue, be sure to include a minimal reproducible example.
