### ISSUE TITLE
Werkzeug deprecated methods have been removed and are still used in flask-login

### ISSUE THREAD

**Issue by Awilen-Bernkastel** [maxcountryman/flask-login#797]
**Describe the bug**
Launching a Flask app that is using Flask-login fails.

Python version: 3.12.0
Flask version: 3.0.0
Flask-login version: 0.6.2
Werkzeug version: 3.0.0

**To Reproduce**
As of 10/10/2023, have Flask and Flask-login as requirements for your app, without version enforcement. Install with pip.

**Expected behavior**

**Screenshots**
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (C:\Users\***\Documents\dev\python\project_name\venv\Lib\site-packages\werkzeug\urls.py). Did you mean: 'urlencode'?

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Updating Flask-login to use the functions within urllib.parse where applicable as explained in the Werkzeug deprecation notices solves the issue, specifically in utils.py.

It appears this has been resolved last week in this repository, although the version available through pip doesn't seem to be up-to-date.

**Comment by erdnaxeli** [comment]
This was already fixed in https://github.com/maxcountryman/flask-login/pull/746. The release will come.

**Comment by oaokm** [comment]
That so good, @erdnaxeli. But with your expectation, how long time  for release flask-login 0.6.3

and thx :)

**Comment by davidism** [comment]
Please search for duplicates first.
