### ISSUE TITLE
When to release a Flask3.0-compatible update?

### ISSUE THREAD

**Issue by oaokm** [maxcountryman/flask-login#800]
Hello,
I'm following the project page, and I've noticed that anything related to the flask 3.0 compatibility update closes, adding a comment is useless.

What interests us now, when is Flask-Login compatible with flask 3.0? 

And Thank\'s

**Comment by davidism** [comment]
Please search for duplicates first.

The volunteer maintainers are aware of this and will work on it when they have availability.

**Comment by davidism** [comment]
Duplicate of #744, fixed by #746. A volunteer maintainer will work on making a release when they have time available.
