### ISSUE TITLE
Flask-Login compatibility issue with Flask 3.0 not deployed to PyPI

### ISSUE THREAD

**Issue by clevrf0x** [maxcountryman/flask-login#805]
**Describe the bug**
A new compatibility issue between Flask-Login and Flask 3.0 has been fixed, but the fix has not been deployed to PyPI. This is causing users to install an older version of Flask-Login that is not compatible with Flask 3.0, and they need to manually apply the fix in the utils.py file.

**To Reproduce**
1. Go to the project page on PyPI or use pip to install Flask-Login.
2. Install Flask 3.0 or use a project that requires Flask 3.0.
3. Observe that Flask-Login is not compatible with Flask 3.0 and manual changes to utils.py are required.

**Expected behavior**
Flask-Login should be compatible with Flask 3.0 out of the box, and users should not need to make manual changes to utils.py.

**Screenshots**
N/A

**Additional context**
This issue is causing problems for users who want to use Flask-Login with Flask 3.0. The fix has been implemented, but it needs to be deployed to PyPI to ensure users get the correct version. The solution might involve triggering deployment on PyPI.

**Comment by oaokm** [comment]
Hi @clevrf0x ,
everyone complains about this issue since the release of flask3.0.
collaborators close issue without temporary solution

the only solution to this problem is reinstall `Werkzeug` to 2.3.0

```sh
$ pip install Werkzeug==2.3.0
```

and i hope to works with you.

**Comment by clevrf0x** [comment]
Hello @oaokm,

The issue was resolved two weeks ago with the implementation of #778. However, the fix has not been deployed to PyPI. As a result, users attempting to install Flask-Login are still receiving an outdated version that lacks compatibility with Flask 3.0. There is no need to revert to an older version of Werkzeug. Users can manually apply the patch at present. This issue pertains to the deployment of the recent fix to the PyPI package.

**Comment by oaokm** [comment]
Thank you on this clarification, @clevrf0x  ♥️
And i will try this solution.
And i hope for collaborators deployment of the recent fix to the PyPI package.

**Comment by davidism** [comment]
Duplicate of #744, fixed by #746. A volunteer maintainer will work on making a release when they have time available.
