### ISSUE TITLE
The answer to all the flask 3/werkzeug 3/url_decode/package not in pypi-related questions

### ISSUE THREAD

**Issue by tumbl3w33d** [maxcountryman/flask-login#809]
There are countless tickets here closed as duplicated and everyone's waiting for this to be available, especially now that there's a CVE in werkzeug and people want to update for security reasons. It took me more time than it should to figure out what's the situation by going through all these closed tickets.

TL;DR: it's fixed but not released due to maintainer's not having time for it.

I didn't find a workaround proposed, so I went the "build from git" way and will share that option here for those that are not that familiar with what pip can do. You replace `flask-login` in your `requirements.txt` with the following line:
`git+https://github.com/maxcountryman/flask-login.git#egg=flask-login`

That's not exactly stable because you would get the latest state from master everytime you update dependencies or re-create the virtualenv. You can pin to a commit hash too with something like
`git+https://github.com/maxcountryman/flask-login.git@<commit-hash>#egg=flask-login`

Don't forget to observe the progress here so you don't end up stuck with an old version that does not automatically update anymore.

And a last hint to the maintainers here: I know it's annoying to handle all the duplicates, but there are better ways than just closing as duplicated **without linking the one ticket you chose as original and which hopefully contains all the answers**. Also, there's the possibility to pin issues in github, so everyone would find it quickly and not create yet another one.

I will close this so it's not another duplicate to be closed by a maintainer.

**Comment by davidism** [comment]
Duplicate of #744, fixed by #746. A volunteer maintainer will work on making a release when they have time available.
