### ISSUE TITLE
Where's the duplicate issue for 0.6.2 incompatibility?

### ISSUE THREAD

**Issue by yomajo** [maxcountryman/flask-login#811]
Instead of closing issues for 0.6.2 / updated werkzeug incompatibility, [davidism](https://github.com/davidism), please give community some clarity:
- Link to duplicate issue (there isn't an open one)
- Timeline for new release, even if it's in 2026

Closing issue and disabling comments looks bad on whole pallets ecosystem imo.

**Comment by erdnaxeli** [comment]
it was fixed here https://github.com/maxcountryman/flask-login/pull/746

**Comment by yomajo** [comment]
With all due respect, if it's not on PyPI - it's not fixed.

**Comment by Kache** [comment]
I think #744 (and/or #805) should be re-opened (and perhaps pinned) for a few reasons:

 * "if it's not on PyPI - it's not fixed."
 * leaving it closed makes it difficult to find, making "Please search for duplicates first" very dismissive
 * once it's easier to find and communication is clear, there'll be less duplicates
 * it centralizes a place to gather & share workarounds, e.g. #809

**Comment by davidism** [comment]
Duplicate of #744, fixed by #746. A volunteer maintainer will work on making a release when they have time available.
