### ISSUE TITLE
sqlalchemy.exc.LegacyAPIWarning: The Query.get() method is considered legacy as of the 1.x series of SQLAlchemy and becomes a legacy construct in 2.0. The method is now available as Session.get() (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)

### ISSUE THREAD

**Issue by TruncatedDinosour** [maxcountryman/flask-login#822]
**Describe the bug**
when using the library, or specifically `is_authenticated`, i get this warning

```
sqlalchemy.exc.LegacyAPIWarning: The Query.get() method is considered legacy as of the 1.x series of SQLAlchemy and becomes
a legacy construct in 2.0. The method is now available as Session.get() (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
```

**To Reproduce**
just use the library lol

**Expected behavior**
for it not to throw the warning

**Screenshots**
no lol

```py
sqlalchemy.exc.LegacyAPIWarning: The Query.get() method is considered legacy as of the 1.x series of SQLAlchemy and becomes
a legacy construct in 2.0. The method is now available as Session.get() (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] arch linux
 - Browser [e.g. chrome, safari] furryfox 119
 - Version [e.g. 22] of flask-sqalchemy ? 3.1.1 on sqlalchemy 2.0.23

**Smartphone (please complete the following information):**
hows this relevent

**Additional context**
cat

**Comment by davidism** [comment]
That would be how SQLAlchemy is being used within your code, not within Flask-Login itself. You'll need to address that yourself.

**Comment by TruncatedDinosour** [comment]
> That would be how SQLAlchemy is being used within your code, not within Flask-Login itself. You'll need to address that yourself.

im quite literally using `current_user.is_authenticated` lol

**Comment by TruncatedDinosour** [comment]
oh wait, the `load_user`
ty
