### ISSUE TITLE
wrong default value of REMEMBER_COOKIE_SAMESITE

### ISSUE THREAD

**Issue by Sparkonix11** [maxcountryman/flask-login#848]
Issue:
The default value of SameSite is None which is ignored by browsers therefore set it to Lax

![Screenshot](https://github.com/maxcountryman/flask-login/assets/76007612/a99c73b7-71fd-49ff-87a8-9fe1912b59cd)

**Comment by davidism** [comment]
Fairly sure that's deliberate. `None` is a valid value, even if it's not what browsers like nowadays. You would set `REMEMBER_COOKIE_SAMESITE = "None"` in your own application if that's what your application needs.

**Comment by Sparkonix11** [comment]
> Fairly sure that's deliberate. `None` is a valid value, even if it's not what browsers like nowadays. You would set `REMEMBER_COOKIE_SAMESITE = "None"` in your own application if that's what your application needs.

took me about an hour to find the same as it is already by default set to None as per documentation. I created issue just to create a pull request so that someone wont face the same issue again

**Comment by davidism** [comment]
`None` is different than `"None"`

**Comment by Sparkonix11** [comment]
i might be wronf

> `None` is different than `"None"`. I get that that's confusing, but they both have meaning (don't set, vs set to the string `"None"`) which have different browser behaviors.

i might be wrong though but if the default value which is `None` is not recognised by the browser and by changing the value to `"None"` it is working as expected then why is `None` is set as by default. and sorry if i am not understanding it properly , it is just i am new to python backend dev
