### ISSUE TITLE
current_user.is_authenticated always False  even if I'm logged in successfully

### ISSUE THREAD

**Issue by zystudios** [maxcountryman/flask-login#851]
If I use the @login_require decorator, then it is able to detect the logged in user, because without logging in it is not possible to execute the function

```python

@app.route('/test', methods=['POST'])
@login_required
def test():
    print(current_user.is_authenticated)
    # is_authenticated always True

```

But I don't use the @login_require decorator, how can I tell if I'm currently logged in or not?

```python
@app.route('/check-if-login', methods=['get'])
def check():
    print(current_user.is_authenticated)
    # current_user is <flask_login.mixins.AnonymousUserMixin object at 0x000002C5BE65B850>
    # is_authenticated always False even if I'm logged in.

```

So this current_user must be @login_required to work?

Thanks

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided. Be sure to include a minimal reproducible example when reporting an issue. If a user is logged in, they will be whether login is required for a view or not.
